# frozen_string_literal: true

require "minitest/autorun"
require "tmpdir"

require_relative "../lib/noisemaker_cpu/kernel_cache"
require_relative "../lib/noisemaker_cpu/pass_runner"

# Mirrors t/04-kernel-smoke.t: renders a representative slice of the catalog
# (one generator and one filter per namespace, plus the native-adapter and
# draw-op effects) via NoisemakerCpu::Renderer.render_effect/meta, checking
# dimensions, determinism, and that every pixel is finite. That real mirror
# needs the generated Ruby kernel bundle (Worker E) plus Workers A/B/D's
# files, so it `skip`s cleanly with an explicit reason while any of those are
# unavailable (guarded by File.exist? / rescue).
#
# Independent of all of that: this worker's own eval/ctx/out plumbing
# (KernelCache + PassRunner::Ctx) is proven directly against a hand-written
# kernel file, following the contract's kernel ABI example, with a minimal
# fake `rt` object -- self-sufficient today regardless of any other worker's
# progress.
class TestKernelSmoke < Minitest::Test
  # A minimal stand-in for NoisemakerCpu::Runtime exposing only the rt
  # surface the hand-written kernel below actually calls (f32/i/bool/binary),
  # so this test never depends on runtime.rb.
  class FakeRt
    def f32(x)
      [x].pack("e").unpack1("e")
    end

    def i(x)
      x.to_i
    end

    # Contract trap #1: rt comparison ops keep returning Integer 0/1 like
    # Perl; every condition context goes through rt.bool.
    def bool(x)
      x != 0
    end

    def binary(op, a, b, *_rest)
      case op
      when "==" then a == b ? 1 : 0
      else raise "FakeRt#binary: unsupported op #{op}"
      end
    end
  end

  HAND_WRITTEN_KERNEL_SOURCE = <<~'RUBY'
    # Generated by NoisemakerCpu::Transpiler - do not edit.
    run_pixel = lambda do |ctx, out|
      rt = ctx.rt
      u = ctx.uniforms
      tex = ctx.texture_binding('inputTex')
      _u_mode = u.key?('mode') ? u['mode'] : 0
      base = rt.f32(0.25)
      bumped = rt.bool(rt.binary('==', _u_mode, rt.i(1))) ? rt.f32(base + rt.f32(0.5)) : base
      out[0] = rt.f32(bumped)
      out[1] = rt.f32(ctx.frag_coord[0])
      out[2] = rt.f32(ctx.uv[0])
      out[3] = tex.nil? ? 0.0 : 1.0
    end
    { kernel: run_pixel, uses_derivatives: false }
  RUBY

  # ---- (c) ALWAYS run: eval/ctx/out plumbing, self-sufficient today ----

  def test_kernel_cache_eval_loading_and_lru_behavior
    Dir.mktmpdir("kernel-smoke") do |dir|
      path = File.join(dir, "hand_written__test__main.rb")
      File.write(path, HAND_WRITTEN_KERNEL_SOURCE)

      # Bare load_kernel: eval's the source and returns the { kernel:,
      # uses_derivatives: } hash the contract's ABI specifies.
      compiled = NoisemakerCpu::KernelCache.load_kernel(File.read(path), path)
      assert_kind_of Hash, compiled
      assert_respond_to compiled[:kernel], :call
      refute compiled[:uses_derivatives]

      # A source that doesn't yield { kernel: ... } is rejected.
      assert_raises(RuntimeError) { NoisemakerCpu::KernelCache.load_kernel("{ nope: 1 }", "<bad>") }
      # A source with a genuine Ruby syntax error is rejected too (SyntaxError
      # is not a StandardError in Ruby -- must be caught explicitly).
      assert_raises(RuntimeError) { NoisemakerCpu::KernelCache.load_kernel("def broken(", "<bad-syntax>") }

      # LRU cache wrapper: a miss compiles via the factory; a hit returns the
      # SAME compiled hash without calling the factory again.
      cache = NoisemakerCpu::KernelCache.new
      factory_calls = 0
      factory = lambda do
        factory_calls += 1
        File.read(path)
      end
      first = cache.get("hand_written:main", factory)
      second = cache.get("hand_written:main", factory)
      assert_equal 1, factory_calls
      assert_same first, second
      assert_equal 1, cache.stats[:entries]
      assert_equal 1, cache.stats[:hits]
      assert_equal 1, cache.stats[:misses]

      cache.clear
      assert_equal 0, cache.stats[:entries]

      # ---- ctx/out plumbing: run the compiled kernel through a real Ctx ----
      fake_rt = FakeRt.new
      bound_tex = Object.new
      ctx = NoisemakerCpu::Ctx.new(
        rt: fake_rt,
        uniforms: { "mode" => 1 },
        textures: { "inputTex" => bound_tex },
        resolution: [8.0, 8.0],
        time: 0.25,
        seed: 1,
        blank: nil
      )
      ctx.frag_coord = [4.5, 4.5, 0.0, 1.0]
      ctx.uv = [0.5625, 0.5625]
      out = [0.0, 0.0, 0.0, 0.0]
      first[:kernel].call(ctx, out)
      assert_in_delta 0.75, out[0], 1e-6 # mode == 1 branch: 0.25 + 0.5
      assert_in_delta 4.5, out[1], 1e-6 # ctx.frag_coord threaded through
      assert_in_delta 0.5625, out[2], 1e-6 # ctx.uv threaded through
      assert_in_delta 1.0, out[3], 1e-6 # texture_binding found the bound texture

      # mode != 1 takes the other branch of the hand-written kernel's
      # conditional -- this is also the rt.bool(0)-is-false check (contract
      # trap #1): a bare `if 0` in Ruby would be truthy and pick the wrong
      # branch, which would show up here as 0.75 instead of 0.25.
      ctx2 = NoisemakerCpu::Ctx.new(rt: fake_rt, uniforms: { "mode" => 0 }, textures: {},
        resolution: [8.0, 8.0], time: 0.25, seed: 1, blank: nil)
      ctx2.frag_coord = [1.5, 1.5, 0.0, 1.0]
      ctx2.uv = [0.1875, 0.1875]
      out2 = [0.0, 0.0, 0.0, 0.0]
      first[:kernel].call(ctx2, out2)
      assert_in_delta 0.25, out2[0], 1e-6
      assert_in_delta 0.0, out2[3], 1e-6 # unbound sampler: texture_binding returned nil (no blank configured)
    end
  end

  def test_ctx_texture_binding_defaults_to_blank
    blank = Object.new
    bound = Object.new
    ctx = NoisemakerCpu::Ctx.new(rt: FakeRt.new, uniforms: {}, textures: { "inputTex" => bound }, blank: blank)
    assert_same bound, ctx.texture_binding("inputTex")
    assert_same blank, ctx.texture_binding("missingTex")
    assert_equal({}, NoisemakerCpu::Ctx.new(rt: FakeRt.new).uniforms)
  end

  # ---- (a)/(b): mirror t/04-kernel-smoke.t; skip cleanly until the bundle +
  # Workers A/B/D/E dependency chain is ready ----

  EFFECTS = %w[
    synth/solid synth/curl synth/noise
    filter/invert filter/vignette filter/crt filter/snow filter/palette
    filter/wormhole filter/stamp
    classicNoisedeck/noise classicNoisedeck/fractal
    mixer/blendMode
  ].freeze

  def renderer_available?
    return @renderer_available if defined?(@renderer_available)

    bundle_metadata = File.expand_path("../lib/noisemaker_cpu/bundle/metadata.json", __dir__)
    @renderer_available =
      if !File.exist?(bundle_metadata)
        @skip_reason = "generated bundle not present yet at #{bundle_metadata} (Worker E)"
        false
      else
        begin
          require_relative "../lib/noisemaker_cpu/renderer"
          true
        rescue LoadError, StandardError => e
          @skip_reason = "renderer.rb dependency chain not ready yet: #{e.class}: #{e.message}"
          false
        end
      end
  end

  def test_bundle_effects_render_finite_deterministic_pixels
    skip @skip_reason || "renderer/bundle dependencies not ready yet" unless renderer_available?

    solid = NoisemakerCpu::Renderer.render_effect("synth/solid", { "color" => "#4080c0" }, nil,
      width: 8, height: 8, seed: 1, time: 0.25)

    EFFECTS.each do |eid|
      eff = NoisemakerCpu::Renderer.meta["effects"][eid]
      assert eff, "#{eid} in bundle"
      inputs = eff["kind"] == "generator" ? {} : { "inputTex" => solid }
      a = NoisemakerCpu::Renderer.render_effect(eid, {}, inputs, width: 8, height: 8, seed: 1, time: 0.25)
      assert_equal 8, a.width, "#{eid} width"
      bad = a.data.count { |v| !v.finite? }
      assert_equal 0, bad, "#{eid} all pixels finite"
      b = NoisemakerCpu::Renderer.render_effect(eid, {}, inputs, width: 8, height: 8, seed: 1, time: 0.25)
      assert_equal a.to_rgba8, b.to_rgba8, "#{eid} deterministic"
    end
  end

  def test_seed_changes_generator_output
    skip @skip_reason || "renderer/bundle dependencies not ready yet" unless renderer_available?

    s1 = NoisemakerCpu::Renderer.render_effect("synth/noise", {}, nil, width: 8, height: 8, seed: 1, time: 0.25)
    s2 = NoisemakerCpu::Renderer.render_effect("synth/noise", {}, nil, width: 8, height: 8, seed: 2, time: 0.25)
    refute_equal s1.to_rgba8, s2.to_rgba8, "render seed threads into the seed param"
  end

  # Regression: kernel eval must not share the host program's local scope.
  # TOPLEVEL_BINDING.dup shares the main script's local environment, so a
  # kernel local named `size`/`seed` (13 generated kernels have one) would
  # assign straight into the host's variables — this clobbered the parity
  # harness's `size` local with a texture-size array during integration.
  def test_kernel_eval_cannot_clobber_host_locals
    src = <<~KERNEL
      run_pixel = lambda do |ctx, out|
        size = [64.0, 64.0]
        seed = 999
        out[0] = size[0]
        out[1] = seed.to_f
        out[2] = 0.0
        out[3] = 1.0
      end
      { kernel: run_pixel, uses_derivatives: false }
    KERNEL
    probe = lambda do
      size = 8
      seed = 1
      k = NoisemakerCpu::KernelCache.load_kernel(src, "clobber-probe")
      out = [0.0, 0.0, 0.0, 0.0]
      k[:kernel].call(nil, out)
      [size, seed, out]
    end
    size, seed, out = probe.call
    assert_equal 8, size, "kernel-local `size` leaked into host scope"
    assert_equal 1, seed, "kernel-local `seed` leaked into host scope"
    assert_equal [64.0, 999.0], out[0, 2], "kernel body executed with its own locals"
  end
end
