# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  map__float_float_float_float_float = pcg__uvec3 = prng__vec3 = brightnessContrast__vec3 = hsv2rgb__vec3 = periodicFunction__float = mod289__vec3 = mod289__vec2 = permute__vec3 = simplexValue__vec2_float_float_float_float = sineNoise__vec2_float_float_float_float = positiveModulo__int_int = randomFromLatticeWithOffset__vec2_float_float_float_ivec2 = constant__vec2_float_float_float = constantOffset__vec2_float_float_float_ivec2 = quadratic3__float_float_float_float = catmullRom3__float_float_float_float = quadratic3x3Value__vec2_float_float_float = catmullRom3x3Value__vec2_float_float_float = blendBicubic__float_float_float_float_float = catmullRom4__float_float_float_float_float = blendLinearOrCosine__float_float_float_int = bicubicValue__vec2_float_float_float = catmullRom4x4Value__vec2_float_float_float = value__vec2_float_float_float = noise__vec2_float = main__void = nil
  _retc = nil
  _u__NOISE_TYPE = u.key?('NOISE_TYPE') ? u['NOISE_TYPE'] : 0
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  _u_wrap = u.key?('wrap') ? u['wrap'] : 0
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_noiseScale = u.key?('noiseScale') ? u['noiseScale'] : rt.f(0.0)
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_hueRotation = u.key?('hueRotation') ? u['hueRotation'] : rt.f(0.0)
  _u_hueRange = u.key?('hueRange') ? u['hueRange'] : rt.f(0.0)
  _u_intensity = u.key?('intensity') ? u['intensity'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  map__float_float_float_float_float = lambda do |value, inMin, inMax, outMin, outMax|
    return rt.binary('+', outMin, rt.binary('/', rt.binary('*', rt.binary('-', outMax, outMin, 1, 'float'), rt.binary('-', value, inMin, 1, 'float'), 1, 'float'), rt.binary('-', inMax, inMin, 1, 'float'), 1, 'float'), 1, 'float')
  end
  pcg__uvec3 = lambda do |v|
    v = rt.copy(v, 'uint')
    v.replace(rt.binary('+', rt.binary('*', v, rt.construct(1, rt.i(1664525), 'uint'), 3, 'uint'), rt.construct(1, rt.i(1013904223), 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    v.replace(rt.binary('^', v, rt.binary('>>', v, rt.construct(1, rt.i(16), 'uint'), 3, 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    return v
  end
  prng__vec3 = lambda do |p|
    p = rt.copy(p, 'float')
    p = rt.assign_swizzle(p, 'x', (rt.bool(rt.binary('>=', rt.swizzle(p, 'x'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'x'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'x')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    p = rt.assign_swizzle(p, 'y', (rt.bool(rt.binary('>=', rt.swizzle(p, 'y'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'y'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'y')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    p = rt.assign_swizzle(p, 'z', (rt.bool(rt.binary('>=', rt.swizzle(p, 'z'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'z'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'z')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    return rt.binary('/', rt.construct(3, pcg__uvec3.call(rt.construct(3, rt.construct(3, p), 'uint'))), rt.construct(1, rt.construct(1, rt.i(4294967295), 'uint')), 3, 'float')
  end
  brightnessContrast__vec3 = lambda do |color|
    color = rt.copy(color, 'float')
    bright = nil; cont = nil
    bright = map__float_float_float_float_float.call(_u_intensity, rt.unary('-', rt.f(100)), rt.f(100), rt.unary('-', rt.f(0.40000000000000002)), rt.f(0.40000000000000002))
    cont = rt.f(1)
    if rt.bool(rt.binary('<', _u_intensity, rt.f(0)))
      cont = map__float_float_float_float_float.call(_u_intensity, rt.unary('-', rt.f(100)), rt.f(0), rt.f(0.5), rt.f(1))
    else
      cont = map__float_float_float_float_float.call(_u_intensity, rt.f(0), rt.f(100), rt.f(1), rt.f(1.5))
    end
    color.replace((rt.binary('+', rt.binary('+', rt.binary('*', rt.binary('-', color, rt.f(0.5), 3, 'float'), cont, 3, 'float'), rt.f(0.5), 3, 'float'), bright, 3, 'float')).map { |c| rt.f32(c) })
    return color
  end
  hsv2rgb__vec3 = lambda do |hsv|
    hsv = rt.copy(hsv, 'float')
    c = nil; h = nil; m = nil; rgb = nil; s = nil; v = nil; x = nil
    h = rt.component_wise('fract', rt.swizzle(hsv, 'x'))
    s = rt.swizzle(hsv, 'y')
    v = rt.swizzle(hsv, 'z')
    c = rt.binary('*', v, s, 1, 'float')
    x = rt.binary('*', c, rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.component_wise('mod', rt.binary('*', h, rt.f(6), 1, 'float'), rt.f(2)), rt.f(1), 1, 'float')), 1, 'float'), 1, 'float')
    m = rt.binary('-', v, c, 1, 'float')
    rgb = rt.construct(3, 0.0)
    if rt.bool((rt.bool(rt.binary('<=', rt.f(0), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(1), rt.f(6), 1, 'float'))) ? 1 : 0))
      rgb.replace((rt.construct(3, c, x, rt.f(0))).map { |c| rt.f32(c) })
    else
      if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(1), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(2), rt.f(6), 1, 'float'))) ? 1 : 0))
        rgb.replace((rt.construct(3, x, c, rt.f(0))).map { |c| rt.f32(c) })
      else
        if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(2), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(3), rt.f(6), 1, 'float'))) ? 1 : 0))
          rgb.replace((rt.construct(3, rt.f(0), c, x)).map { |c| rt.f32(c) })
        else
          if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(3), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(4), rt.f(6), 1, 'float'))) ? 1 : 0))
            rgb.replace((rt.construct(3, rt.f(0), x, c)).map { |c| rt.f32(c) })
          else
            if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(4), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(5), rt.f(6), 1, 'float'))) ? 1 : 0))
              rgb.replace((rt.construct(3, x, rt.f(0), c)).map { |c| rt.f32(c) })
            else
              if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(5), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.f(1))) ? 1 : 0))
                rgb.replace((rt.construct(3, c, rt.f(0), x)).map { |c| rt.f32(c) })
              else
                rgb.replace((rt.construct(3, rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
              end
            end
          end
        end
      end
    end
    return rt.binary('+', rgb, rt.construct(3, m, m, m), 3, 'float')
  end
  periodicFunction__float = lambda do |p|
    return map__float_float_float_float_float.call(rt.component_wise('sin', rt.binary('*', p, rt.f(6.2831853071800001), 1, 'float')), rt.unary('-', rt.f(1)), rt.f(1), rt.f(0), rt.f(1))
  end
  mod289__vec3 = lambda do |x|
    x = rt.copy(x, 'float')
    return rt.binary('-', x, rt.binary('*', rt.component_wise('floor', rt.binary('*', x, rt.binary('/', rt.f(1), rt.f(289), 1, 'float'), 3, 'float')), rt.f(289), 3, 'float'), 3, 'float')
  end
  mod289__vec2 = lambda do |x|
    x = rt.copy(x, 'float')
    return rt.binary('-', x, rt.binary('*', rt.component_wise('floor', rt.binary('*', x, rt.binary('/', rt.f(1), rt.f(289), 1, 'float'), 2, 'float')), rt.f(289), 2, 'float'), 2, 'float')
  end
  permute__vec3 = lambda do |x|
    x = rt.copy(x, 'float')
    return mod289__vec3.call(rt.binary('*', rt.binary('+', rt.binary('*', x, rt.f(34), 3, 'float'), rt.f(1), 3, 'float'), x, 3, 'float'))
  end
  simplexValue__vec2_float_float_float_float = lambda do |st, xFreq, yFreq, s, blend|
    st = rt.copy(st, 'float')
    _C = nil; _g = nil; a0 = nil; h = nil; i = nil; i1 = nil; m = nil; ox = nil; p = nil; uv = nil; v = nil; x = nil; x0 = nil; x12 = nil
    _C = rt.construct(4, rt.construct(4, rt.f(0.211324865405187), rt.f(0.36602540378443899), rt.unary('-', rt.f(0.57735026918962595)), rt.f(0.024390243902439001)))
    uv = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    uv = rt.assign_swizzle(uv, 'x', rt.binary('+', rt.swizzle(uv, 'x'), s, 1, 'float'))
    i = rt.construct(2, rt.component_wise('floor', rt.binary('+', uv, rt.dot(uv, rt.swizzle(_C, 'yy')), 2, 'float')))
    x0 = rt.construct(2, rt.binary('+', rt.binary('-', uv, i, 2, 'float'), rt.dot(i, rt.swizzle(_C, 'xx')), 2, 'float'))
    i1 = rt.construct(2, 0.0)
    i1.replace(((rt.bool(rt.binary('>', rt.swizzle(x0, 'x'), rt.swizzle(x0, 'y'))) ? (rt.construct(2, rt.f(1), rt.f(0))) : (rt.construct(2, rt.f(0), rt.f(1))))).map { |c| rt.f32(c) })
    x12 = rt.construct(4, rt.binary('+', rt.swizzle(x0, 'xyxy'), rt.swizzle(_C, 'xxzz'), 4, 'float'))
    x12 = rt.assign_swizzle(x12, 'xy', rt.binary('-', rt.swizzle(x12, 'xy'), i1, 2, 'float'))
    i.replace((mod289__vec2.call(i)).map { |c| rt.f32(c) })
    p = rt.construct(3, permute__vec3.call(rt.binary('+', rt.binary('+', permute__vec3.call(rt.binary('+', rt.swizzle(i, 'y'), rt.construct(3, rt.f(0), rt.swizzle(i1, 'y'), rt.f(1)), 3, 'float')), rt.swizzle(i, 'x'), 3, 'float'), rt.construct(3, rt.f(0), rt.swizzle(i1, 'x'), rt.f(1)), 3, 'float')))
    m = rt.construct(3, rt.component_wise('max', rt.binary('-', rt.f(0.5), rt.construct(3, rt.dot(x0, x0), rt.dot(rt.swizzle(x12, 'xy'), rt.swizzle(x12, 'xy')), rt.dot(rt.swizzle(x12, 'zw'), rt.swizzle(x12, 'zw'))), 3, 'float'), rt.f(0)))
    m.replace((rt.binary('*', m, m, 3, 'float')).map { |c| rt.f32(c) })
    m.replace((rt.binary('*', m, m, 3, 'float')).map { |c| rt.f32(c) })
    x = rt.construct(3, rt.binary('-', rt.binary('*', rt.f(2), rt.component_wise('fract', rt.binary('*', p, rt.swizzle(_C, 'www'), 3, 'float')), 3, 'float'), rt.f(1), 3, 'float'))
    h = rt.construct(3, rt.binary('-', rt.component_wise('abs', x), rt.f(0.5), 3, 'float'))
    ox = rt.construct(3, rt.component_wise('floor', rt.binary('+', x, rt.f(0.5), 3, 'float')))
    a0 = rt.construct(3, rt.binary('-', x, ox, 3, 'float'))
    m.replace((rt.binary('*', m, rt.binary('-', rt.f(1.79284291400159), rt.binary('*', rt.f(0.85373472095313996), rt.binary('+', rt.binary('*', a0, a0, 3, 'float'), rt.binary('*', h, h, 3, 'float'), 3, 'float'), 3, 'float'), 3, 'float'), 3, 'float')).map { |c| rt.f32(c) })
    _g = rt.construct(3, 0.0)
    _g = rt.assign_swizzle(_g, 'x', rt.binary('+', rt.binary('*', rt.swizzle(a0, 'x'), rt.swizzle(x0, 'x'), 1, 'float'), rt.binary('*', rt.swizzle(h, 'x'), rt.swizzle(x0, 'y'), 1, 'float'), 1, 'float'))
    _g = rt.assign_swizzle(_g, 'yz', rt.binary('+', rt.binary('*', rt.swizzle(a0, 'yz'), rt.swizzle(x12, 'xz'), 2, 'float'), rt.binary('*', rt.swizzle(h, 'yz'), rt.swizzle(x12, 'yw'), 2, 'float'), 2, 'float'))
    v = rt.binary('*', rt.f(130), rt.dot(m, _g), 1, 'float')
    return periodicFunction__float.call(rt.binary('-', map__float_float_float_float_float.call(v, rt.unary('-', rt.f(1)), rt.f(1), rt.f(0), rt.f(1)), blend, 1, 'float'))
  end
  sineNoise__vec2_float_float_float_float = lambda do |st, xFreq, yFreq, s, blend|
    st = rt.copy(st, 'float')
    a = nil; b = nil; c = nil; r1 = nil; r2 = nil; uv = nil; x = nil; y = nil
    uv = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    uv = rt.assign_swizzle(uv, 'x', rt.binary('+', rt.swizzle(uv, 'x'), s, 1, 'float'))
    a = blend
    b = blend
    c = rt.binary('-', rt.f(1), blend, 1, 'float')
    r1 = rt.construct(3, rt.binary('+', rt.binary('*', prng__vec3.call(rt.construct(3, s, rt.f(0), rt.f(0))), rt.f(0.75), 3, 'float'), rt.f(0.125), 3, 'float'))
    r2 = rt.construct(3, rt.binary('+', rt.binary('*', prng__vec3.call(rt.construct(3, rt.binary('+', s, rt.f(10), 1, 'float'), rt.f(0), rt.f(0))), rt.f(0.75), 3, 'float'), rt.f(0.125), 3, 'float'))
    x = rt.component_wise('sin', rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('*', rt.swizzle(r1, 'x'), rt.swizzle(uv, 'y'), 1, 'float'), rt.component_wise('sin', rt.binary('+', rt.binary('*', rt.swizzle(r1, 'y'), rt.swizzle(uv, 'x'), 1, 'float'), a, 1, 'float')), 1, 'float'), rt.component_wise('sin', rt.binary('+', rt.binary('*', rt.swizzle(r1, 'z'), rt.swizzle(uv, 'x'), 1, 'float'), b, 1, 'float')), 1, 'float'), c, 1, 'float'))
    y = rt.component_wise('sin', rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('*', rt.swizzle(r2, 'x'), rt.swizzle(uv, 'x'), 1, 'float'), rt.component_wise('sin', rt.binary('+', rt.binary('*', rt.swizzle(r2, 'y'), rt.swizzle(uv, 'y'), 1, 'float'), b, 1, 'float')), 1, 'float'), rt.component_wise('sin', rt.binary('+', rt.binary('*', rt.swizzle(r2, 'z'), rt.swizzle(uv, 'y'), 1, 'float'), c, 1, 'float')), 1, 'float'), a, 1, 'float'))
    return rt.binary('+', rt.binary('*', rt.binary('+', x, y, 1, 'float'), rt.f(0.5), 1, 'float'), rt.f(0.5), 1, 'float')
  end
  positiveModulo__int_int = lambda do |value, modulus|
    r = nil
    if rt.bool(rt.binary('==', modulus, rt.i(0)))
      return rt.i(0)
    end
    r = rt.binary('%', value, modulus, 1, 'int')
    return (rt.bool(rt.binary('<', r, rt.i(0))) ? (rt.binary('+', r, modulus, 1, 'int')) : (r))
  end
  randomFromLatticeWithOffset__vec2_float_float_float_ivec2 = lambda do |st, xFreq, yFreq, s, offset|
    st = rt.copy(st, 'float')
    offset = rt.copy(offset, 'int')
    base = nil; baseFloor = nil; denom = nil; frac = nil; fracBits = nil; freqXInt = nil; freqYInt = nil; jitter = nil; lattice = nil; prngState = nil; seedBits = nil; seedFrac = nil; seedInt = nil; state = nil; xBits = nil; xCombined = nil; xi = nil; yBits = nil; yi = nil
    lattice = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    baseFloor = rt.construct(2, rt.component_wise('floor', lattice))
    base = rt.binary('+', rt.construct(2, rt.construct(2, baseFloor), 'int'), offset, 2, 'int')
    frac = rt.construct(2, rt.binary('-', lattice, baseFloor, 2, 'float'))
    seedInt = rt.construct(1, rt.component_wise('floor', s), 'int')
    seedFrac = rt.component_wise('fract', s)
    xCombined = rt.binary('+', rt.swizzle(frac, 'x'), seedFrac, 1, 'float')
    xi = rt.binary('+', rt.binary('+', rt.swizzle(base, 'x'), seedInt, 1, 'int'), rt.construct(1, rt.component_wise('floor', xCombined), 'int'), 1, 'int')
    yi = rt.swizzle(base, 'y')
    freqXInt = 0
    freqYInt = 0
    if rt.bool(_u_wrap)
      freqXInt = rt.construct(1, rt.binary('+', xFreq, rt.f(0.5), 1, 'float'), 'int')
      freqYInt = rt.construct(1, rt.binary('+', yFreq, rt.f(0.5), 1, 'float'), 'int')
      if rt.bool(rt.binary('>', freqXInt, rt.i(0)))
        xi = positiveModulo__int_int.call(xi, freqXInt)
      end
      if rt.bool(rt.binary('>', freqYInt, rt.i(0)))
        yi = positiveModulo__int_int.call(yi, freqYInt)
      end
    end
    xBits = rt.construct(1, xi, 'uint')
    yBits = rt.construct(1, yi, 'uint')
    seedBits = rt.construct(1, _u_seed, 'uint')
    fracBits = rt.float_bits_to_uint(seedFrac)
    jitter = rt.construct(3, rt.binary('^', rt.binary('*', fracBits, rt.i(374761393), 1, 'uint'), rt.i(2654435769), 1, 'uint'), rt.binary('^', rt.binary('*', fracBits, rt.i(668265263), 1, 'uint'), rt.i(2135587861), 1, 'uint'), rt.binary('^', rt.binary('*', fracBits, rt.i(2246822519), 1, 'uint'), rt.i(2496678324), 1, 'uint'), 'uint')
    state = rt.binary('^', rt.construct(3, xBits, yBits, seedBits, 'uint'), jitter, 3, 'uint')
    prngState = pcg__uvec3.call(state)
    denom = rt.construct(1, rt.i(4294967295))
    return rt.construct(3, rt.binary('/', rt.construct(1, rt.swizzle(prngState, 'x')), denom, 1, 'float'), rt.binary('/', rt.construct(1, rt.swizzle(prngState, 'y')), denom, 1, 'float'), rt.binary('/', rt.construct(1, rt.swizzle(prngState, 'z')), denom, 1, 'float'))
  end
  constant__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    rand = nil; scaledTime = nil
    rand = rt.construct(3, randomFromLatticeWithOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(0), 'int')))
    scaledTime = rt.binary('*', periodicFunction__float.call(rt.binary('-', rt.swizzle(rand, 'x'), _u_time, 1, 'float')), map__float_float_float_float_float.call(rt.component_wise('abs', _u_speed), rt.f(0), rt.f(100), rt.f(0), rt.f(0.25)), 1, 'float')
    return periodicFunction__float.call(rt.binary('-', rt.swizzle(rand, 'y'), scaledTime, 1, 'float'))
  end
  constantOffset__vec2_float_float_float_ivec2 = lambda do |st, xFreq, yFreq, s, offset|
    st = rt.copy(st, 'float')
    offset = rt.copy(offset, 'int')
    rand = nil; scaledTime = nil
    rand = rt.construct(3, randomFromLatticeWithOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, offset))
    scaledTime = rt.binary('*', periodicFunction__float.call(rt.binary('-', rt.swizzle(rand, 'x'), _u_time, 1, 'float')), map__float_float_float_float_float.call(rt.component_wise('abs', _u_speed), rt.f(0), rt.f(100), rt.f(0), rt.f(0.25)), 1, 'float')
    return periodicFunction__float.call(rt.binary('-', rt.swizzle(rand, 'y'), scaledTime, 1, 'float'))
  end
  quadratic3__float_float_float_float = lambda do |p0, p1, p2, _t|
    t2 = nil
    t2 = rt.binary('*', _t, _t, 1, 'float')
    return rt.binary('+', rt.binary('+', rt.binary('*', rt.binary('*', rt.binary('*', p0, rt.f(0.5), 1, 'float'), rt.binary('-', rt.f(1), _t, 1, 'float'), 1, 'float'), rt.binary('-', rt.f(1), _t, 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('*', p1, rt.f(0.5), 1, 'float'), rt.binary('+', rt.binary('+', rt.binary('*', rt.unary('-', rt.f(2)), t2, 1, 'float'), rt.binary('*', rt.f(2), _t, 1, 'float'), 1, 'float'), rt.f(1), 1, 'float'), 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('*', p2, rt.f(0.5), 1, 'float'), t2, 1, 'float'), 1, 'float')
  end
  catmullRom3__float_float_float_float = lambda do |p0, p1, p2, _t|
    t2 = nil; t3 = nil
    t2 = rt.binary('*', _t, _t, 1, 'float')
    t3 = rt.binary('*', t2, _t, 1, 'float')
    return rt.binary('+', rt.binary('+', rt.binary('+', p1, rt.binary('*', rt.binary('*', rt.f(0.5), _t, 1, 'float'), rt.binary('-', p2, p0, 1, 'float'), 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('*', rt.f(0.5), t2, 1, 'float'), rt.binary('-', rt.binary('+', rt.binary('-', rt.binary('*', rt.f(2), p0, 1, 'float'), rt.binary('*', rt.f(5), p1, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(4), p2, 1, 'float'), 1, 'float'), p0, 1, 'float'), 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('*', rt.f(0.5), t3, 1, 'float'), rt.binary('+', rt.binary('-', rt.binary('+', rt.unary('-', p0), rt.binary('*', rt.f(3), p1, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(3), p2, 1, 'float'), 1, 'float'), p0, 1, 'float'), 1, 'float'), 1, 'float')
  end
  quadratic3x3Value__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    f = nil; lattice = nil; v00 = nil; v01 = nil; v02 = nil; v10 = nil; v11 = nil; v12 = nil; v20 = nil; v21 = nil; v22 = nil; y0 = nil; y1 = nil; y2 = nil
    lattice = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    f = rt.construct(2, rt.component_wise('fract', lattice))
    v00 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.unary('-', rt.i(1)), 'int'))
    v10 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.unary('-', rt.i(1)), 'int'))
    v20 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.unary('-', rt.i(1)), 'int'))
    v01 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(0), 'int'))
    v11 = constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
    v21 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(0), 'int'))
    v02 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(1), 'int'))
    v12 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(1), 'int'))
    v22 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(1), 'int'))
    y0 = quadratic3__float_float_float_float.call(v00, v10, v20, rt.swizzle(f, 'x'))
    y1 = quadratic3__float_float_float_float.call(v01, v11, v21, rt.swizzle(f, 'x'))
    y2 = quadratic3__float_float_float_float.call(v02, v12, v22, rt.swizzle(f, 'x'))
    return quadratic3__float_float_float_float.call(y0, y1, y2, rt.swizzle(f, 'y'))
  end
  catmullRom3x3Value__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    f = nil; lattice = nil; v00 = nil; v01 = nil; v02 = nil; v10 = nil; v11 = nil; v12 = nil; v20 = nil; v21 = nil; v22 = nil; y0 = nil; y1 = nil; y2 = nil
    lattice = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    f = rt.construct(2, rt.component_wise('fract', lattice))
    v00 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.unary('-', rt.i(1)), 'int'))
    v10 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.unary('-', rt.i(1)), 'int'))
    v20 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.unary('-', rt.i(1)), 'int'))
    v01 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(0), 'int'))
    v11 = constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
    v21 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(0), 'int'))
    v02 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(1), 'int'))
    v12 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(1), 'int'))
    v22 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(1), 'int'))
    y0 = catmullRom3__float_float_float_float.call(v00, v10, v20, rt.swizzle(f, 'x'))
    y1 = catmullRom3__float_float_float_float.call(v01, v11, v21, rt.swizzle(f, 'x'))
    y2 = catmullRom3__float_float_float_float.call(v02, v12, v22, rt.swizzle(f, 'x'))
    return catmullRom3__float_float_float_float.call(y0, y1, y2, rt.swizzle(f, 'y'))
  end
  blendBicubic__float_float_float_float_float = lambda do |p0, p1, p2, p3, _t|
    b0 = nil; b1 = nil; b2 = nil; b3 = nil; t2 = nil; t3 = nil
    t2 = rt.binary('*', _t, _t, 1, 'float')
    t3 = rt.binary('*', t2, _t, 1, 'float')
    b0 = rt.binary('/', rt.binary('*', rt.binary('*', rt.binary('-', rt.f(1), _t, 1, 'float'), rt.binary('-', rt.f(1), _t, 1, 'float'), 1, 'float'), rt.binary('-', rt.f(1), _t, 1, 'float'), 1, 'float'), rt.f(6), 1, 'float')
    b1 = rt.binary('/', rt.binary('+', rt.binary('-', rt.binary('*', rt.f(3), t3, 1, 'float'), rt.binary('*', rt.f(6), t2, 1, 'float'), 1, 'float'), rt.f(4), 1, 'float'), rt.f(6), 1, 'float')
    b2 = rt.binary('/', rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('*', rt.unary('-', rt.f(3)), t3, 1, 'float'), rt.binary('*', rt.f(3), t2, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(3), _t, 1, 'float'), 1, 'float'), rt.f(1), 1, 'float'), rt.f(6), 1, 'float')
    b3 = rt.binary('/', t3, rt.f(6), 1, 'float')
    return rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('*', p0, b0, 1, 'float'), rt.binary('*', p1, b1, 1, 'float'), 1, 'float'), rt.binary('*', p2, b2, 1, 'float'), 1, 'float'), rt.binary('*', p3, b3, 1, 'float'), 1, 'float')
  end
  catmullRom4__float_float_float_float_float = lambda do |p0, p1, p2, p3, _t|
    return rt.binary('+', p1, rt.binary('*', rt.binary('*', rt.f(0.5), _t, 1, 'float'), rt.binary('+', rt.binary('-', p2, p0, 1, 'float'), rt.binary('*', _t, rt.binary('+', rt.binary('-', rt.binary('+', rt.binary('-', rt.binary('*', rt.f(2), p0, 1, 'float'), rt.binary('*', rt.f(5), p1, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(4), p2, 1, 'float'), 1, 'float'), p3, 1, 'float'), rt.binary('*', _t, rt.binary('-', rt.binary('+', rt.binary('*', rt.f(3), rt.binary('-', p1, p2, 1, 'float'), 1, 'float'), p3, 1, 'float'), p0, 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float')
  end
  blendLinearOrCosine__float_float_float_int = lambda do |a, b, amount, nType|
    if rt.bool(rt.binary('==', nType, rt.i(1)))
      return rt.component_wise('mix', a, b, amount)
    end
    return rt.component_wise('mix', a, b, rt.component_wise('smoothstep', rt.f(0), rt.f(1), amount))
  end
  bicubicValue__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    f = nil; uv = nil; x0y0 = nil; x0y1 = nil; x0y2 = nil; x0y3 = nil; x1y0 = nil; x1y1 = nil; x1y2 = nil; x1y3 = nil; x2y0 = nil; x2y1 = nil; x2y2 = nil; x2y3 = nil; x3y0 = nil; x3y1 = nil; x3y2 = nil; x3y3 = nil; y0 = nil; y1 = nil; y2 = nil; y3 = nil
    uv = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    f = rt.construct(2, rt.component_wise('fract', uv))
    x0y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.unary('-', rt.i(1)), 'int'))
    x0y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(0), 'int'))
    x0y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(1), 'int'))
    x0y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(2), 'int'))
    x1y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.unary('-', rt.i(1)), 'int'))
    x1y1 = constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
    x1y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(1), 'int'))
    x1y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(2), 'int'))
    x2y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.unary('-', rt.i(1)), 'int'))
    x2y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(0), 'int'))
    x2y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(1), 'int'))
    x2y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(2), 'int'))
    x3y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.unary('-', rt.i(1)), 'int'))
    x3y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(0), 'int'))
    x3y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(1), 'int'))
    x3y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(2), 'int'))
    y0 = blendBicubic__float_float_float_float_float.call(x0y0, x1y0, x2y0, x3y0, rt.swizzle(f, 'x'))
    y1 = blendBicubic__float_float_float_float_float.call(x0y1, x1y1, x2y1, x3y1, rt.swizzle(f, 'x'))
    y2 = blendBicubic__float_float_float_float_float.call(x0y2, x1y2, x2y2, x3y2, rt.swizzle(f, 'x'))
    y3 = blendBicubic__float_float_float_float_float.call(x0y3, x1y3, x2y3, x3y3, rt.swizzle(f, 'x'))
    return rt.component_wise('clamp', blendBicubic__float_float_float_float_float.call(y0, y1, y2, y3, rt.swizzle(f, 'y')), rt.f(0), rt.f(1))
  end
  catmullRom4x4Value__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    f = nil; uv = nil; x0y0 = nil; x0y1 = nil; x0y2 = nil; x0y3 = nil; x1y0 = nil; x1y1 = nil; x1y2 = nil; x1y3 = nil; x2y0 = nil; x2y1 = nil; x2y2 = nil; x2y3 = nil; x3y0 = nil; x3y1 = nil; x3y2 = nil; x3y3 = nil; y0 = nil; y1 = nil; y2 = nil; y3 = nil
    uv = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
    f = rt.construct(2, rt.component_wise('fract', uv))
    x0y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.unary('-', rt.i(1)), 'int'))
    x0y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(0), 'int'))
    x0y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(1), 'int'))
    x0y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(2), 'int'))
    x1y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.unary('-', rt.i(1)), 'int'))
    x1y1 = constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
    x1y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(1), 'int'))
    x1y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(2), 'int'))
    x2y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.unary('-', rt.i(1)), 'int'))
    x2y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(0), 'int'))
    x2y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(1), 'int'))
    x2y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(2), 'int'))
    x3y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.unary('-', rt.i(1)), 'int'))
    x3y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(0), 'int'))
    x3y2 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(1), 'int'))
    x3y3 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(2), rt.i(2), 'int'))
    y0 = catmullRom4__float_float_float_float_float.call(x0y0, x1y0, x2y0, x3y0, rt.swizzle(f, 'x'))
    y1 = catmullRom4__float_float_float_float_float.call(x0y1, x1y1, x2y1, x3y1, rt.swizzle(f, 'x'))
    y2 = catmullRom4__float_float_float_float_float.call(x0y2, x1y2, x2y2, x3y2, rt.swizzle(f, 'x'))
    y3 = catmullRom4__float_float_float_float_float.call(x0y3, x1y3, x2y3, x3y3, rt.swizzle(f, 'x'))
    return rt.component_wise('clamp', catmullRom4__float_float_float_float_float.call(y0, y1, y2, y3, rt.swizzle(f, 'y')), rt.f(0), rt.f(1))
  end
  value__vec2_float_float_float = lambda do |st, xFreq, yFreq, s|
    st = rt.copy(st, 'float')
    a = nil; b = nil; f = nil; scaledTime10 = nil; scaledTime11 = nil; uv = nil; x0y0 = nil; x0y1 = nil; x1y0 = nil; x1y1 = nil
    a = rt.f(0.0)
    b = rt.f(0.0)
    f = rt.construct(2, 0.0)
    scaledTime10 = rt.f(0.0)
    scaledTime11 = rt.f(0.0)
    uv = rt.construct(2, 0.0)
    x0y0 = rt.f(0.0)
    x0y1 = rt.f(0.0)
    x1y0 = rt.f(0.0)
    x1y1 = rt.f(0.0)
    if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(0)))
      return constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
    else
      if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(3)))
        return catmullRom3x3Value__vec2_float_float_float.call(st, xFreq, yFreq, s)
      else
        if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(4)))
          return catmullRom4x4Value__vec2_float_float_float.call(st, xFreq, yFreq, s)
        else
          if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(5)))
            return quadratic3x3Value__vec2_float_float_float.call(st, xFreq, yFreq, s)
          else
            if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(6)))
              return bicubicValue__vec2_float_float_float.call(st, xFreq, yFreq, s)
            else
              if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(10)))
                scaledTime10 = rt.binary('*', rt.binary('*', simplexValue__vec2_float_float_float_float.call(st, xFreq, yFreq, rt.binary('+', s, rt.f(50), 1, 'float'), _u_time), _u_speed, 1, 'float'), rt.f(0.0025000000000000001), 1, 'float')
                return simplexValue__vec2_float_float_float_float.call(st, xFreq, yFreq, s, scaledTime10)
              else
                if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(11)))
                  scaledTime11 = rt.binary('*', rt.binary('*', sineNoise__vec2_float_float_float_float.call(st, xFreq, yFreq, rt.binary('+', s, rt.f(50), 1, 'float'), _u_time), _u_speed, 1, 'float'), rt.f(0.0025000000000000001), 1, 'float')
                  return sineNoise__vec2_float_float_float_float.call(st, xFreq, yFreq, s, scaledTime11)
                else
                  uv = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(st, 'x'), xFreq, 1, 'float'), rt.binary('*', rt.swizzle(st, 'y'), yFreq, 1, 'float')))
                  f = rt.construct(2, rt.component_wise('fract', uv))
                  x0y0 = constant__vec2_float_float_float.call(st, xFreq, yFreq, s)
                  x1y0 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(0), 'int'))
                  x0y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(0), rt.i(1), 'int'))
                  x1y1 = constantOffset__vec2_float_float_float_ivec2.call(st, xFreq, yFreq, s, rt.construct(2, rt.i(1), rt.i(1), 'int'))
                  a = blendLinearOrCosine__float_float_float_int.call(x0y0, x1y0, rt.swizzle(f, 'x'), _u__NOISE_TYPE)
                  b = blendLinearOrCosine__float_float_float_int.call(x0y1, x1y1, rt.swizzle(f, 'x'), _u__NOISE_TYPE)
                  return rt.component_wise('clamp', blendLinearOrCosine__float_float_float_int.call(a, b, rt.swizzle(f, 'y'), _u__NOISE_TYPE), rt.f(0), rt.f(1))
                end
              end
            end
          end
        end
      end
    end
  end
  noise__vec2_float = lambda do |st, s|
    st = rt.copy(st, 'float')
    color = nil; freq = nil
    freq = rt.f(1)
    if rt.bool(rt.binary('==', _u__NOISE_TYPE, rt.i(10)))
      freq = map__float_float_float_float_float.call(_u_noiseScale, rt.f(1), rt.f(100), rt.f(1), rt.f(0.5))
    else
      if rt.bool(_u_wrap)
        freq = rt.component_wise('floor', map__float_float_float_float_float.call(_u_noiseScale, rt.f(1), rt.f(100), rt.f(6), rt.f(2)))
      else
        freq = map__float_float_float_float_float.call(_u_noiseScale, rt.f(1), rt.f(100), rt.f(6), rt.f(1))
      end
    end
    color = rt.construct(3, rt.construct(3, value__vec2_float_float_float.call(st, freq, freq, rt.binary('+', rt.f(0), s, 1, 'float')), value__vec2_float_float_float.call(st, freq, freq, rt.binary('+', rt.f(10), s, 1, 'float')), value__vec2_float_float_float.call(st, freq, freq, rt.binary('+', rt.f(20), s, 1, 'float'))))
    color = rt.assign_swizzle(color, 'r', rt.binary('*', rt.binary('*', rt.swizzle(color, 'r'), _u_hueRange, 1, 'float'), rt.f(0.01), 1, 'float'))
    color = rt.assign_swizzle(color, 'r', rt.binary('+', rt.swizzle(color, 'r'), rt.binary('-', rt.f(1), rt.binary('/', _u_hueRotation, rt.f(360), 1, 'float'), 1, 'float'), 1, 'float'))
    color = rt.assign_swizzle(color, 'g', rt.binary('*', rt.swizzle(color, 'g'), rt.f(0.33300000000000002), 1, 'float'))
    color = rt.assign_swizzle(color, 'b', rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', rt.swizzle(color, 'b'), rt.f(2), 1, 'float'), rt.f(1), 1, 'float')), 1, 'float'))
    color.replace((hsv2rgb__vec3.call(color)).map { |c| rt.f32(c) })
    return color
  end
  main__void = lambda do
    color = nil; globalCoord = nil; left = nil; leftColor = nil; right = nil; rightColor = nil; st = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    color = rt.construct(4, rt.construct(4, rt.f(0), rt.f(0), rt.f(1), rt.f(1)))
    st = rt.construct(2, rt.binary('/', globalCoord, rt.swizzle(_u_fullResolution, 'y'), 2, 'float'))
    st.replace((rt.binary('-', st, rt.construct(2, rt.binary('*', rt.binary('/', rt.swizzle(_u_fullResolution, 'x'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), rt.f(0.5), 1, 'float'), rt.f(0.5)), 2, 'float')).map { |c| rt.f32(c) })
    leftColor = rt.construct(3, noise__vec2_float.call(st, rt.construct(1, _u_seed)))
    rightColor = rt.construct(3, noise__vec2_float.call(st, rt.binary('+', rt.construct(1, _u_seed), rt.f(10), 1, 'float')))
    left = rt.construct(3, rt.component_wise('min', rt.binary('/', rt.binary('*', leftColor, rightColor, 3, 'float'), rt.binary('-', rt.f(1), rt.binary('*', rightColor, leftColor, 3, 'float'), 3, 'float'), 3, 'float'), rt.construct(3, rt.f(1))))
    right = rt.construct(3, rt.component_wise('min', rt.binary('/', rt.binary('*', rightColor, leftColor, 3, 'float'), rt.binary('-', rt.f(1), rt.binary('*', leftColor, rightColor, 3, 'float'), 3, 'float'), 3, 'float'), rt.construct(3, rt.f(1))))
    color = rt.assign_swizzle(color, 'rgb', brightnessContrast__vec3.call(rt.component_wise('mix', left, right, rt.f(0.5))))
    color = rt.assign_swizzle(color, 'a', rt.f(1))
    g['fragColor'].replace((color).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
