# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hsv2rgb__vec3 = rgb2hsv__vec3 = desaturate__vec3 = blend__vec3_vec3 = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_tex = ctx.texture_binding('tex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_inputColor = u.key?('inputColor') ? u['inputColor'] : rt.construct(3, 0.0)
  _u_blendMode = u.key?('blendMode') ? u['blendMode'] : 0
  _u_range = u.key?('range') ? u['range'] : rt.f(0.0)
  _u_mixAmt = u.key?('mixAmt') ? u['mixAmt'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  hsv2rgb__vec3 = lambda do |hsv|
    hsv = rt.copy(hsv, 'float')
    c = nil; h = nil; m = nil; rgb = nil; s = nil; v = nil; x = nil
    h = rt.component_wise('fract', rt.swizzle(hsv, 'x'))
    s = rt.swizzle(hsv, 'y')
    v = rt.swizzle(hsv, 'z')
    c = rt.binary('*', v, s, 1, 'float')
    x = rt.binary('*', c, rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.component_wise('mod', rt.binary('*', h, rt.f(6), 1, 'float'), rt.f(2)), rt.f(1), 1, 'float')), 1, 'float'), 1, 'float')
    m = rt.binary('-', v, c, 1, 'float')
    rgb = rt.construct(3, 0.0)
    if rt.bool((rt.bool(rt.binary('<=', rt.f(0), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(1), rt.f(6), 1, 'float'))) ? 1 : 0))
      rgb.replace((rt.construct(3, c, x, rt.f(0))).map { |c| rt.f32(c) })
    else
      if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(1), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(2), rt.f(6), 1, 'float'))) ? 1 : 0))
        rgb.replace((rt.construct(3, x, c, rt.f(0))).map { |c| rt.f32(c) })
      else
        if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(2), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(3), rt.f(6), 1, 'float'))) ? 1 : 0))
          rgb.replace((rt.construct(3, rt.f(0), c, x)).map { |c| rt.f32(c) })
        else
          if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(3), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(4), rt.f(6), 1, 'float'))) ? 1 : 0))
            rgb.replace((rt.construct(3, rt.f(0), x, c)).map { |c| rt.f32(c) })
          else
            if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(4), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(5), rt.f(6), 1, 'float'))) ? 1 : 0))
              rgb.replace((rt.construct(3, x, rt.f(0), c)).map { |c| rt.f32(c) })
            else
              if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(5), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.f(1))) ? 1 : 0))
                rgb.replace((rt.construct(3, c, rt.f(0), x)).map { |c| rt.f32(c) })
              else
                rgb.replace((rt.construct(3, rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
              end
            end
          end
        end
      end
    end
    return rt.binary('+', rgb, rt.construct(3, m, m, m), 3, 'float')
  end
  rgb2hsv__vec3 = lambda do |rgb|
    rgb = rt.copy(rgb, 'float')
    _g = nil; b = nil; delta = nil; h = nil; max = nil; min = nil; r = nil; s = nil; v = nil
    r = rt.swizzle(rgb, 'r')
    _g = rt.swizzle(rgb, 'g')
    b = rt.swizzle(rgb, 'b')
    max = rt.component_wise('max', r, rt.component_wise('max', _g, b))
    min = rt.component_wise('min', r, rt.component_wise('min', _g, b))
    delta = rt.binary('-', max, min, 1, 'float')
    h = rt.f(0)
    if rt.bool(rt.binary('!=', delta, rt.f(0)))
      if rt.bool(rt.binary('==', max, r))
        h = rt.binary('/', rt.component_wise('mod', rt.binary('/', rt.binary('-', _g, b, 1, 'float'), delta, 1, 'float'), rt.f(6)), rt.f(6), 1, 'float')
      else
        if rt.bool(rt.binary('==', max, _g))
          h = rt.binary('/', rt.binary('+', rt.binary('/', rt.binary('-', b, r, 1, 'float'), delta, 1, 'float'), rt.f(2), 1, 'float'), rt.f(6), 1, 'float')
        else
          if rt.bool(rt.binary('==', max, b))
            h = rt.binary('/', rt.binary('+', rt.binary('/', rt.binary('-', r, _g, 1, 'float'), delta, 1, 'float'), rt.f(4), 1, 'float'), rt.f(6), 1, 'float')
          end
        end
      end
    end
    s = (rt.bool(rt.binary('==', max, rt.f(0))) ? (rt.f(0)) : (rt.binary('/', delta, max, 1, 'float')))
    v = max
    return rt.construct(3, h, s, v)
  end
  desaturate__vec3 = lambda do |color|
    color = rt.copy(color, 'float')
    c = nil
    c = rt.construct(3, rgb2hsv__vec3.call(color))
    c = rt.assign_swizzle(c, 'g', rt.f(0))
    return hsv2rgb__vec3.call(c)
  end
  blend__vec3_vec3 = lambda do |color1, color2|
    color1 = rt.copy(color1, 'float')
    color2 = rt.copy(color2, 'float')
    c = nil; c1 = nil; c2 = nil; color = nil; cut = nil
    color = rt.construct(3, rt.construct(3, rt.f(0)))
    cut = rt.binary('*', _u_range, rt.f(0.01), 1, 'float')
    c = rt.construct(3, 0.0)
    c1 = rt.construct(3, 0.0)
    c2 = rt.construct(3, 0.0)
    if rt.bool(rt.binary('==', _u_blendMode, rt.i(0)))
      if rt.bool(rt.binary('>', rt.distance(_u_inputColor, color1), rt.binary('*', _u_range, rt.f(0.01), 1, 'float')))
        color1.replace((desaturate__vec3.call(color1)).map { |c| rt.f32(c) })
      end
      if rt.bool(rt.binary('>', rt.distance(_u_inputColor, color2), rt.binary('*', _u_range, rt.f(0.01), 1, 'float')))
        color2.replace((desaturate__vec3.call(color2)).map { |c| rt.f32(c) })
      end
      color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
    else
      if rt.bool(rt.binary('==', _u_blendMode, rt.i(1)))
        if rt.bool(rt.binary('<=', rt.distance(_u_inputColor, color1), rt.binary('*', _u_range, rt.f(0.01), 1, 'float')))
          color.replace((color2).map { |c| rt.f32(c) })
        else
          color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
        end
      else
        if rt.bool(rt.binary('==', _u_blendMode, rt.i(2)))
          if rt.bool(rt.binary('<=', rt.distance(_u_inputColor, color2), rt.binary('*', _u_range, rt.f(0.01), 1, 'float')))
            color.replace((color1).map { |c| rt.f32(c) })
          else
            color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
          end
        else
          if rt.bool(rt.binary('==', _u_blendMode, rt.i(3)))
            c = rt.binary('-', rt.f(1), rt.component_wise('step', cut, rt.swizzle(desaturate__vec3.call(color2), 'r')), 1, 'float')
            color2.replace((rt.component_wise('mix', color1, rt.construct(3, rt.f(0)), c)).map { |c| rt.f32(c) })
            color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
          else
            if rt.bool(rt.binary('==', _u_blendMode, rt.i(4)))
              c = rt.construct(3, rt.binary('-', rt.f(1), rt.component_wise('step', cut, color2), 3, 'float'))
              color2.replace((rt.component_wise('mix', color1, rt.construct(3, rt.f(0)), c)).map { |c| rt.f32(c) })
              color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
            else
              if rt.bool(rt.binary('==', _u_blendMode, rt.i(5)))
                c = rt.swizzle(rgb2hsv__vec3.call(color2), 'r')
                color2.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
              else
                if rt.bool(rt.binary('==', _u_blendMode, rt.i(6)))
                  c = rt.swizzle(rgb2hsv__vec3.call(color2), 'g')
                  color2.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                  color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                else
                  if rt.bool(rt.binary('==', _u_blendMode, rt.i(7)))
                    c = rt.swizzle(rgb2hsv__vec3.call(color2), 'b')
                    color2.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                    color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                  else
                    if rt.bool(rt.binary('==', _u_blendMode, rt.i(8)))
                      c = rt.binary('-', rt.f(1), rt.component_wise('step', cut, rt.swizzle(desaturate__vec3.call(color1), 'r')), 1, 'float')
                      color1.replace((rt.component_wise('mix', color2, rt.construct(3, rt.f(0)), c)).map { |c| rt.f32(c) })
                      color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                    else
                      if rt.bool(rt.binary('==', _u_blendMode, rt.i(9)))
                        c = rt.construct(3, rt.binary('-', rt.f(1), rt.component_wise('step', cut, color1), 3, 'float'))
                        color1.replace((rt.component_wise('mix', color2, rt.construct(3, rt.f(0)), c)).map { |c| rt.f32(c) })
                        color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                      else
                        if rt.bool(rt.binary('==', _u_blendMode, rt.i(10)))
                          c = rt.swizzle(rgb2hsv__vec3.call(color1), 'r')
                          color1.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                          color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                        else
                          if rt.bool(rt.binary('==', _u_blendMode, rt.i(11)))
                            c = rt.swizzle(rgb2hsv__vec3.call(color1), 'g')
                            color1.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                            color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                          else
                            if rt.bool(rt.binary('==', _u_blendMode, rt.i(12)))
                              c = rt.swizzle(rgb2hsv__vec3.call(color1), 'b')
                              color1.replace((rt.component_wise('mix', color1, color2, rt.binary('*', c, cut, 1, 'float'))).map { |c| rt.f32(c) })
                              color.replace((rt.component_wise('mix', color2, color1, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                            else
                              if rt.bool(rt.binary('==', _u_blendMode, rt.i(13)))
                                color2.replace((rt.component_wise('mix', color1, color2, cut)).map { |c| rt.f32(c) })
                                color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                              else
                                if rt.bool(rt.binary('==', _u_blendMode, rt.i(14)))
                                  c = rt.construct(3, rt.component_wise('step', cut, rt.component_wise('mix', color1, color2, rt.f(0.5))))
                                  color2.replace((rt.component_wise('mix', color1, color2, c)).map { |c| rt.f32(c) })
                                  color.replace((rt.component_wise('mix', color1, color2, rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                                else
                                  if rt.bool(rt.binary('==', _u_blendMode, rt.i(15)))
                                    c1 = rt.construct(3, rt.component_wise('smoothstep', color1, rt.construct(3, cut), color2))
                                    c2 = rt.construct(3, rt.component_wise('smoothstep', color2, rt.construct(3, cut), color1))
                                    color.replace((rt.component_wise('mix', rt.swizzle(c1, 'brg'), rt.swizzle(c2, 'gbr'), rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float'))).map { |c| rt.f32(c) })
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    return color
  end
  main__void = lambda do
    color = nil; color1 = nil; color2 = nil; globalCoord = nil; st = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    color = rt.construct(4, rt.construct(4, rt.f(0), rt.f(0), rt.f(1), rt.f(1)))
    st = rt.construct(2, rt.binary('/', globalCoord, _u_fullResolution, 2, 'float'))
    color1 = rt.construct(4, rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')))
    color2 = rt.construct(4, rt.texture(_u_tex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_tex)), 2, 'float')))
    color = rt.assign_swizzle(color, 'rgb', blend__vec3_vec3.call(rt.swizzle(color1, 'rgb'), rt.swizzle(color2, 'rgb')))
    color = rt.assign_swizzle(color, 'a', rt.component_wise('mix', rt.swizzle(color1, 'a'), rt.swizzle(color2, 'a'), rt.binary('*', _u_mixAmt, rt.f(0.01), 1, 'float')))
    g['fragColor'].replace((color).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
