# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  map__float_float_float_float_float = pcg__uvec3 = prng__vec3 = hsv2rgb__vec3 = rgb2hsv__vec3 = linearToSrgb__vec3 = oklab_from_linear_srgb__vec3 = linear_srgb_from_oklab__vec3 = pal__float = luminance__vec3 = rotate2D__vec2_float = polarShape__vec2_int = shapeDistance__vec2_vec2_int_float = wrapEdges__vec2_float = smin__float_float_float = cells__vec2_float_float_int = main__void = nil
  _retc = nil
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_renderScale = u.key?('renderScale') ? u['renderScale'] : rt.f(0.0)
  _u_shape = u.key?('shape') ? u['shape'] : 0
  _u_scale = u.key?('scale') ? u['scale'] : rt.f(0.0)
  _u_cellScale = u.key?('cellScale') ? u['cellScale'] : rt.f(0.0)
  _u_cellSmooth = u.key?('cellSmooth') ? u['cellSmooth'] : rt.f(0.0)
  _u_variation = u.key?('variation') ? u['variation'] : rt.f(0.0)
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_paletteMode = u.key?('paletteMode') ? u['paletteMode'] : 0
  _u_paletteOffset = u.key?('paletteOffset') ? u['paletteOffset'] : rt.construct(3, 0.0)
  _u_paletteAmp = u.key?('paletteAmp') ? u['paletteAmp'] : rt.construct(3, 0.0)
  _u_paletteFreq = u.key?('paletteFreq') ? u['paletteFreq'] : rt.construct(3, 0.0)
  _u_palettePhase = u.key?('palettePhase') ? u['palettePhase'] : rt.construct(3, 0.0)
  _u_colorMode = u.key?('colorMode') ? u['colorMode'] : 0
  _u_cyclePalette = u.key?('cyclePalette') ? u['cyclePalette'] : 0
  _u_rotatePalette = u.key?('rotatePalette') ? u['rotatePalette'] : rt.f(0.0)
  _u_repeatPalette = u.key?('repeatPalette') ? u['repeatPalette'] : rt.f(0.0)
  _u_texInfluence = u.key?('texInfluence') ? u['texInfluence'] : 0
  _u_texIntensity = u.key?('texIntensity') ? u['texIntensity'] : rt.f(0.0)
  _u_tex = ctx.texture_binding('tex')
  g['fragColor'] = rt.construct(4, 0.0)
  g['fwdA'] = rt.construct(9, rt.f(1), rt.f(1), rt.f(1), rt.f(0.39633777739999998), rt.unary('-', rt.f(0.1055613458)), rt.unary('-', rt.f(0.089484177499999998)), rt.f(0.21580375730000001), rt.unary('-', rt.f(0.063854172799999998)), rt.unary('-', rt.f(1.291485548)))
  g['fwdB'] = rt.construct(9, rt.f(4.0767245292999998), rt.unary('-', rt.f(1.2681437731)), rt.unary('-', rt.f(0.0041119885000000002)), rt.unary('-', rt.f(3.3072168827000001)), rt.f(2.6093323230999999), rt.unary('-', rt.f(0.70347630979999998)), rt.f(0.2307590544), rt.unary('-', rt.f(0.34113442900000002)), rt.f(1.7068625689000001))
  g['invB'] = rt.construct(9, rt.f(0.41216561200000001), rt.f(0.21185910699999999), rt.f(0.088309794699999999), rt.f(0.53627520799999995), rt.f(0.68071895839999996), rt.f(0.28184741740000002), rt.f(0.051457565300000001), rt.f(0.107406579), rt.f(0.63026136160000001))
  g['invA'] = rt.construct(9, rt.f(0.2104542553), rt.f(1.9779984951), rt.f(0.025904037099999999), rt.f(0.79361778500000002), rt.unary('-', rt.f(2.4285922050000002)), rt.f(0.7827717662), rt.unary('-', rt.f(0.0040720467999999996)), rt.f(0.45059370989999997), rt.unary('-', rt.f(0.80867576600000002)))
  map__float_float_float_float_float = lambda do |value, inMin, inMax, outMin, outMax|
    return rt.binary('+', outMin, rt.binary('/', rt.binary('*', rt.binary('-', outMax, outMin, 1, 'float'), rt.binary('-', value, inMin, 1, 'float'), 1, 'float'), rt.binary('-', inMax, inMin, 1, 'float'), 1, 'float'), 1, 'float')
  end
  pcg__uvec3 = lambda do |v|
    v = rt.copy(v, 'uint')
    v.replace(rt.binary('+', rt.binary('*', v, rt.construct(1, rt.i(1664525), 'uint'), 3, 'uint'), rt.construct(1, rt.i(1013904223), 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    v.replace(rt.binary('^', v, rt.binary('>>', v, rt.construct(1, rt.i(16), 'uint'), 3, 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    return v
  end
  prng__vec3 = lambda do |p|
    p = rt.copy(p, 'float')
    p = rt.assign_swizzle(p, 'x', (rt.bool(rt.binary('>=', rt.swizzle(p, 'x'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'x'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'x')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    p = rt.assign_swizzle(p, 'y', (rt.bool(rt.binary('>=', rt.swizzle(p, 'y'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'y'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'y')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    p = rt.assign_swizzle(p, 'z', (rt.bool(rt.binary('>=', rt.swizzle(p, 'z'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'z'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'z')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))))
    return rt.binary('/', rt.construct(3, pcg__uvec3.call(rt.construct(3, p, 'uint'))), rt.construct(1, rt.construct(1, rt.i(4294967295), 'uint')), 3, 'float')
  end
  hsv2rgb__vec3 = lambda do |hsv|
    hsv = rt.copy(hsv, 'float')
    c = nil; h = nil; m = nil; rgb = nil; s = nil; v = nil; x = nil
    h = rt.component_wise('fract', rt.swizzle(hsv, 'x'))
    s = rt.swizzle(hsv, 'y')
    v = rt.swizzle(hsv, 'z')
    c = rt.binary('*', v, s, 1, 'float')
    x = rt.binary('*', c, rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.component_wise('mod', rt.binary('*', h, rt.f(6), 1, 'float'), rt.f(2)), rt.f(1), 1, 'float')), 1, 'float'), 1, 'float')
    m = rt.binary('-', v, c, 1, 'float')
    rgb = rt.construct(3, 0.0)
    if rt.bool((rt.bool(rt.binary('<=', rt.f(0), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(1), rt.f(6), 1, 'float'))) ? 1 : 0))
      rgb.replace((rt.construct(3, c, x, rt.f(0))).map { |c| rt.f32(c) })
    else
      if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(1), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(2), rt.f(6), 1, 'float'))) ? 1 : 0))
        rgb.replace((rt.construct(3, x, c, rt.f(0))).map { |c| rt.f32(c) })
      else
        if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(2), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(3), rt.f(6), 1, 'float'))) ? 1 : 0))
          rgb.replace((rt.construct(3, rt.f(0), c, x)).map { |c| rt.f32(c) })
        else
          if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(3), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(4), rt.f(6), 1, 'float'))) ? 1 : 0))
            rgb.replace((rt.construct(3, rt.f(0), x, c)).map { |c| rt.f32(c) })
          else
            if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(4), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.binary('/', rt.f(5), rt.f(6), 1, 'float'))) ? 1 : 0))
              rgb.replace((rt.construct(3, x, rt.f(0), c)).map { |c| rt.f32(c) })
            else
              if rt.bool((rt.bool(rt.binary('<=', rt.binary('/', rt.f(5), rt.f(6), 1, 'float'), h)) && rt.bool(rt.binary('<', h, rt.f(1))) ? 1 : 0))
                rgb.replace((rt.construct(3, c, rt.f(0), x)).map { |c| rt.f32(c) })
              else
                rgb.replace((rt.construct(3, rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
              end
            end
          end
        end
      end
    end
    return rt.binary('+', rgb, rt.construct(3, m, m, m), 3, 'float')
  end
  rgb2hsv__vec3 = lambda do |rgb|
    rgb = rt.copy(rgb, 'float')
    _g = nil; b = nil; delta = nil; h = nil; max = nil; min = nil; r = nil; s = nil; v = nil
    r = rt.swizzle(rgb, 'r')
    _g = rt.swizzle(rgb, 'g')
    b = rt.swizzle(rgb, 'b')
    max = rt.component_wise('max', r, rt.component_wise('max', _g, b))
    min = rt.component_wise('min', r, rt.component_wise('min', _g, b))
    delta = rt.binary('-', max, min, 1, 'float')
    h = rt.f(0)
    if rt.bool(rt.binary('!=', delta, rt.f(0)))
      if rt.bool(rt.binary('==', max, r))
        h = rt.binary('/', rt.component_wise('mod', rt.binary('/', rt.binary('-', _g, b, 1, 'float'), delta, 1, 'float'), rt.f(6)), rt.f(6), 1, 'float')
      else
        if rt.bool(rt.binary('==', max, _g))
          h = rt.binary('/', rt.binary('+', rt.binary('/', rt.binary('-', b, r, 1, 'float'), delta, 1, 'float'), rt.f(2), 1, 'float'), rt.f(6), 1, 'float')
        else
          if rt.bool(rt.binary('==', max, b))
            h = rt.binary('/', rt.binary('+', rt.binary('/', rt.binary('-', r, _g, 1, 'float'), delta, 1, 'float'), rt.f(4), 1, 'float'), rt.f(6), 1, 'float')
          end
        end
      end
    end
    s = (rt.bool(rt.binary('==', max, rt.f(0))) ? (rt.f(0)) : (rt.binary('/', delta, max, 1, 'float')))
    v = max
    return rt.construct(3, h, s, v)
  end
  linearToSrgb__vec3 = lambda do |linear|
    linear = rt.copy(linear, 'float')
    _for0_first = nil; i = nil; srgb = nil
    srgb = rt.construct(3, 0.0)
    i = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', i, rt.i(3)))
        break
      end
      if rt.bool(rt.binary('<=', linear[(i).to_i], rt.f(0.0031308)))
        srgb[(i).to_i] = rt.binary('*', linear[(i).to_i], rt.f(12.92), 1, 'float')
      else
        srgb[(i).to_i] = rt.binary('-', rt.binary('*', rt.f(1.0549999999999999), rt.component_wise('pow', linear[(i).to_i], rt.binary('/', rt.f(1), rt.f(2.3999999999999999), 1, 'float')), 1, 'float'), rt.f(0.055), 1, 'float')
      end
    end
    return srgb
  end
  oklab_from_linear_srgb__vec3 = lambda do |c|
    c = rt.copy(c, 'float')
    lms = nil
    lms = rt.matrix_mult(g['invB'], c, 3)
    return rt.matrix_mult(g['invA'], rt.binary('*', rt.component_wise('sign', lms), rt.component_wise('pow', rt.component_wise('abs', lms), rt.construct(3, rt.f(0.33333333333330001))), 3, 'float'), 3)
  end
  linear_srgb_from_oklab__vec3 = lambda do |c|
    c = rt.copy(c, 'float')
    lms = nil
    lms = rt.matrix_mult(g['fwdA'], c, 3)
    return rt.matrix_mult(g['fwdB'], rt.binary('*', rt.binary('*', lms, lms, 3, 'float'), lms, 3, 'float'), 3)
  end
  pal__float = lambda do |_t|
    a = nil; b = nil; c = nil; color = nil; d = nil
    a = _u_paletteOffset
    b = _u_paletteAmp
    c = _u_paletteFreq
    d = _u_palettePhase
    _t = rt.binary('+', rt.binary('*', _t, _u_repeatPalette, 1, 'float'), rt.binary('*', _u_rotatePalette, rt.f(0.01), 1, 'float'), 1, 'float')
    color = rt.binary('+', a, rt.binary('*', b, rt.component_wise('cos', rt.binary('*', rt.f(6.2831799999999998), rt.binary('+', rt.binary('*', c, _t, 3, 'float'), d, 3, 'float'), 3, 'float')), 3, 'float'), 3, 'float')
    if rt.bool(rt.binary('==', _u_paletteMode, rt.i(1)))
      color.replace((hsv2rgb__vec3.call(color)).map { |c| rt.f32(c) })
    else
      if rt.bool(rt.binary('==', _u_paletteMode, rt.i(2)))
        color = rt.assign_swizzle(color, 'g', rt.binary('+', rt.binary('*', rt.swizzle(color, 'g'), rt.unary('-', rt.f(0.50900000000000001)), 1, 'float'), rt.f(0.27600000000000002), 1, 'float'))
        color = rt.assign_swizzle(color, 'b', rt.binary('+', rt.binary('*', rt.swizzle(color, 'b'), rt.unary('-', rt.f(0.50900000000000001)), 1, 'float'), rt.f(0.19800000000000001), 1, 'float'))
        color.replace((linear_srgb_from_oklab__vec3.call(color)).map { |c| rt.f32(c) })
        color.replace((linearToSrgb__vec3.call(color)).map { |c| rt.f32(c) })
      end
    end
    return color
  end
  luminance__vec3 = lambda do |color|
    color = rt.copy(color, 'float')
    return rt.binary('+', rt.binary('+', rt.binary('*', rt.f(0.21260000000000001), rt.swizzle(color, 'r'), 1, 'float'), rt.binary('*', rt.f(0.71519999999999995), rt.swizzle(color, 'g'), 1, 'float'), 1, 'float'), rt.binary('*', rt.f(0.0722), rt.swizzle(color, 'b'), 1, 'float'), 1, 'float')
  end
  rotate2D__vec2_float = lambda do |st, rot|
    st = rt.copy(st, 'float')
    angle = nil
    rot = map__float_float_float_float_float.call(rot, rt.f(0), rt.f(360), rt.f(0), rt.f(2))
    angle = rt.binary('*', rot, rt.f(3.1415926535900001), 1, 'float')
    st.replace((rt.binary('-', st, rt.construct(2, rt.binary('/', rt.binary('*', rt.f(0.5), rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), rt.f(0.5)), 2, 'float')).map { |c| rt.f32(c) })
    st.replace((rt.matrix_mult(rt.construct(4, rt.component_wise('cos', angle), rt.unary('-', rt.component_wise('sin', angle)), rt.component_wise('sin', angle), rt.component_wise('cos', angle)), st, 2)).map { |c| rt.f32(c) })
    st.replace((rt.binary('+', st, rt.construct(2, rt.binary('/', rt.binary('*', rt.f(0.5), rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), rt.f(0.5)), 2, 'float')).map { |c| rt.f32(c) })
    return st
  end
  polarShape__vec2_int = lambda do |st, sides|
    st = rt.copy(st, 'float')
    a = nil; r = nil
    a = rt.binary('+', rt.component_wise('atan', rt.swizzle(st, 'x'), rt.swizzle(st, 'y')), rt.f(3.1415926535900001), 1, 'float')
    r = rt.binary('/', rt.f(6.2831853071800001), rt.construct(1, sides), 1, 'float')
    return rt.binary('*', rt.component_wise('cos', rt.binary('-', rt.binary('*', rt.component_wise('floor', rt.binary('+', rt.f(0.5), rt.binary('/', a, r, 1, 'float'), 1, 'float')), r, 1, 'float'), a, 1, 'float')), rt.length(st), 1, 'float')
  end
  shapeDistance__vec2_vec2_int_float = lambda do |st, offset, type, scale|
    st = rt.copy(st, 'float')
    offset = rt.copy(offset, 'float')
    d = nil
    st.replace((rt.binary('+', st, offset, 2, 'float')).map { |c| rt.f32(c) })
    d = rt.f(1)
    if rt.bool(rt.binary('==', type, rt.i(0)))
      d = rt.length(rt.binary('*', st, rt.f(1.2), 2, 'float'))
    else
      if rt.bool(rt.binary('==', type, rt.i(2)))
        d = polarShape__vec2_int.call(rt.binary('*', st, rt.f(1.2), 2, 'float'), rt.i(6))
      else
        if rt.bool(rt.binary('==', type, rt.i(3)))
          d = polarShape__vec2_int.call(rt.binary('*', st, rt.f(1.2), 2, 'float'), rt.i(8))
        else
          if rt.bool(rt.binary('==', type, rt.i(4)))
            d = polarShape__vec2_int.call(rt.binary('*', st, rt.f(1.5), 2, 'float'), rt.i(4))
          else
            if rt.bool(rt.binary('==', type, rt.i(6)))
              st = rt.assign_swizzle(st, 'y', rt.binary('+', rt.swizzle(st, 'y'), rt.f(0.050000000000000003), 1, 'float'))
              d = polarShape__vec2_int.call(rt.binary('*', st, rt.f(1.5), 2, 'float'), rt.i(3))
            end
          end
        end
      end
    end
    return rt.binary('*', d, scale, 1, 'float')
  end
  wrapEdges__vec2_float = lambda do |st, freq|
    st = rt.copy(st, 'float')
    if rt.bool(rt.binary('<', rt.swizzle(st, 'x'), rt.f(0)))
      st = rt.assign_swizzle(st, 'x', rt.binary('-', freq, rt.f(1), 1, 'float'))
    end
    if rt.bool(rt.binary('>', rt.swizzle(st, 'x'), rt.binary('/', rt.binary('*', freq, rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')))
      st = rt.assign_swizzle(st, 'x', rt.f(0))
    end
    if rt.bool(rt.binary('<', rt.swizzle(st, 'y'), rt.f(0)))
      st = rt.assign_swizzle(st, 'y', rt.binary('-', freq, rt.f(1), 1, 'float'))
    end
    if rt.bool(rt.binary('>', rt.swizzle(st, 'y'), freq))
      st = rt.assign_swizzle(st, 'y', rt.f(0))
    end
    return st
  end
  smin__float_float_float = lambda do |a, b, k|
    h = nil
    if rt.bool(rt.binary('==', k, rt.f(0)))
      return rt.component_wise('min', a, b)
    end
    h = rt.binary('/', rt.component_wise('max', rt.binary('-', k, rt.component_wise('abs', rt.binary('-', a, b, 1, 'float')), 1, 'float'), rt.f(0)), k, 1, 'float')
    return rt.binary('-', rt.component_wise('min', a, b), rt.binary('*', rt.binary('*', rt.binary('*', h, h, 1, 'float'), k, 1, 'float'), rt.binary('/', rt.f(1), rt.f(4), 1, 'float'), 1, 'float'), 1, 'float')
  end
  cells__vec2_float_float_int = lambda do |st, freq, cellSize, sides|
    st = rt.copy(st, 'float')
    _for1_first = nil; _for2_first = nil; d = nil; diff = nil; dist = nil; f = nil; i = nil; n = nil; point = nil; r1 = nil; r2 = nil; spd = nil; wrap = nil; x = nil; y = nil
    st.replace((rt.binary('-', st, rt.construct(2, rt.binary('/', rt.binary('*', rt.f(0.5), rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), rt.f(0.5)), 2, 'float')).map { |c| rt.f32(c) })
    st.replace((rt.binary('*', st, freq, 2, 'float')).map { |c| rt.f32(c) })
    st.replace((rt.binary('+', st, rt.construct(2, rt.binary('/', rt.binary('*', rt.f(0.5), rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), rt.f(0.5)), 2, 'float')).map { |c| rt.f32(c) })
    st.replace((rt.binary('+', st, rt.swizzle(prng__vec3.call(rt.construct(3, rt.construct(1, _u_seed))), 'xy'), 2, 'float')).map { |c| rt.f32(c) })
    i = rt.component_wise('floor', st)
    f = rt.component_wise('fract', st)
    d = rt.f(1)
    y = rt.unary('-', rt.i(2))
    _for1_first = true
    (0..1048575).each do |_for1|
      unless _for1_first
        y = rt.binary('+', y, rt.i(1), 1, 'int')
      end
      _for1_first = false
      unless rt.bool(rt.binary('<=', y, rt.i(2)))
        break
      end
      x = rt.unary('-', rt.i(2))
      _for2_first = true
      (0..1048575).each do |_for2|
        unless _for2_first
          x = rt.binary('+', x, rt.i(1), 1, 'int')
        end
        _for2_first = false
        unless rt.bool(rt.binary('<=', x, rt.i(2)))
          break
        end
        n = rt.construct(2, rt.construct(1, x), rt.construct(1, y))
        wrap = rt.binary('+', i, n, 2, 'float')
        point = rt.swizzle(prng__vec3.call(rt.construct(3, wrap, rt.construct(1, _u_seed))), 'xy')
        r1 = rt.binary('-', rt.binary('*', prng__vec3.call(rt.construct(3, rt.construct(1, _u_seed), wrap)), rt.f(0.5), 3, 'float'), rt.f(0.25), 3, 'float')
        r2 = rt.binary('-', rt.binary('*', prng__vec3.call(rt.construct(3, wrap, rt.construct(1, _u_seed))), rt.f(2), 3, 'float'), rt.f(1), 3, 'float')
        spd = rt.component_wise('floor', _u_speed)
        point.replace((rt.binary('+', point, rt.construct(2, rt.binary('*', rt.component_wise('sin', rt.binary('+', rt.binary('*', rt.binary('*', _u_time, rt.f(6.2831853071800001), 1, 'float'), spd, 1, 'float'), rt.swizzle(r2, 'x'), 1, 'float')), rt.swizzle(r1, 'x'), 1, 'float'), rt.binary('*', rt.component_wise('cos', rt.binary('+', rt.binary('*', rt.binary('*', _u_time, rt.f(6.2831853071800001), 1, 'float'), spd, 1, 'float'), rt.swizzle(r2, 'y'), 1, 'float')), rt.swizzle(r1, 'y'), 1, 'float')), 2, 'float')).map { |c| rt.f32(c) })
        diff = rt.binary('-', rt.binary('+', n, point, 2, 'float'), f, 2, 'float')
        dist = shapeDistance__vec2_vec2_int_float.call(rt.construct(2, rt.swizzle(diff, 'x'), rt.unary('-', rt.swizzle(diff, 'y'))), rt.construct(2, rt.f(0)), sides, cellSize)
        if rt.bool(rt.binary('==', _u_shape, rt.i(1)))
          dist = rt.binary('+', rt.component_wise('abs', rt.binary('-', rt.binary('+', rt.swizzle(n, 'x'), rt.swizzle(point, 'x'), 1, 'float'), rt.swizzle(f, 'x'), 1, 'float')), rt.component_wise('abs', rt.binary('-', rt.binary('+', rt.swizzle(n, 'y'), rt.swizzle(point, 'y'), 1, 'float'), rt.swizzle(f, 'y'), 1, 'float')), 1, 'float')
          dist = rt.binary('*', dist, cellSize, 1, 'float')
        end
        dist = rt.binary('+', dist, rt.binary('*', rt.swizzle(r1, 'z'), rt.binary('*', _u_variation, rt.f(0.01), 1, 'float'), 1, 'float'), 1, 'float')
        d = smin__float_float_float.call(d, dist, rt.binary('*', _u_cellSmooth, rt.f(0.01), 1, 'float'))
      end
    end
    return d
  end
  main__void = lambda do
    cellSize = nil; color = nil; d = nil; freq = nil; globalCoord = nil; st = nil; texCoord = nil; texFactor = nil; texLuminosity = nil; texRGB = nil
    globalCoord = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
    color = rt.construct(4, rt.f(0), rt.f(0), rt.f(1), rt.f(1))
    st = rt.binary('/', globalCoord, rt.swizzle(_u_fullResolution, 'y'), 2, 'float')
    freq = map__float_float_float_float_float.call(_u_scale, rt.f(1), rt.f(100), rt.f(20), rt.f(1))
    cellSize = map__float_float_float_float_float.call(_u_cellScale, rt.f(1), rt.f(100), rt.f(3), rt.f(0.75))
    texLuminosity = rt.f(0)
    texFactor = rt.binary('*', _u_texIntensity, rt.f(0.01), 1, 'float')
    texCoord = rt.binary('/', globalCoord, _u_fullResolution, 2, 'float')
    texRGB = rt.construct(3, 0.0)
    if rt.bool(rt.binary('>', _u_texInfluence, rt.i(0)))
      texRGB = rt.swizzle(rt.texture(_u_tex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_tex)), 2, 'float')), 'rgb')
      texLuminosity = luminance__vec3.call(texRGB)
      if rt.bool(rt.binary('==', _u_texInfluence, rt.i(1)))
        cellSize = rt.binary('-', cellSize, rt.binary('*', texLuminosity, texFactor, 1, 'float'), 1, 'float')
      else
        if rt.bool(rt.binary('==', _u_texInfluence, rt.i(2)))
          freq = rt.binary('-', freq, rt.binary('*', texLuminosity, rt.binary('*', texFactor, rt.f(5), 1, 'float'), 1, 'float'), 1, 'float')
        end
      end
    end
    d = cells__vec2_float_float_int.call(st, freq, cellSize, _u_shape)
    if rt.bool(rt.binary('>=', _u_texInfluence, rt.i(10)))
      if rt.bool(rt.binary('==', _u_texInfluence, rt.i(10)))
        d = rt.binary('+', d, rt.binary('*', texLuminosity, texFactor, 1, 'float'), 1, 'float')
      else
        if rt.bool(rt.binary('==', _u_texInfluence, rt.i(11)))
          d = rt.component_wise('mix', d, rt.binary('/', d, rt.component_wise('max', rt.f(0.10000000000000001), texLuminosity), 1, 'float'), texFactor)
        else
          if rt.bool(rt.binary('==', _u_texInfluence, rt.i(12)))
            d = rt.component_wise('mix', d, rt.component_wise('min', d, texLuminosity), texFactor)
          else
            if rt.bool(rt.binary('==', _u_texInfluence, rt.i(13)))
              d = rt.component_wise('mix', d, rt.component_wise('max', d, texLuminosity), texFactor)
            else
              if rt.bool(rt.binary('==', _u_texInfluence, rt.i(14)))
                d = rt.component_wise('mix', d, rt.component_wise('mod', d, rt.component_wise('max', rt.f(0.10000000000000001), texLuminosity)), texFactor)
              else
                if rt.bool(rt.binary('==', _u_texInfluence, rt.i(15)))
                  d = rt.component_wise('mix', d, rt.binary('*', d, texLuminosity, 1, 'float'), texFactor)
                else
                  if rt.bool(rt.binary('==', _u_texInfluence, rt.i(16)))
                    d = rt.binary('-', d, rt.binary('*', texLuminosity, texFactor, 1, 'float'), 1, 'float')
                  end
                end
              end
            end
          end
        end
      end
    end
    if rt.bool(rt.binary('==', _u_colorMode, rt.i(0)))
      color = rt.assign_swizzle(color, 'rgb', rt.construct(3, d))
    else
      if rt.bool(rt.binary('==', _u_colorMode, rt.i(1)))
        color = rt.assign_swizzle(color, 'rgb', rt.construct(3, rt.binary('-', rt.f(1), d, 1, 'float')))
      else
        if rt.bool(rt.binary('==', _u_colorMode, rt.i(2)))
          if rt.bool(rt.binary('==', _u_cyclePalette, rt.unary('-', rt.i(1))))
            d = rt.binary('+', d, _u_time, 1, 'float')
          else
            if rt.bool(rt.binary('==', _u_cyclePalette, rt.i(1)))
              d = rt.binary('-', d, _u_time, 1, 'float')
            end
          end
          color = rt.assign_swizzle(color, 'rgb', pal__float.call(d))
        end
      end
    end
    st.replace((rt.binary('/', globalCoord, _u_fullResolution, 2, 'float')).map { |c| rt.f32(c) })
    g['fragColor'].replace((color).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
