# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  clamp01__vec3 = chebyshev_mask__vec2 = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_renderScale = u.key?('renderScale') ? u['renderScale'] : rt.f(0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['TAP_COUNT'] = rt.i(32)
  g['RADIUS'] = rt.f(48)
  g['GOLDEN_ANGLE'] = rt.f(2.3999631404876709)
  g['BRIGHTNESS_ADJUST'] = rt.f(0.15000000596046448)
  clamp01__vec3 = lambda do |v|
    v = rt.copy(v, 'float')
    return rt.component_wise('clamp', v, rt.construct(3, rt.f(0)), rt.construct(3, rt.f(1)))
  end
  chebyshev_mask__vec2 = lambda do |uv|
    uv = rt.copy(uv, 'float')
    centered = nil
    centered = rt.construct(2, ((rt.component_wise('abs', rt.f32(((uv[0]) - ((rt.f(0.5))))))) * (rt.f(2))), ((rt.component_wise('abs', rt.f32(((uv[1]) - ((rt.f(0.5))))))) * (rt.f(2))))
    return rt.component_wise('max', rt.swizzle(centered, 'x'), rt.swizzle(centered, 'y'))
  end
  main__void = lambda do
    __hoist1608 = nil; _for0_first = nil; _t = nil; a = nil; bloomed = nil; blurAccum = nil; blurred = nil; boosted = nil; edgeBlended = nil; edgeMask = nil; finalRgb = nil; fullRes = nil; globalCoord = nil; globalUV = nil; i = nil; offset = nil; original = nil; r = nil; radiusUV = nil; sampleGlobalUV = nil; sampleLocalUV = nil; sigma = nil; sourceClamped = nil; texelSize = nil; theta = nil; uv = nil; weight = nil; weightSum = nil
    globalCoord = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0])), ((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1])))
    uv = rt.construct(2, ((globalCoord[0]) / (_u_fullResolution[0])), ((globalCoord[1]) / (_u_fullResolution[1])))
    fullRes = rt.construct(2, (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[0]) : (_u_resolution[0])), (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[1]) : (_u_resolution[1])))
    globalUV = rt.construct(2, ((((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0]))) / (fullRes[0])), ((((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1]))) / (fullRes[1])))
    original = rt.construct(4, rt.texel_fetch(_u_inputTex, rt.construct(2, rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy')), 'int'), rt.i(0)))
    a = rt.component_wise('clamp', _u_alpha, rt.f(0), rt.f(1))
    if rt.bool(rt.binary('<=', a, rt.f(0)))
      g['fragColor'].replace((rt.construct(4, clamp01__vec3.call(rt.swizzle(original, 'rgb')), rt.swizzle(original, 'a'))).map { |c| rt.f32(c) })
      return
    end
    texelSize = rt.construct(2, ((rt.f(1)) / (_u_fullResolution[0])), ((rt.f(1)) / (_u_fullResolution[1])))
    radiusUV = rt.construct(2, ((((g['RADIUS']) * (_u_renderScale))) * (texelSize[0])), ((((g['RADIUS']) * (_u_renderScale))) * (texelSize[1])))
    blurAccum = rt.construct(3, rt.construct(3, rt.f(0)))
    weightSum = rt.f(0)
    i = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', i, g['TAP_COUNT']))
        break
      end
      _t = rt.binary('/', rt.construct(1, i), rt.construct(1, g['TAP_COUNT']), 1, 'float')
      r = rt.component_wise('sqrt', _t)
      theta = rt.binary('*', rt.construct(1, i), g['GOLDEN_ANGLE'], 1, 'float')
      offset = rt.construct(2, (((rt.component_wise('cos', theta))) * (r)), (((rt.component_wise('sin', theta))) * (r)))
      sigma = rt.f(0.40000000596046448)
      weight = rt.component_wise('exp', rt.binary('/', rt.binary('*', rt.unary('-', rt.f(0.5)), rt.binary('*', r, r, 1, 'float'), 1, 'float'), rt.binary('*', sigma, sigma, 1, 'float'), 1, 'float'))
      sampleGlobalUV = rt.construct(2, rt.component_wise('clamp', rt.f32(((uv[0]) + (((offset[0]) * (radiusUV[0]))))), (rt.f(0)), (rt.f(1))), rt.component_wise('clamp', rt.f32(((uv[1]) + (((offset[1]) * (radiusUV[1]))))), (rt.f(0)), (rt.f(1))))
      sampleLocalUV = rt.construct(2, ((((((sampleGlobalUV[0]) * (_u_fullResolution[0]))) - (_u_tileOffset[0]))) / (((rt.texture_size(_u_inputTex))[0]))), ((((((sampleGlobalUV[1]) * (_u_fullResolution[1]))) - (_u_tileOffset[1]))) / (((rt.texture_size(_u_inputTex))[1]))))
      __hoist1608 = rt.binary('*', rt.swizzle(rt.texture(_u_inputTex, sampleLocalUV), 'rgb'), weight, 3, 'float'); blurAccum[0] = rt.f32(rt.binary('+', blurAccum[0], __hoist1608[0], 1, 'float')); blurAccum[1] = rt.f32(rt.binary('+', blurAccum[1], __hoist1608[1], 1, 'float')); blurAccum[2] = rt.f32(rt.binary('+', blurAccum[2], __hoist1608[2], 1, 'float'))
      weightSum = rt.binary('+', weightSum, weight, 1, 'float')
    end
    blurred = rt.construct(3, ((blurAccum[0]) / (weightSum)), ((blurAccum[1]) / (weightSum)), ((blurAccum[2]) / (weightSum)))
    boosted = rt.construct(3, clamp01__vec3.call(rt.construct(3, ((blurred[0]) + ((g['BRIGHTNESS_ADJUST']))), ((blurred[1]) + ((g['BRIGHTNESS_ADJUST']))), ((blurred[2]) + ((g['BRIGHTNESS_ADJUST']))))))
    edgeMask = chebyshev_mask__vec2.call(globalUV)
    edgeMask = rt.component_wise('smoothstep', rt.f(0), rt.f(0.80000001192092896), edgeMask)
    sourceClamped = rt.construct(3, clamp01__vec3.call(rt.swizzle(original, 'rgb')))
    bloomed = rt.construct(3, clamp01__vec3.call(rt.construct(3, ((((sourceClamped[0]) + (boosted[0]))) * (rt.f(0.5))), ((((sourceClamped[1]) + (boosted[1]))) * (rt.f(0.5))), ((((sourceClamped[2]) + (boosted[2]))) * (rt.f(0.5))))))
    edgeBlended = rt.construct(3, rt.component_wise('mix', sourceClamped[0], bloomed[0], edgeMask), rt.component_wise('mix', sourceClamped[1], bloomed[1], edgeMask), rt.component_wise('mix', sourceClamped[2], bloomed[2], edgeMask))
    finalRgb = rt.construct(3, clamp01__vec3.call(rt.component_wise('mix', sourceClamped, edgeBlended, a)))
    g['fragColor'].replace((rt.construct(4, finalRgb, rt.swizzle(original, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
