# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  main__void = nil
  _retc = nil
  _u__MODE = u.key?('MODE') ? u['MODE'] : 0
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_smoothness = u.key?('smoothness') ? u['smoothness'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  main__void = lambda do
    __hoist1304 = nil; _for0_first = nil; _for1_first = nil; blurred = nil; src = nil; sum = nil; texel = nil; uv = nil; w = nil; wsum = nil; x = nil; y = nil
    uv = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) / (_u_resolution[0])), ((rt.swizzle(ctx.frag_coord, 'y')) / (_u_resolution[1])))
    texel = rt.construct(2, ((rt.f(1)) / (_u_resolution[0])), ((rt.f(1)) / (_u_resolution[1])))
    src = rt.construct(4, (rt.texture(_u_inputTex, uv))[0], (rt.texture(_u_inputTex, uv))[1], (rt.texture(_u_inputTex, uv))[2], (rt.texture(_u_inputTex, uv))[3])
    sum = rt.construct(4, rt.construct(4, rt.f(0)))
    wsum = rt.f(0)
    y = rt.unary('-', rt.i(1))
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        y = rt.binary('+', y, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<=', y, rt.i(1)))
        break
      end
      x = rt.unary('-', rt.i(1))
      _for1_first = true
      (0..1048575).each do |_for1|
        unless _for1_first
          x = rt.binary('+', x, rt.i(1), 1, 'int')
        end
        _for1_first = false
        unless rt.bool(rt.binary('<=', x, rt.i(1)))
          break
        end
        w = rt.binary('*', rt.binary('-', rt.f(2), rt.component_wise('abs', rt.construct(1, x)), 1, 'float'), rt.binary('-', rt.f(2), rt.component_wise('abs', rt.construct(1, y)), 1, 'float'), 1, 'float')
        __hoist1304 = rt.binary('*', rt.texture(_u_inputTex, rt.binary('+', uv, rt.binary('*', rt.construct(2, rt.construct(1, x), rt.construct(1, y)), texel, 2, 'float'), 2, 'float')), w, 4, 'float'); sum[0] = rt.f32(rt.binary('+', sum[0], __hoist1304[0], 1, 'float')); sum[1] = rt.f32(rt.binary('+', sum[1], __hoist1304[1], 1, 'float')); sum[2] = rt.f32(rt.binary('+', sum[2], __hoist1304[2], 1, 'float')); sum[3] = rt.f32(rt.binary('+', sum[3], __hoist1304[3], 1, 'float'))
        wsum = rt.binary('+', wsum, w, 1, 'float')
      end
    end
    blurred = rt.construct(4, ((sum[0]) / (wsum)), ((sum[1]) / (wsum)), ((sum[2]) / (wsum)), ((sum[3]) / (wsum)))
    g['fragColor'].replace((rt.component_wise('mix', src, blurred, rt.component_wise('clamp', rt.binary('/', _u_smoothness, rt.f(100), 1, 'float'), rt.f(0), rt.f(1)))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
