# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  clamp01__float = s_curve01__float = fade__float = freq_for_shape__float_vec2 = hash_uint__uint = fast_hash__ivec3_uint = value_noise__vec2_vec2_float_uint = height_paper__vec2_vec2_float = height_stucco__vec2_vec2_float = height_canvas__vec2_vec2_float = height_halftone__vec2_vec2 = height_crosshatch__vec2_vec2 = height_field__vec2_vec2_float = material_hash__ivec2_uint_uint = material_gradient__ivec2_uint_uint = material_fade__vec2 = material_gradient_layer__vec2_uint_uint = material_noise__vec2_vec2_float_uint = material_soft__vec2_float_uint_float = material_directional__vec2_float_uint_float = material_sprinkles__vec2_float_uint_float = material_edge_mask__vec2_vec2 = material_value__vec2_vec2_vec2_float_uint = shape_material__float = main__void = nil
  _retc = nil
  _u__MODE = u.key?('MODE') ? u['MODE'] : 0
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  _u_scale = u.key?('scale') ? u['scale'] : rt.f(0.0)
  _u_intensity = u.key?('intensity') ? u['intensity'] : rt.f(0.0)
  _u_contrast = u.key?('contrast') ? u['contrast'] : rt.f(0.0)
  _u_mono = u.key?('mono') ? u['mono'] : 0
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['PI'] = rt.f(3.1415926535900001)
  g['INV_UINT32_MAX'] = rt.binary('/', rt.f(1), rt.f(4294967295), 1, 'float')
  g['Z_LOOP'] = rt.i(2)
  g['SHADE_GAIN'] = rt.f(4.4000000000000004)
  clamp01__float = lambda do |value|
    return rt.component_wise('clamp', value, rt.f(0), rt.f(1))
  end
  s_curve01__float = lambda do |value|
    c = nil
    c = clamp01__float.call(value)
    return rt.binary('*', rt.binary('*', c, c, 1, 'float'), rt.binary('-', rt.f(3), rt.binary('*', rt.f(2), c, 1, 'float'), 1, 'float'), 1, 'float')
  end
  fade__float = lambda do |_t|
    return rt.binary('*', rt.binary('*', _t, _t, 1, 'float'), rt.binary('-', rt.f(3), rt.binary('*', rt.f(2), _t, 1, 'float'), 1, 'float'), 1, 'float')
  end
  freq_for_shape__float_vec2 = lambda do |base_freq, dims|
    dims = rt.copy(dims, 'float')
    h = nil; w = nil
    w = rt.component_wise('max', rt.swizzle(dims, 'x'), rt.f(1))
    h = rt.component_wise('max', rt.swizzle(dims, 'y'), rt.f(1))
    if rt.bool(rt.binary('<', rt.component_wise('abs', rt.binary('-', w, h, 1, 'float')), rt.f(0.5)))
      return rt.construct(2, base_freq, base_freq)
    end
    if rt.bool(rt.binary('>', w, h))
      return rt.construct(2, base_freq, rt.binary('/', rt.binary('*', base_freq, w, 1, 'float'), h, 1, 'float'))
    end
    return rt.construct(2, rt.binary('/', rt.binary('*', base_freq, h, 1, 'float'), w, 1, 'float'), base_freq)
  end
  hash_uint__uint = lambda do |x|
    x = rt.binary('^', x, rt.binary('>>', x, rt.i(16), 1, 'uint'), 1, 'uint')
    x = rt.binary('*', x, rt.i(2146121005), 1, 'uint')
    x = rt.binary('^', x, rt.binary('>>', x, rt.i(15), 1, 'uint'), 1, 'uint')
    x = rt.binary('*', x, rt.i(2221713035), 1, 'uint')
    x = rt.binary('^', x, rt.binary('>>', x, rt.i(16), 1, 'uint'), 1, 'uint')
    return x
  end
  fast_hash__ivec3_uint = lambda do |p, salt|
    p = rt.copy(p, 'int')
    h = nil
    h = rt.binary('^', salt, rt.i(2654435769), 1, 'uint')
    h = rt.binary('^', h, rt.binary('*', rt.construct(1, rt.swizzle(p, 'x'), 'uint'), rt.i(668265261), 1, 'uint'), 1, 'uint')
    h = rt.hash_uint(h)
    h = rt.binary('^', h, rt.binary('*', rt.construct(1, rt.swizzle(p, 'y'), 'uint'), rt.i(3266489909), 1, 'uint'), 1, 'uint')
    h = rt.hash_uint(h)
    h = rt.binary('^', h, rt.binary('*', rt.construct(1, rt.swizzle(p, 'z'), 'uint'), rt.i(374761393), 1, 'uint'), 1, 'uint')
    h = rt.hash_uint(h)
    return rt.binary('*', rt.construct(1, h), g['INV_UINT32_MAX'], 1, 'float')
  end
  value_noise__vec2_vec2_float_uint = lambda do |uv, freq, motion, salt|
    uv = rt.copy(uv, 'float')
    freq = rt.copy(freq, 'float')
    base_cell = nil; c000 = nil; c001 = nil; c010 = nil; c011 = nil; c100 = nil; c101 = nil; c110 = nil; c111 = nil; cell_floor = nil; frac_part = nil; scaled_uv = nil; tx = nil; ty = nil; tz = nil; x00 = nil; x01 = nil; x10 = nil; x11 = nil; y0 = nil; y1 = nil; z0 = nil; z1 = nil; z_floor = nil; z_frac = nil
    scaled_uv = rt.binary('*', uv, rt.component_wise('max', freq, rt.construct(2, rt.f(1), rt.f(1))), 2, 'float')
    cell_floor = rt.component_wise('floor', scaled_uv)
    frac_part = rt.component_wise('fract', scaled_uv)
    base_cell = rt.construct(2, cell_floor, 'int')
    z_floor = rt.component_wise('floor', motion)
    z_frac = rt.component_wise('fract', motion)
    z0 = rt.binary('%', rt.construct(1, z_floor, 'int'), g['Z_LOOP'], 1, 'int')
    z1 = rt.binary('%', rt.binary('+', z0, rt.i(1), 1, 'int'), g['Z_LOOP'], 1, 'int')
    c000 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(0), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(0), 1, 'int'), z0, 'int'), salt)
    c100 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(1), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(0), 1, 'int'), z0, 'int'), salt)
    c010 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(0), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(1), 1, 'int'), z0, 'int'), salt)
    c110 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(1), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(1), 1, 'int'), z0, 'int'), salt)
    c001 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(0), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(0), 1, 'int'), z1, 'int'), salt)
    c101 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(1), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(0), 1, 'int'), z1, 'int'), salt)
    c011 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(0), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(1), 1, 'int'), z1, 'int'), salt)
    c111 = fast_hash__ivec3_uint.call(rt.construct(3, rt.binary('+', rt.swizzle(base_cell, 'x'), rt.i(1), 1, 'int'), rt.binary('+', rt.swizzle(base_cell, 'y'), rt.i(1), 1, 'int'), z1, 'int'), salt)
    tx = fade__float.call(rt.swizzle(frac_part, 'x'))
    ty = fade__float.call(rt.swizzle(frac_part, 'y'))
    tz = fade__float.call(z_frac)
    x00 = rt.component_wise('mix', c000, c100, tx)
    x10 = rt.component_wise('mix', c010, c110, tx)
    x01 = rt.component_wise('mix', c001, c101, tx)
    x11 = rt.component_wise('mix', c011, c111, tx)
    y0 = rt.component_wise('mix', x00, x10, ty)
    y1 = rt.component_wise('mix', x01, x11, ty)
    return rt.component_wise('mix', y0, y1, tz)
  end
  height_paper__vec2_vec2_float = lambda do |uv, base_freq, motion|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    _for0_first = nil; accum = nil; amplitude = nil; freq = nil; octave = nil; ridged = nil; salt = nil; samp = nil; total = nil
    freq = rt.component_wise('max', base_freq, rt.construct(2, rt.f(1), rt.f(1)))
    amplitude = rt.f(0.5)
    accum = rt.f(0)
    total = rt.f(0)
    octave = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        octave = rt.binary('+', octave, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', octave, rt.i(3)))
        break
      end
      salt = rt.binary('*', rt.i(2654435769), rt.construct(1, rt.binary('+', octave, rt.i(1), 1, 'int'), 'uint'), 1, 'uint')
      samp = value_noise__vec2_vec2_float_uint.call(uv, freq, rt.binary('+', motion, rt.binary('*', rt.construct(1, octave), rt.f(0.37), 1, 'float'), 1, 'float'), salt)
      ridged = rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', samp, rt.f(2), 1, 'float'), rt.f(1), 1, 'float')), 1, 'float')
      accum = rt.binary('+', accum, rt.binary('*', ridged, amplitude, 1, 'float'), 1, 'float')
      total = rt.binary('+', total, amplitude, 1, 'float')
      freq.replace((rt.binary('*', freq, rt.f(2), 2, 'float')).map { |c| rt.f32(c) })
      amplitude = rt.binary('*', amplitude, rt.f(0.55000000000000004), 1, 'float')
    end
    return (rt.bool(rt.binary('>', total, rt.f(0))) ? (clamp01__float.call(rt.binary('/', accum, total, 1, 'float'))) : (clamp01__float.call(accum)))
  end
  height_stucco__vec2_vec2_float = lambda do |uv, base_freq, motion|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    _for1_first = nil; accum = nil; amplitude = nil; freq = nil; octave = nil; salt = nil; samp = nil; total = nil
    freq = rt.component_wise('max', base_freq, rt.construct(2, rt.f(1), rt.f(1)))
    amplitude = rt.f(0.5)
    accum = rt.f(0)
    total = rt.f(0)
    octave = rt.i(0)
    _for1_first = true
    (0..1048575).each do |_for1|
      unless _for1_first
        octave = rt.binary('+', octave, rt.i(1), 1, 'int')
      end
      _for1_first = false
      unless rt.bool(rt.binary('<', octave, rt.i(2)))
        break
      end
      salt = rt.binary('*', rt.i(2654435769), rt.construct(1, rt.binary('+', octave, rt.i(1), 1, 'int'), 'uint'), 1, 'uint')
      samp = value_noise__vec2_vec2_float_uint.call(uv, freq, rt.binary('+', motion, rt.binary('*', rt.construct(1, octave), rt.f(0.37), 1, 'float'), 1, 'float'), salt)
      accum = rt.binary('+', accum, rt.binary('*', samp, amplitude, 1, 'float'), 1, 'float')
      total = rt.binary('+', total, amplitude, 1, 'float')
      freq.replace((rt.binary('*', freq, rt.f(2), 2, 'float')).map { |c| rt.f32(c) })
      amplitude = rt.binary('*', amplitude, rt.f(0.5), 1, 'float')
    end
    return (rt.bool(rt.binary('>', total, rt.f(0))) ? (clamp01__float.call(rt.binary('/', accum, total, 1, 'float'))) : (clamp01__float.call(accum)))
  end
  height_canvas__vec2_vec2_float = lambda do |uv, base_freq, motion|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    noise = nil; st = nil; warpX = nil; weave = nil; weftY = nil
    st = rt.binary('*', uv, base_freq, 2, 'float')
    warpX = rt.component_wise('abs', rt.component_wise('sin', rt.binary('*', rt.swizzle(st, 'x'), g['PI'], 1, 'float')))
    weftY = rt.component_wise('abs', rt.component_wise('sin', rt.binary('*', rt.swizzle(st, 'y'), g['PI'], 1, 'float')))
    weave = rt.binary('*', warpX, weftY, 1, 'float')
    noise = value_noise__vec2_vec2_float_uint.call(uv, rt.binary('*', base_freq, rt.f(0.5), 2, 'float'), motion, rt.i(305419896))
    return clamp01__float.call(rt.binary('+', rt.binary('*', weave, rt.f(0.84999999999999998), 1, 'float'), rt.binary('*', noise, rt.f(0.14999999999999999), 1, 'float'), 1, 'float'))
  end
  height_halftone__vec2_vec2 = lambda do |uv, base_freq|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    cell = nil; dot = nil; st = nil
    st = rt.binary('*', uv, base_freq, 2, 'float')
    cell = rt.binary('-', rt.component_wise('fract', st), rt.f(0.5), 2, 'float')
    dot = rt.binary('-', rt.f(1), clamp01__float.call(rt.binary('*', rt.length(cell), rt.f(3), 1, 'float')), 1, 'float')
    return rt.binary('*', dot, dot, 1, 'float')
  end
  height_crosshatch__vec2_vec2 = lambda do |uv, base_freq|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    d1 = nil; d2 = nil; st = nil
    st = rt.binary('*', uv, base_freq, 2, 'float')
    d1 = rt.component_wise('abs', rt.component_wise('sin', rt.binary('*', rt.binary('+', rt.swizzle(st, 'x'), rt.swizzle(st, 'y'), 1, 'float'), g['PI'], 1, 'float')))
    d2 = rt.component_wise('abs', rt.component_wise('sin', rt.binary('*', rt.binary('-', rt.swizzle(st, 'x'), rt.swizzle(st, 'y'), 1, 'float'), g['PI'], 1, 'float')))
    return clamp01__float.call(rt.binary('*', d1, d2, 1, 'float'))
  end
  height_field__vec2_vec2_float = lambda do |uv, base_freq, motion|
    uv = rt.copy(uv, 'float')
    base_freq = rt.copy(base_freq, 'float')
    if rt.bool(rt.binary('==', _u__MODE, rt.i(0)))
      return height_canvas__vec2_vec2_float.call(uv, base_freq, motion)
    else
      if rt.bool(rt.binary('==', _u__MODE, rt.i(1)))
        return height_crosshatch__vec2_vec2.call(uv, base_freq)
      else
        if rt.bool(rt.binary('==', _u__MODE, rt.i(2)))
          return height_halftone__vec2_vec2.call(uv, base_freq)
        else
          if rt.bool(rt.binary('==', _u__MODE, rt.i(4)))
            return height_stucco__vec2_vec2_float.call(uv, base_freq, motion)
          else
            return height_paper__vec2_vec2_float.call(uv, base_freq, motion)
          end
        end
      end
    end
  end
  material_hash__ivec2_uint_uint = lambda do |p, salt, layer|
    p = rt.copy(p, 'int')
    h = nil
    h = rt.binary('^', salt, rt.binary('*', layer, rt.i(2654435769), 1, 'uint'), 1, 'uint')
    h = rt.binary('^', h, rt.binary('*', rt.construct(1, rt.swizzle(p, 'x'), 'uint'), rt.i(668265261), 1, 'uint'), 1, 'uint')
    h = rt.hash_uint(h)
    h = rt.binary('^', h, rt.binary('*', rt.construct(1, rt.swizzle(p, 'y'), 'uint'), rt.i(3266489909), 1, 'uint'), 1, 'uint')
    return rt.hash_uint(h)
  end
  material_gradient__ivec2_uint_uint = lambda do |p, salt, layer|
    p = rt.copy(p, 'int')
    gradient = nil; h = nil
    h = material_hash__ivec2_uint_uint.call(p, salt, layer)
    gradient = rt.binary('-', rt.binary('*', rt.construct(2, rt.construct(1, rt.binary('&', h, rt.i(65535), 1, 'uint')), rt.construct(1, rt.binary('>>', h, rt.i(16), 1, 'uint'))), rt.binary('/', rt.f(2), rt.f(65535), 1, 'float'), 2, 'float'), rt.f(1), 2, 'float')
    return rt.binary('*', gradient, rt.component_wise('inversesqrt', rt.component_wise('max', rt.dot(gradient, gradient), rt.f(9.9999999999999995e-07))), 2, 'float')
  end
  material_fade__vec2 = lambda do |_t|
    _t = rt.copy(_t, 'float')
    return rt.binary('*', rt.binary('*', rt.binary('*', _t, _t, 2, 'float'), _t, 2, 'float'), rt.binary('+', rt.binary('*', _t, rt.binary('-', rt.binary('*', _t, rt.f(6), 2, 'float'), rt.f(15), 2, 'float'), 2, 'float'), rt.f(10), 2, 'float'), 2, 'float')
  end
  material_gradient_layer__vec2_uint_uint = lambda do |p, salt, layer|
    p = rt.copy(p, 'float')
    blend = nil; cell = nil; local = nil; n00 = nil; n01 = nil; n10 = nil; n11 = nil
    cell = rt.construct(2, rt.component_wise('floor', p), 'int')
    local = rt.component_wise('fract', p)
    n00 = rt.dot(material_gradient__ivec2_uint_uint.call(cell, salt, layer), local)
    n10 = rt.dot(material_gradient__ivec2_uint_uint.call(rt.binary('+', cell, rt.construct(2, rt.i(1), rt.i(0), 'int'), 2, 'int'), salt, layer), rt.binary('-', local, rt.construct(2, rt.f(1), rt.f(0)), 2, 'float'))
    n01 = rt.dot(material_gradient__ivec2_uint_uint.call(rt.binary('+', cell, rt.construct(2, rt.i(0), rt.i(1), 'int'), 2, 'int'), salt, layer), rt.binary('-', local, rt.construct(2, rt.f(0), rt.f(1)), 2, 'float'))
    n11 = rt.dot(material_gradient__ivec2_uint_uint.call(rt.binary('+', cell, rt.construct(2, rt.i(1), rt.i(1), 'int'), 2, 'int'), salt, layer), rt.binary('-', local, rt.construct(2, rt.f(1), rt.f(1)), 2, 'float'))
    blend = material_fade__vec2.call(local)
    return rt.component_wise('mix', rt.component_wise('mix', n00, n10, rt.swizzle(blend, 'x')), rt.component_wise('mix', n01, n11, rt.swizzle(blend, 'x')), rt.swizzle(blend, 'y'))
  end
  material_noise__vec2_vec2_float_uint = lambda do |globalPixel, cellSize, motion, salt|
    globalPixel = rt.copy(globalPixel, 'float')
    cellSize = rt.copy(cellSize, 'float')
    n = nil; n0 = nil; n1 = nil; p = nil; z0 = nil; z1 = nil; zFloor = nil
    p = rt.binary('/', globalPixel, rt.component_wise('max', cellSize, rt.construct(2, rt.f(0.5))), 2, 'float')
    zFloor = rt.component_wise('floor', motion)
    z0 = rt.binary('%', rt.construct(1, zFloor, 'int'), g['Z_LOOP'], 1, 'int')
    z1 = rt.binary('%', rt.binary('+', z0, rt.i(1), 1, 'int'), g['Z_LOOP'], 1, 'int')
    n0 = material_gradient_layer__vec2_uint_uint.call(p, salt, rt.construct(1, z0, 'uint'))
    n1 = material_gradient_layer__vec2_uint_uint.call(p, salt, rt.construct(1, z1, 'uint'))
    n = rt.component_wise('mix', n0, n1, rt.swizzle(material_fade__vec2.call(rt.construct(2, rt.component_wise('fract', motion))), 'x'))
    return clamp01__float.call(rt.binary('+', rt.f(0.5), rt.binary('*', n, rt.f(0.71999999999999997), 1, 'float'), 1, 'float'))
  end
  material_soft__vec2_float_uint_float = lambda do |globalPixel, motion, salt, size|
    globalPixel = rt.copy(globalPixel, 'float')
    primary = nil; primaryCell = nil; secondary = nil
    primaryCell = rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(3.25), 1, 'float'), rt.f(1.5)))
    primary = material_noise__vec2_vec2_float_uint.call(globalPixel, primaryCell, motion, salt)
    secondary = material_noise__vec2_vec2_float_uint.call(rt.binary('+', globalPixel, rt.construct(2, rt.f(17.309999999999999), rt.f(29.170000000000002)), 2, 'float'), rt.binary('*', primaryCell, rt.f(1.8700000000000001), 2, 'float'), rt.binary('+', motion, rt.f(0.40999999999999998), 1, 'float'), rt.binary('^', salt, rt.i(1757159915), 1, 'uint'))
    return rt.binary('+', rt.binary('*', primary, rt.f(0.68000000000000005), 1, 'float'), rt.binary('*', secondary, rt.f(0.32000000000000001), 1, 'float'), 1, 'float')
  end
  material_directional__vec2_float_uint_float = lambda do |globalPixel, motion, salt, size|
    globalPixel = rt.copy(globalPixel, 'float')
    primary = nil; primaryCell = nil; secondary = nil; secondaryCell = nil
    primaryCell = rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(22), 1, 'float'), rt.f(8)), rt.component_wise('max', rt.binary('*', size, rt.f(2), 1, 'float'), rt.f(1.25)))
    secondaryCell = rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(37), 1, 'float'), rt.f(13)), rt.component_wise('max', rt.binary('*', size, rt.f(3.7000000000000002), 1, 'float'), rt.f(2.2999999999999998)))
    primary = material_noise__vec2_vec2_float_uint.call(globalPixel, primaryCell, motion, salt)
    secondary = material_noise__vec2_vec2_float_uint.call(rt.binary('+', globalPixel, rt.construct(2, rt.f(19.370000000000001), rt.f(11.83)), 2, 'float'), secondaryCell, rt.binary('+', motion, rt.f(0.40999999999999998), 1, 'float'), rt.binary('^', salt, rt.i(1757159915), 1, 'uint'))
    return rt.binary('+', rt.binary('*', primary, rt.f(0.71999999999999997), 1, 'float'), rt.binary('*', secondary, rt.f(0.28000000000000003), 1, 'float'), 1, 'float')
  end
  material_sprinkles__vec2_float_uint_float = lambda do |globalPixel, motion, salt, size|
    globalPixel = rt.copy(globalPixel, 'float')
    _for2_first = nil; _for3_first = nil; baseCell = nil; cell = nil; jx = nil; jy = nil; local = nil; nearest = nil; p = nil; point = nil; x = nil; y = nil
    p = rt.binary('+', rt.binary('/', globalPixel, rt.component_wise('max', rt.binary('*', rt.f(4), size, 1, 'float'), rt.f(1)), 2, 'float'), rt.construct(2, rt.binary('*', motion, rt.f(0.31), 1, 'float'), rt.binary('*', motion, rt.f(0.19), 1, 'float')), 2, 'float')
    baseCell = rt.construct(2, rt.component_wise('floor', p), 'int')
    local = rt.component_wise('fract', p)
    nearest = rt.f(10)
    y = rt.unary('-', rt.i(1))
    _for2_first = true
    (0..1048575).each do |_for2|
      unless _for2_first
        y = rt.binary('+', y, rt.i(1), 1, 'int')
      end
      _for2_first = false
      unless rt.bool(rt.binary('<=', y, rt.i(1)))
        break
      end
      x = rt.unary('-', rt.i(1))
      _for3_first = true
      (0..1048575).each do |_for3|
        unless _for3_first
          x = rt.binary('+', x, rt.i(1), 1, 'int')
        end
        _for3_first = false
        unless rt.bool(rt.binary('<=', x, rt.i(1)))
          break
        end
        cell = rt.binary('+', baseCell, rt.construct(2, x, y, 'int'), 2, 'int')
        jx = rt.binary('-', fast_hash__ivec3_uint.call(rt.construct(3, cell, rt.i(0), 'int'), salt), rt.f(0.5), 1, 'float')
        jy = rt.binary('-', fast_hash__ivec3_uint.call(rt.construct(3, cell, rt.i(1), 'int'), rt.binary('^', salt, rt.i(1757159915), 1, 'uint')), rt.f(0.5), 1, 'float')
        point = rt.binary('+', rt.binary('+', rt.construct(2, rt.construct(1, x), rt.construct(1, y)), rt.f(0.5), 2, 'float'), rt.binary('*', rt.construct(2, jx, jy), rt.f(0.59999999999999998), 2, 'float'), 2, 'float')
        nearest = rt.component_wise('min', nearest, rt.length(rt.binary('-', local, point, 2, 'float')))
      end
    end
    return rt.component_wise('mix', rt.f(0.45000000000000001), rt.f(1), rt.binary('-', rt.f(1), rt.component_wise('smoothstep', rt.f(0.10000000000000001), rt.f(0.22), nearest), 1, 'float'))
  end
  material_edge_mask__vec2_vec2 = lambda do |uv, pixelStep|
    uv = rt.copy(uv, 'float')
    pixelStep = rt.copy(pixelStep, 'float')
    _u = nil; d = nil; l = nil; r = nil
    l = rt.dot(rt.swizzle(rt.texture(_u_inputTex, rt.binary('-', uv, rt.construct(2, rt.swizzle(pixelStep, 'x'), rt.f(0)), 2, 'float')), 'rgb'), rt.construct(3, rt.f(0.21260000000000001), rt.f(0.71519999999999995), rt.f(0.0722)))
    r = rt.dot(rt.swizzle(rt.texture(_u_inputTex, rt.binary('+', uv, rt.construct(2, rt.swizzle(pixelStep, 'x'), rt.f(0)), 2, 'float')), 'rgb'), rt.construct(3, rt.f(0.21260000000000001), rt.f(0.71519999999999995), rt.f(0.0722)))
    d = rt.dot(rt.swizzle(rt.texture(_u_inputTex, rt.binary('-', uv, rt.construct(2, rt.f(0), rt.swizzle(pixelStep, 'y')), 2, 'float')), 'rgb'), rt.construct(3, rt.f(0.21260000000000001), rt.f(0.71519999999999995), rt.f(0.0722)))
    _u = rt.dot(rt.swizzle(rt.texture(_u_inputTex, rt.binary('+', uv, rt.construct(2, rt.f(0), rt.swizzle(pixelStep, 'y')), 2, 'float')), 'rgb'), rt.construct(3, rt.f(0.21260000000000001), rt.f(0.71519999999999995), rt.f(0.0722)))
    return rt.component_wise('clamp', rt.binary('*', rt.length(rt.construct(2, rt.binary('-', r, l, 1, 'float'), rt.binary('-', _u, d, 1, 'float'))), rt.f(6), 1, 'float'), rt.f(0), rt.f(1))
  end
  material_value__vec2_vec2_vec2_float_uint = lambda do |globalPixel, dims, uv, motion, salt|
    globalPixel = rt.copy(globalPixel, 'float')
    dims = rt.copy(dims, 'float')
    uv = rt.copy(uv, 'float')
    a = nil; b = nil; c = nil; n = nil; size = nil
    size = rt.component_wise('max', _u_scale, rt.f(0.10000000000000001))
    a = rt.f(0.0)
    b = rt.f(0.0)
    c = rt.f(0.0)
    n = rt.f(0.0)
    if rt.bool(rt.binary('==', _u__MODE, rt.i(6)))
      return material_soft__vec2_float_uint_float.call(globalPixel, motion, salt, size)
    else
      if rt.bool(rt.binary('==', _u__MODE, rt.i(7)))
        return material_sprinkles__vec2_float_uint_float.call(globalPixel, motion, salt, size)
      else
        if rt.bool(rt.binary('==', _u__MODE, rt.i(8)))
          a = material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.binary('*', rt.f(13), size, 1, 'float')), motion, salt)
          b = material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.binary('*', rt.f(6), size, 1, 'float')), rt.binary('+', motion, rt.f(0.31), 1, 'float'), rt.binary('^', salt, rt.i(2654435769), 1, 'uint'))
          c = material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.binary('*', rt.f(2.5), size, 1, 'float')), rt.binary('+', motion, rt.f(0.67000000000000004), 1, 'float'), rt.binary('^', salt, rt.i(2246822507), 1, 'uint'))
          return rt.binary('+', rt.binary('+', rt.binary('*', a, rt.f(0.57999999999999996), 1, 'float'), rt.binary('*', b, rt.f(0.28000000000000003), 1, 'float'), 1, 'float'), rt.binary('*', c, rt.f(0.14000000000000001), 1, 'float'), 1, 'float')
        else
          if rt.bool(rt.binary('==', _u__MODE, rt.i(9)))
            n = material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(1.5), 1, 'float'), rt.f(0.80000000000000004))), motion, salt)
            return s_curve01__float.call(s_curve01__float.call(n))
          else
            if rt.bool(rt.binary('==', _u__MODE, rt.i(10)))
              return material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.binary('*', rt.f(4.5), size, 1, 'float')), motion, salt)
            else
              if rt.bool(rt.binary('==', _u__MODE, rt.i(11)))
                return rt.component_wise('step', rt.f(0.5), material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(1.5), 1, 'float'), rt.f(0.80000000000000004))), motion, salt))
              else
                if rt.bool(rt.binary('==', _u__MODE, rt.i(12)))
                  return material_directional__vec2_float_uint_float.call(globalPixel, motion, salt, size)
                else
                  if rt.bool(rt.binary('==', _u__MODE, rt.i(13)))
                    return material_directional__vec2_float_uint_float.call(rt.swizzle(globalPixel, 'yx'), motion, salt, size)
                  else
                    if rt.bool(rt.binary('==', _u__MODE, rt.i(14)))
                      n = material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(1.5), 1, 'float'), rt.f(0.80000000000000004))), motion, salt)
                      return rt.component_wise('mix', rt.f(0.5), n, material_edge_mask__vec2_vec2.call(uv, rt.binary('/', rt.f(1), dims, 2, 'float')))
                    else
                      return material_noise__vec2_vec2_float_uint.call(globalPixel, rt.construct(2, rt.component_wise('max', rt.binary('*', size, rt.f(1.5), 1, 'float'), rt.f(0.80000000000000004))), motion, salt)
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
  shape_material__float = lambda do |raw|
    amount = nil; c = nil; shaped = nil
    amount = rt.binary('/', _u_intensity, rt.f(40), 1, 'float')
    shaped = rt.binary('+', rt.binary('*', raw, amount, 1, 'float'), rt.binary('*', rt.f(0.5), rt.binary('-', rt.f(1), amount, 1, 'float'), 1, 'float'), 1, 'float')
    c = rt.component_wise('clamp', rt.binary('/', _u_contrast, rt.f(100), 1, 'float'), rt.f(0), rt.f(1))
    if rt.bool(rt.binary('<', c, rt.f(0.5)))
      return rt.component_wise('mix', rt.f(0.5), shaped, rt.binary('*', c, rt.f(2), 1, 'float'))
    end
    return rt.component_wise('mix', shaped, s_curve01__float.call(shaped), rt.binary('*', rt.binary('-', c, rt.f(0.5), 1, 'float'), rt.f(2), 1, 'float'))
  end
  main__void = lambda do
    a = nil; base_color = nil; base_factor = nil; base_freq = nil; dims = nil; factor = nil; freq_scale = nil; gain = nil; globalDims = nil; globalPixel = nil; gradient = nil; gx = nil; gy = nil; h_center = nil; h_down = nil; h_left = nil; h_right = nil; h_up = nil; highlight_mix = nil; material = nil; materialMotion = nil; motion = nil; pixel_step = nil; r = nil; scaled_rgb = nil; shade_base = nil
    base_color = rt.texture(_u_inputTex, ctx.uv)
    dims = rt.construct(2, rt.texture_size(_u_inputTex))
    pixel_step = rt.binary('/', rt.f(1), dims, 2, 'float')
    a = rt.component_wise('clamp', _u_alpha, rt.f(0), rt.f(1))
    if rt.bool(rt.binary('<=', a, rt.f(0)))
      g['fragColor'].replace((base_color).map { |c| rt.f32(c) })
      return
    end
    globalDims = rt.construct(2, 0.0)
    globalPixel = rt.construct(2, 0.0)
    material = rt.construct(3, 0.0)
    materialMotion = rt.f(0.0)
    r = rt.f(0.0)
    if rt.bool(rt.binary('>=', _u__MODE, rt.i(5)))
      globalDims = (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution) : (dims))
      globalPixel = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
      materialMotion = rt.binary('*', _u_time, rt.construct(1, g['Z_LOOP']), 1, 'float')
      r = shape_material__float.call(material_value__vec2_vec2_vec2_float_uint.call(globalPixel, globalDims, ctx.uv, materialMotion, rt.i(305441741)))
      material = rt.construct(3, r)
      if rt.bool((rt.bool(_u_mono) ? 0 : 1))
        material = rt.assign_swizzle(material, 'g', shape_material__float.call(material_value__vec2_vec2_vec2_float_uint.call(globalPixel, globalDims, ctx.uv, materialMotion, rt.i(1757159915))))
        material = rt.assign_swizzle(material, 'b', shape_material__float.call(material_value__vec2_vec2_vec2_float_uint.call(globalPixel, globalDims, ctx.uv, materialMotion, rt.i(48610963))))
      end
      g['fragColor'].replace((rt.construct(4, rt.component_wise('clamp', rt.component_wise('mix', rt.swizzle(base_color, 'rgb'), material, a), rt.f(0), rt.f(1)), rt.swizzle(base_color, 'a'))).map { |c| rt.f32(c) })
      return
    end
    freq_scale = rt.f(0.0)
    if rt.bool(rt.binary('==', _u__MODE, rt.i(4)))
      freq_scale = rt.f(48)
    else
      freq_scale = rt.f(24)
    end
    base_freq = freq_for_shape__float_vec2.call(rt.binary('*', freq_scale, rt.binary('-', rt.f(10.01), _u_scale, 1, 'float'), 1, 'float'), dims)
    motion = rt.binary('*', _u_time, rt.construct(1, g['Z_LOOP']), 1, 'float')
    h_center = height_field__vec2_vec2_float.call(ctx.uv, base_freq, motion)
    h_right = height_field__vec2_vec2_float.call(rt.binary('+', ctx.uv, rt.construct(2, rt.swizzle(pixel_step, 'x'), rt.f(0)), 2, 'float'), base_freq, motion)
    h_left = height_field__vec2_vec2_float.call(rt.binary('-', ctx.uv, rt.construct(2, rt.swizzle(pixel_step, 'x'), rt.f(0)), 2, 'float'), base_freq, motion)
    h_up = height_field__vec2_vec2_float.call(rt.binary('+', ctx.uv, rt.construct(2, rt.f(0), rt.swizzle(pixel_step, 'y')), 2, 'float'), base_freq, motion)
    h_down = height_field__vec2_vec2_float.call(rt.binary('-', ctx.uv, rt.construct(2, rt.f(0), rt.swizzle(pixel_step, 'y')), 2, 'float'), base_freq, motion)
    gx = rt.binary('-', h_right, h_left, 1, 'float')
    gy = rt.binary('-', h_down, h_up, 1, 'float')
    gradient = rt.component_wise('sqrt', rt.binary('+', rt.binary('*', gx, gx, 1, 'float'), rt.binary('*', gy, gy, 1, 'float'), 1, 'float'))
    gain = rt.f(0.0)
    if rt.bool(rt.binary('==', _u__MODE, rt.i(4)))
      gain = rt.binary('*', g['SHADE_GAIN'], rt.f(0.5), 1, 'float')
    else
      gain = rt.binary('*', g['SHADE_GAIN'], rt.f(0.25), 1, 'float')
    end
    shade_base = clamp01__float.call(rt.binary('*', gradient, gain, 1, 'float'))
    highlight_mix = clamp01__float.call(rt.binary('*', rt.binary('*', shade_base, shade_base, 1, 'float'), rt.f(1.25), 1, 'float'))
    base_factor = rt.binary('+', rt.f(0.90000000000000002), rt.binary('*', h_center, rt.f(0.34999999999999998), 1, 'float'), 1, 'float')
    factor = rt.component_wise('clamp', rt.binary('+', base_factor, rt.binary('*', highlight_mix, rt.f(0.34999999999999998), 1, 'float'), 1, 'float'), rt.f(0.84999999999999998), rt.f(1.6000000000000001))
    scaled_rgb = rt.component_wise('clamp', rt.binary('*', rt.swizzle(base_color, 'rgb'), factor, 3, 'float'), rt.f(0), rt.f(1))
    g['fragColor'].replace((rt.construct(4, rt.component_wise('mix', rt.swizzle(base_color, 'rgb'), scaled_rgb, a), rt.swizzle(base_color, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
