# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  map__float_float_float_float_float = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_aberrationAmt = u.key?('aberrationAmt') ? u['aberrationAmt'] : rt.f(0.0)
  _u_passthru = u.key?('passthru') ? u['passthru'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  map__float_float_float_float_float = lambda do |value, inMin, inMax, outMin, outMax|
    return rt.binary('+', outMin, rt.binary('/', rt.binary('*', rt.binary('-', outMax, outMin, 1, 'float'), rt.binary('-', value, inMin, 1, 'float'), 1, 'float'), rt.binary('-', inMax, inMin, 1, 'float'), 1, 'float'), 1, 'float')
  end
  main__void = lambda do
    aberrated = nil; aberrationOffset = nil; blue = nil; blueOffset = nil; centerDist = nil; diff = nil; edges = nil; fullRes = nil; globalAspect = nil; globalCoord = nil; globalUV = nil; green = nil; original = nil; red = nil; redOffset = nil; uv = nil
    globalCoord = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
    uv = rt.binary('/', globalCoord, _u_fullResolution, 2, 'float')
    fullRes = (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution) : (_u_resolution))
    globalUV = rt.binary('/', rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'), fullRes, 2, 'float')
    globalAspect = rt.binary('/', rt.swizzle(fullRes, 'x'), rt.swizzle(fullRes, 'y'), 1, 'float')
    diff = rt.binary('-', rt.construct(2, rt.binary('*', rt.f(0.5), globalAspect, 1, 'float'), rt.f(0.5)), rt.construct(2, rt.binary('*', rt.swizzle(globalUV, 'x'), globalAspect, 1, 'float'), rt.swizzle(globalUV, 'y')), 2, 'float')
    centerDist = rt.length(diff)
    aberrationOffset = rt.binary('*', rt.binary('*', rt.binary('*', map__float_float_float_float_float.call(_u_aberrationAmt, rt.f(0), rt.f(100), rt.f(0), rt.f(0.050000000000000003)), centerDist, 1, 'float'), rt.f(3.1415926535900001), 1, 'float'), rt.f(0.5), 1, 'float')
    redOffset = rt.component_wise('mix', rt.component_wise('clamp', rt.binary('+', rt.swizzle(uv, 'x'), aberrationOffset, 1, 'float'), rt.f(0), rt.f(1)), rt.swizzle(uv, 'x'), rt.swizzle(uv, 'x'))
    red = rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.construct(2, redOffset, rt.swizzle(uv, 'y')), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float'))
    green = rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float'))
    blueOffset = rt.component_wise('mix', rt.swizzle(uv, 'x'), rt.component_wise('clamp', rt.binary('-', rt.swizzle(uv, 'x'), aberrationOffset, 1, 'float'), rt.f(0), rt.f(1)), rt.swizzle(uv, 'x'))
    blue = rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.construct(2, blueOffset, rt.swizzle(uv, 'y')), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float'))
    aberrated = rt.construct(3, rt.swizzle(red, 'r'), rt.swizzle(green, 'g'), rt.swizzle(blue, 'b'))
    edges = rt.binary('-', aberrated, rt.swizzle(green, 'rgb'), 3, 'float')
    original = rt.binary('*', rt.swizzle(green, 'rgb'), map__float_float_float_float_float.call(_u_passthru, rt.f(0), rt.f(100), rt.f(0), rt.f(2)), 3, 'float')
    g['fragColor'].replace((rt.construct(4, rt.component_wise('min', rt.binary('+', edges, original, 3, 'float'), rt.f(1)), rt.swizzle(green, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
