# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  rot__vec2_float = mirrorFold__float = hexCoord__vec2 = rotationalFold__vec2_int = main__void = nil
  _retc = nil
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_symmetry = u.key?('symmetry') ? u['symmetry'] : 0
  _u_scale = u.key?('scale') ? u['scale'] : rt.f(0.0)
  _u_offsetX = u.key?('offsetX') ? u['offsetX'] : rt.f(0.0)
  _u_offsetY = u.key?('offsetY') ? u['offsetY'] : rt.f(0.0)
  _u_angle = u.key?('angle') ? u['angle'] : rt.f(0.0)
  _u_repeat = u.key?('repeat') ? u['repeat'] : rt.f(0.0)
  _u_aspectLens = u.key?('aspectLens') ? u['aspectLens'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  g['PI'] = rt.f(3.1415927410125732)
  g['TAU'] = rt.f(6.2831854820251465)
  rot__vec2_float = lambda do |p, a|
    p = rt.copy(p, 'float')
    c = nil; s = nil
    c = rt.component_wise('cos', a)
    s = rt.component_wise('sin', a)
    return rt.construct(2, rt.binary('-', rt.binary('*', rt.swizzle(p, 'x'), c, 1, 'float'), rt.binary('*', rt.swizzle(p, 'y'), s, 1, 'float'), 1, 'float'), rt.binary('+', rt.binary('*', rt.swizzle(p, 'x'), s, 1, 'float'), rt.binary('*', rt.swizzle(p, 'y'), c, 1, 'float'), 1, 'float'))
  end
  mirrorFold__float = lambda do |_t|
    return rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', rt.f(2), rt.component_wise('fract', rt.binary('*', _t, rt.f(0.5), 1, 'float')), 1, 'float'), rt.f(1), 1, 'float')), 1, 'float')
  end
  hexCoord__vec2 = lambda do |uv|
    uv = rt.copy(uv, 'float')
    a = nil; b = nil; h = nil; s = nil
    s = rt.construct(2, rt.construct(2, rt.f(1), rt.f(1.7320507764816284)))
    h = rt.construct(2, ((s[0]) * (rt.f(0.5))), ((s[1]) * (rt.f(0.5))))
    a = rt.construct(2, ((rt.component_wise('mod', uv[0], s[0])) - (h[0])), ((rt.component_wise('mod', uv[1], s[1])) - (h[1])))
    b = rt.construct(2, ((rt.component_wise('mod', rt.f32(((uv[0]) + (h[0]))), s[0])) - (h[0])), ((rt.component_wise('mod', rt.f32(((uv[1]) + (h[1]))), s[1])) - (h[1])))
    return rt.construct(2, (rt.bool(rt.binary('<', rt.dot(a, a), rt.dot(b, b))) ? (a[0]) : (b[0])), (rt.bool(rt.binary('<', rt.dot(a, a), rt.dot(b, b))) ? (a[1]) : (b[1])))
  end
  rotationalFold__vec2_int = lambda do |uv, n|
    uv = rt.copy(uv, 'float')
    a = nil; fn = nil; p = nil; r = nil; sectorAngle = nil
    fn = rt.construct(1, n)
    sectorAngle = rt.binary('/', g['TAU'], fn, 1, 'float')
    p = rt.construct(2, ((uv[0]) - (rt.f(0.5))), ((uv[1]) - (rt.f(0.5))))
    a = rt.component_wise('atan', rt.swizzle(p, 'y'), rt.swizzle(p, 'x'))
    r = rt.length(p)
    a = rt.component_wise('mod', rt.component_wise('mod', rt.binary('+', a, g['TAU'], 1, 'float'), g['TAU']), sectorAngle)
    if rt.bool(rt.binary('>', a, rt.binary('*', sectorAngle, rt.f(0.5), 1, 'float')))
      a = rt.binary('-', sectorAngle, a, 1, 'float')
    end
    return rt.construct(2, (((((r) * (rt.component_wise('cos', a))))) + (rt.f(0.5))), (((((r) * (rt.component_wise('sin', a))))) + (rt.f(0.5))))
  end
  main__void = lambda do
    __sc1544 = nil; aspect = nil; effectiveScale = nil; globalCoord = nil; globalUV = nil; local = nil; localUV = nil; rep = nil; st = nil
    globalCoord = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0])), ((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1])))
    globalUV = rt.construct(2, ((globalCoord[0]) / (_u_fullResolution[0])), ((globalCoord[1]) / (_u_fullResolution[1])))
    aspect = rt.binary('/', rt.swizzle(_u_fullResolution, 'x'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')
    st = rt.construct(2, ((globalUV[0]) - (rt.f(0.5))), ((globalUV[1]) - (rt.f(0.5))))
    if rt.bool(_u_aspectLens)
      st = rt.assign_swizzle(st, 'x', rt.binary('*', rt.swizzle(st, 'x'), aspect, 1, 'float'))
    end
    st.replace((rot__vec2_float.call(st, rt.binary('/', rt.binary('*', _u_angle, g['PI'], 1, 'float'), rt.f(180), 1, 'float'))).map { |c| rt.f32(c) })
    if rt.bool(_u_aspectLens)
      st = rt.assign_swizzle(st, 'x', rt.binary('/', rt.swizzle(st, 'x'), aspect, 1, 'float'))
    end
    __sc1544 = rt.f(0.5); st[0] = rt.f32(rt.binary('+', st[0], __sc1544, 1, 'float')); st[1] = rt.f32(rt.binary('+', st[1], __sc1544, 1, 'float'))
    rep = rt.construct(2, (rt.bool(_u_aspectLens) ? ((((_u_repeat) * (aspect)))) : ((_u_repeat))), (rt.bool(_u_aspectLens) ? ((_u_repeat)) : ((_u_repeat))))
    effectiveScale = rt.f(0.0)
    local = rt.construct(2, 0.0)
    if rt.bool(rt.binary('==', _u_symmetry, rt.i(3)))
      local = rt.construct(2, hexCoord__vec2.call(rt.construct(2, ((((st[0]) + ((_u_offsetX)))) * (rep[0])), ((((st[1]) + ((_u_offsetY)))) * (rep[1])))))
      local.replace((rt.binary('/', local, _u_scale, 2, 'float')).map { |c| rt.f32(c) })
      st.replace((rotationalFold__vec2_int.call(rt.construct(2, ((local[0]) + (rt.f(0.5))), ((local[1]) + (rt.f(0.5)))), rt.i(6))).map { |c| rt.f32(c) })
    else
      st.replace((rt.binary('*', st, rep, 2, 'float')).map { |c| rt.f32(c) })
      st.replace((rt.component_wise('fract', st)).map { |c| rt.f32(c) })
      effectiveScale = (rt.bool(rt.binary('==', _u_symmetry, rt.i(0))) ? (rt.binary('*', _u_scale, rt.f(0.5), 1, 'float')) : (_u_scale))
      st.replace((rt.binary('/', rt.binary('-', st, rt.f(0.5), 2, 'float'), effectiveScale, 2, 'float')).map { |c| rt.f32(c) })
      st[0] = rt.f32(rt.binary('+', st[0], ((rt.f(0.5)) + ((_u_offsetX))), 1, 'float')); st[1] = rt.f32(rt.binary('+', st[1], ((rt.f(0.5)) + ((_u_offsetY))), 1, 'float'))
      if rt.bool(rt.binary('==', _u_symmetry, rt.i(0)))
        st = rt.assign_swizzle(st, 'x', mirrorFold__float.call(rt.swizzle(st, 'x')))
        st = rt.assign_swizzle(st, 'y', mirrorFold__float.call(rt.swizzle(st, 'y')))
      else
        if rt.bool(rt.binary('==', _u_symmetry, rt.i(1)))
          st.replace((rotationalFold__vec2_int.call(rt.component_wise('fract', st), rt.i(2))).map { |c| rt.f32(c) })
        else
          st.replace((rotationalFold__vec2_int.call(rt.component_wise('fract', st), rt.i(4))).map { |c| rt.f32(c) })
        end
      end
    end
    localUV = rt.construct(2, rt.component_wise('fract', st[0]), rt.component_wise('fract', st[1]))
    g['fragColor'].replace((rt.construct(4, rt.swizzle(rt.texture(_u_inputTex, localUV), 'rgb'), rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
