# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  rotate2D__float = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_rotation = u.key?('rotation') ? u['rotation'] : rt.f(0.0)
  _u_wrap = u.key?('wrap') ? u['wrap'] : 0
  _u_speed = u.key?('speed') ? u['speed'] : 0
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['TAU'] = rt.f(6.2831854820251465)
  rotate2D__float = lambda do |angle|
    c = nil; s = nil
    c = rt.component_wise('cos', angle)
    s = rt.component_wise('sin', angle)
    return rt.construct(4, c, rt.unary('-', s), s, c)
  end
  main__void = lambda do
    angle = nil; aspect = nil; center = nil; texSize = nil; uv = nil
    texSize = rt.texture_size(_u_inputTex)
    uv = rt.construct(2, rt.binary_raw('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct_raw(2, rt.construct(2, texSize)), 2, 'float'))
    angle = _u_rotation
    if rt.bool(rt.binary('!=', _u_speed, rt.i(0)))
      angle = rt.binary('+', angle, rt.binary('*', rt.binary('*', _u_time, rt.f(360), 1, 'float'), rt.construct(1, _u_speed), 1, 'float'), 1, 'float')
    end
    aspect = rt.binary('/', rt.construct(1, rt.swizzle(texSize, 'x')), rt.construct(1, rt.swizzle(texSize, 'y')), 1, 'float')
    center = rt.construct(2, rt.f(0.5))
    uv[0] = rt.f32(rt.binary('-', uv[0], center[0], 1, 'float')); uv[1] = rt.f32(rt.binary('-', uv[1], center[1], 1, 'float'))
    uv = rt.assign_swizzle(uv, 'x', rt.binary_raw('*', rt.swizzle(uv, 'x'), aspect, 1, 'float'))
    rt.matrix_mult_assign(uv, rotate2D__float.call(rt.binary('/', rt.binary('*', rt.unary('-', angle), g['TAU'], 1, 'float'), rt.f(360), 1, 'float')), uv, 2)
    uv = rt.assign_swizzle(uv, 'x', rt.binary_raw('/', rt.swizzle(uv, 'x'), aspect, 1, 'float'))
    uv[0] = rt.f32(rt.binary('+', uv[0], center[0], 1, 'float')); uv[1] = rt.f32(rt.binary('+', uv[1], center[1], 1, 'float'))
    if rt.bool(rt.binary('==', _u_wrap, rt.i(0)))
      uv.replace((rt.component_wise('abs', rt.construct(2, rt.f32(((rt.component_wise('mod', rt.f32(((uv[0]) + (rt.f(1)))), rt.f(2))) - (rt.f(1)))), rt.f32(((rt.component_wise('mod', rt.f32(((uv[1]) + (rt.f(1)))), rt.f(2))) - (rt.f(1))))))).map { |c| rt.f32(c) })
    else
      if rt.bool(rt.binary('==', _u_wrap, rt.i(1)))
        uv.replace((rt.component_wise('fract', uv)).map { |c| rt.f32(c) })
      else
        uv.replace((rt.component_wise('clamp', uv, rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
      end
    end
    g['fragColor'].replace((rt.texture(_u_inputTex, uv)).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
