# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  main__void = nil
  _retc = nil
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_radius = u.key?('radius') ? u['radius'] : rt.f(0.0)
  _u_renderScale = u.key?('renderScale') ? u['renderScale'] : rt.f(0.0)
  _u_taps = u.key?('taps') ? u['taps'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  g['MAX_TAPS'] = rt.i(64)
  g['GOLDEN_ANGLE'] = rt.f(2.39996323)
  g['PI'] = rt.f(3.1415926535900001)
  main__void = lambda do
    _for0_first = nil; _t = nil; bloomAccum = nil; globalCoord = nil; i = nil; offset = nil; r = nil; radiusUV = nil; sampleColor = nil; sampleUV = nil; sigma = nil; tapCount = nil; texSize = nil; texelSize = nil; theta = nil; uv = nil; weight = nil; weightSum = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    texSize = rt.construct(2, rt.construct(2, rt.texture_size(_u_inputTex)))
    uv = rt.construct(2, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), texSize, 2, 'float'))
    texelSize = rt.construct(2, rt.binary('/', rt.f(1), texSize, 2, 'float'))
    radiusUV = rt.construct(2, rt.binary('*', rt.binary('*', _u_radius, _u_renderScale, 1, 'float'), texelSize, 2, 'float'))
    tapCount = rt.component_wise('clamp', _u_taps, rt.i(1), g['MAX_TAPS'])
    bloomAccum = rt.construct(3, rt.construct(3, rt.f(0)))
    weightSum = rt.f(0)
    i = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', i, g['MAX_TAPS']))
        break
      end
      if rt.bool(rt.binary('>=', i, tapCount))
        break
      end
      _t = rt.binary('/', rt.construct(1, i), rt.construct(1, tapCount), 1, 'float')
      r = rt.component_wise('sqrt', _t)
      theta = rt.binary('*', rt.construct(1, i), g['GOLDEN_ANGLE'], 1, 'float')
      offset = rt.construct(2, rt.binary('*', rt.construct(2, rt.component_wise('cos', theta), rt.component_wise('sin', theta)), r, 2, 'float'))
      sigma = rt.f(0.40000000000000002)
      weight = rt.component_wise('exp', rt.binary('/', rt.binary('*', rt.unary('-', rt.f(0.5)), rt.binary('*', r, r, 1, 'float'), 1, 'float'), rt.binary('*', sigma, sigma, 1, 'float'), 1, 'float'))
      sampleUV = rt.construct(2, rt.component_wise('clamp', rt.binary('+', uv, rt.binary('*', offset, radiusUV, 2, 'float'), 2, 'float'), rt.construct(2, rt.f(0)), rt.construct(2, rt.f(1))))
      sampleColor = rt.construct(3, rt.swizzle(rt.texture(_u_inputTex, sampleUV), 'rgb'))
      bloomAccum.replace((rt.binary('+', bloomAccum, rt.binary('*', sampleColor, weight, 3, 'float'), 3, 'float')).map { |c| rt.f32(c) })
      weightSum = rt.binary('+', weightSum, weight, 1, 'float')
    end
    if rt.bool(rt.binary('>', weightSum, rt.f(0)))
      bloomAccum.replace((rt.binary('/', bloomAccum, weightSum, 3, 'float')).map { |c| rt.f32(c) })
    end
    g['fragColor'].replace((rt.construct(4, bloomAccum, rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
