# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  polygonShape__vec2_int = smod__vec2_float = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_shape = u.key?('shape') ? u['shape'] : 0
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_rotation = u.key?('rotation') ? u['rotation'] : rt.f(0.0)
  _u_scale = u.key?('scale') ? u['scale'] : rt.f(0.0)
  _u_center = u.key?('center') ? u['center'] : rt.f(0.0)
  _u_aspectLens = u.key?('aspectLens') ? u['aspectLens'] : 0
  _u_antialias = u.key?('antialias') ? u['antialias'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  g['PI'] = rt.f(3.1415927410125732)
  g['TAU'] = rt.f(6.2831854820251465)
  polygonShape__vec2_int = lambda do |uv, sides|
    uv = rt.copy(uv, 'float')
    a = nil; r = nil
    a = rt.binary('+', rt.component_wise('atan', rt.swizzle(uv, 'x'), rt.swizzle(uv, 'y')), g['PI'], 1, 'float')
    r = rt.binary('/', g['TAU'], rt.construct(1, sides), 1, 'float')
    return rt.binary('*', rt.component_wise('cos', rt.binary('-', rt.binary('*', rt.component_wise('floor', rt.binary('+', rt.f(0.5), rt.binary('/', a, r, 1, 'float'), 1, 'float')), r, 1, 'float'), a, 1, 'float')), rt.length(uv), 1, 'float')
  end
  smod__vec2_float = lambda do |v, m|
    v = rt.copy(v, 'float')
    return rt.binary('*', m, rt.binary('-', rt.binary('-', rt.f(0.75), rt.component_wise('abs', rt.construct(2, rt.f32(((rt.component_wise('fract', v[0])) - (rt.f(0.5)))), rt.f32(((rt.component_wise('fract', v[1])) - (rt.f(0.5)))))), 2, 'float'), rt.f(0.25), 2, 'float'), 2, 'float')
  end
  main__void = lambda do
    __hoistv1 = nil; __hoistv2 = nil; __hoistv3 = nil; __hoistv4 = nil; __sc5 = nil; a = nil; amt = nil; aspectRatio = nil; centerMask = nil; centered = nil; color = nil; dx = nil; dy = nil; fullRes = nil; p = nil; r = nil; texSize = nil; tileDims = nil; tunnelCoords = nil; uv = nil
    texSize = rt.texture_size(_u_inputTex)
    tileDims = rt.construct(2, rt.construct(2, texSize))
    fullRes = rt.construct(2, (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[0]) : (tileDims[0])), (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[1]) : (tileDims[1])))
    uv = rt.construct(2, ((((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0]))) / (fullRes[0])), ((((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1]))) / (fullRes[1])))
    centered = rt.construct(2, ((uv[0]) - (rt.f(0.5))), ((uv[1]) - (rt.f(0.5))))
    aspectRatio = rt.binary('/', rt.swizzle(fullRes, 'x'), rt.swizzle(fullRes, 'y'), 1, 'float')
    if rt.bool(_u_aspectLens)
      centered = rt.assign_swizzle(centered, 'x', rt.binary('*', rt.swizzle(centered, 'x'), aspectRatio, 1, 'float'))
    end
    a = rt.component_wise('atan', rt.swizzle(centered, 'y'), rt.swizzle(centered, 'x'))
    r = rt.f(0.0)
    p = rt.construct(2, 0.0)
    if rt.bool(rt.binary('==', _u_shape, rt.i(0)))
      r = rt.length(centered)
    else
      if rt.bool(rt.binary('==', _u_shape, rt.i(1)))
        r = polygonShape__vec2_int.call(rt.construct(2, ((centered[0]) * (rt.f(2))), ((centered[1]) * (rt.f(2)))), rt.i(3))
      else
        if rt.bool(rt.binary('==', _u_shape, rt.i(2)))
          p = rt.construct(2, ((((((((((((((centered[0]) * (centered[0]))) * (centered[0]))) * (centered[0]))) * (centered[0]))) * (centered[0]))) * (centered[0]))) * (centered[0])), ((((((((((((((centered[1]) * (centered[1]))) * (centered[1]))) * (centered[1]))) * (centered[1]))) * (centered[1]))) * (centered[1]))) * (centered[1])))
          r = rt.component_wise('pow', rt.binary('+', rt.swizzle(p, 'x'), rt.swizzle(p, 'y'), 1, 'float'), rt.f(0.125))
        else
          if rt.bool(rt.binary('==', _u_shape, rt.i(3)))
            r = polygonShape__vec2_int.call(rt.construct(2, ((centered[0]) * (rt.f(2))), ((centered[1]) * (rt.f(2)))), rt.i(4))
          else
            if rt.bool(rt.binary('==', _u_shape, rt.i(4)))
              r = polygonShape__vec2_int.call(rt.construct(2, ((centered[0]) * (rt.f(2))), ((centered[1]) * (rt.f(2)))), rt.i(6))
            else
              r = polygonShape__vec2_int.call(rt.construct(2, ((centered[0]) * (rt.f(2))), ((centered[1]) * (rt.f(2)))), rt.i(8))
            end
          end
        end
      end
    end
    r = rt.binary('-', r, rt.binary('*', _u_scale, rt.f(0.15000000596046448), 1, 'float'), 1, 'float')
    tunnelCoords = rt.construct(2, smod__vec2_float.call(rt.construct(2, (((((rt.f(0.30000001192092896)) / (r))) + (((_u_time) * (_u_speed))))), (((((a) / (g['PI']))) + (((_u_time) * (_u_rotation)))))), rt.f(1)))
    color = rt.construct(4, 0.0)
    dx = rt.construct(2, 0.0)
    dy = rt.construct(2, 0.0)
    if rt.bool(_u_antialias)
      dx = rt.construct(2, rt.dFdx(tunnelCoords))
      dy = rt.construct(2, rt.dFdy(tunnelCoords))
      color.replace((rt.construct(4, rt.f(0))).map { |c| rt.f32(c) })
      __hoistv1 = rt.texture(_u_inputTex, rt.binary('+', rt.binary('+', tunnelCoords, rt.binary('*', dx, rt.unary('-', rt.f(0.375)), 2, 'float'), 2, 'float'), rt.binary('*', dy, rt.unary('-', rt.f(0.125)), 2, 'float'), 2, 'float')); color[0] = rt.f32(rt.binary('+', color[0], __hoistv1[0], 1, 'float')); color[1] = rt.f32(rt.binary('+', color[1], __hoistv1[1], 1, 'float')); color[2] = rt.f32(rt.binary('+', color[2], __hoistv1[2], 1, 'float')); color[3] = rt.f32(rt.binary('+', color[3], __hoistv1[3], 1, 'float'))
      __hoistv2 = rt.texture(_u_inputTex, rt.binary('+', rt.binary('+', tunnelCoords, rt.binary('*', dx, rt.f(0.125), 2, 'float'), 2, 'float'), rt.binary('*', dy, rt.unary('-', rt.f(0.375)), 2, 'float'), 2, 'float')); color[0] = rt.f32(rt.binary('+', color[0], __hoistv2[0], 1, 'float')); color[1] = rt.f32(rt.binary('+', color[1], __hoistv2[1], 1, 'float')); color[2] = rt.f32(rt.binary('+', color[2], __hoistv2[2], 1, 'float')); color[3] = rt.f32(rt.binary('+', color[3], __hoistv2[3], 1, 'float'))
      __hoistv3 = rt.texture(_u_inputTex, rt.binary('+', rt.binary('+', tunnelCoords, rt.binary('*', dx, rt.f(0.375), 2, 'float'), 2, 'float'), rt.binary('*', dy, rt.f(0.125), 2, 'float'), 2, 'float')); color[0] = rt.f32(rt.binary('+', color[0], __hoistv3[0], 1, 'float')); color[1] = rt.f32(rt.binary('+', color[1], __hoistv3[1], 1, 'float')); color[2] = rt.f32(rt.binary('+', color[2], __hoistv3[2], 1, 'float')); color[3] = rt.f32(rt.binary('+', color[3], __hoistv3[3], 1, 'float'))
      __hoistv4 = rt.texture(_u_inputTex, rt.binary('+', rt.binary('+', tunnelCoords, rt.binary('*', dx, rt.unary('-', rt.f(0.125)), 2, 'float'), 2, 'float'), rt.binary('*', dy, rt.f(0.375), 2, 'float'), 2, 'float')); color[0] = rt.f32(rt.binary('+', color[0], __hoistv4[0], 1, 'float')); color[1] = rt.f32(rt.binary('+', color[1], __hoistv4[1], 1, 'float')); color[2] = rt.f32(rt.binary('+', color[2], __hoistv4[2], 1, 'float')); color[3] = rt.f32(rt.binary('+', color[3], __hoistv4[3], 1, 'float'))
      __sc5 = rt.f(0.25); color[0] = rt.f32(rt.binary('*', color[0], __sc5, 1, 'float')); color[1] = rt.f32(rt.binary('*', color[1], __sc5, 1, 'float')); color[2] = rt.f32(rt.binary('*', color[2], __sc5, 1, 'float')); color[3] = rt.f32(rt.binary('*', color[3], __sc5, 1, 'float'))
    else
      color.replace((rt.texture(_u_inputTex, tunnelCoords)).map { |c| rt.f32(c) })
    end
    amt = rt.f(0.0)
    centerMask = rt.f(0.0)
    if rt.bool(rt.binary('!=', _u_center, rt.f(0)))
      centerMask = rt.component_wise('smoothstep', rt.f(0), rt.f(0.5), r)
      amt = rt.binary('/', _u_center, rt.f(100), 1, 'float')
      if rt.bool(rt.binary('<', amt, rt.f(0)))
        color = rt.assign_swizzle(color, 'rgb', rt.binary('*', rt.swizzle(color, 'rgb'), rt.component_wise('mix', rt.f(1), centerMask, rt.unary('-', amt)), 3, 'float'))
      else
        color = rt.assign_swizzle(color, 'rgb', rt.component_wise('mix', rt.swizzle(color, 'rgb'), rt.construct(3, rt.f(1)), rt.binary('*', rt.binary('-', rt.f(1), centerMask, 1, 'float'), amt, 1, 'float')))
      end
    end
    g['fragColor'].replace((color).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: true }
