# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  srgbToLinear__vec3 = linearToSrgb__vec3 = rgbToHsl__vec3 = hslToRgb__vec3 = computeHslKey__vec3_float_float_float_float_float_float_float = applyHslCorrection__vec3_float_float_float = main__void = nil
  _retc = nil
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_hslEnable = u.key?('hslEnable') ? u['hslEnable'] : 0
  _u_hslHueCenter = u.key?('hslHueCenter') ? u['hslHueCenter'] : rt.f(0.0)
  _u_hslHueRange = u.key?('hslHueRange') ? u['hslHueRange'] : rt.f(0.0)
  _u_hslSatMin = u.key?('hslSatMin') ? u['hslSatMin'] : rt.f(0.0)
  _u_hslSatMax = u.key?('hslSatMax') ? u['hslSatMax'] : rt.f(0.0)
  _u_hslLumMin = u.key?('hslLumMin') ? u['hslLumMin'] : rt.f(0.0)
  _u_hslLumMax = u.key?('hslLumMax') ? u['hslLumMax'] : rt.f(0.0)
  _u_hslFeather = u.key?('hslFeather') ? u['hslFeather'] : rt.f(0.0)
  _u_hslHueShift = u.key?('hslHueShift') ? u['hslHueShift'] : rt.f(0.0)
  _u_hslSatAdjust = u.key?('hslSatAdjust') ? u['hslSatAdjust'] : rt.f(0.0)
  _u_hslLumAdjust = u.key?('hslLumAdjust') ? u['hslLumAdjust'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['LUMA_WEIGHTS'] = rt.construct(3, rt.f(0.21260000000000001), rt.f(0.71519999999999995), rt.f(0.0722))
  g['PI'] = rt.f(3.1415926535900001)
  srgbToLinear__vec3 = lambda do |srgb|
    srgb = rt.copy(srgb, 'float')
    _for0_first = nil; i = nil; linear = nil
    linear = rt.construct(3, 0.0)
    i = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', i, rt.i(3)))
        break
      end
      if rt.bool(rt.binary('<=', srgb[(i).to_i], rt.f(0.04045)))
        linear[(i).to_i] = rt.binary('/', srgb[(i).to_i], rt.f(12.92), 1, 'float')
      else
        linear[(i).to_i] = rt.component_wise('pow', rt.binary('/', rt.binary('+', srgb[(i).to_i], rt.f(0.055), 1, 'float'), rt.f(1.0549999999999999), 1, 'float'), rt.f(2.3999999999999999))
      end
    end
    return linear
  end
  linearToSrgb__vec3 = lambda do |linear|
    linear = rt.copy(linear, 'float')
    _for1_first = nil; i = nil; srgb = nil
    srgb = rt.construct(3, 0.0)
    i = rt.i(0)
    _for1_first = true
    (0..1048575).each do |_for1|
      unless _for1_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for1_first = false
      unless rt.bool(rt.binary('<', i, rt.i(3)))
        break
      end
      if rt.bool(rt.binary('<=', linear[(i).to_i], rt.f(0.0031308)))
        srgb[(i).to_i] = rt.binary('*', linear[(i).to_i], rt.f(12.92), 1, 'float')
      else
        srgb[(i).to_i] = rt.binary('-', rt.binary('*', rt.f(1.0549999999999999), rt.component_wise('pow', linear[(i).to_i], rt.binary('/', rt.f(1), rt.f(2.3999999999999999), 1, 'float')), 1, 'float'), rt.f(0.055), 1, 'float')
      end
    end
    return srgb
  end
  rgbToHsl__vec3 = lambda do |rgb|
    rgb = rt.copy(rgb, 'float')
    delta = nil; h = nil; l = nil; maxC = nil; minC = nil; s = nil
    maxC = rt.component_wise('max', rt.component_wise('max', rt.swizzle(rgb, 'r'), rt.swizzle(rgb, 'g')), rt.swizzle(rgb, 'b'))
    minC = rt.component_wise('min', rt.component_wise('min', rt.swizzle(rgb, 'r'), rt.swizzle(rgb, 'g')), rt.swizzle(rgb, 'b'))
    delta = rt.binary('-', maxC, minC, 1, 'float')
    l = rt.binary('*', rt.binary('+', maxC, minC, 1, 'float'), rt.f(0.5), 1, 'float')
    h = rt.f(0)
    s = rt.f(0)
    if rt.bool(rt.binary('>', delta, rt.f(0.001)))
      s = (rt.bool(rt.binary('>', l, rt.f(0.5))) ? (rt.binary('/', delta, rt.binary('-', rt.binary('-', rt.f(2), maxC, 1, 'float'), minC, 1, 'float'), 1, 'float')) : (rt.binary('/', delta, rt.binary('+', maxC, minC, 1, 'float'), 1, 'float')))
      if rt.bool(rt.binary('==', maxC, rt.swizzle(rgb, 'r')))
        h = rt.binary('+', rt.binary('/', rt.binary('-', rt.swizzle(rgb, 'g'), rt.swizzle(rgb, 'b'), 1, 'float'), delta, 1, 'float'), (rt.bool(rt.binary('<', rt.swizzle(rgb, 'g'), rt.swizzle(rgb, 'b'))) ? (rt.f(6)) : (rt.f(0))), 1, 'float')
      else
        if rt.bool(rt.binary('==', maxC, rt.swizzle(rgb, 'g')))
          h = rt.binary('+', rt.binary('/', rt.binary('-', rt.swizzle(rgb, 'b'), rt.swizzle(rgb, 'r'), 1, 'float'), delta, 1, 'float'), rt.f(2), 1, 'float')
        else
          h = rt.binary('+', rt.binary('/', rt.binary('-', rt.swizzle(rgb, 'r'), rt.swizzle(rgb, 'g'), 1, 'float'), delta, 1, 'float'), rt.f(4), 1, 'float')
        end
      end
      h = rt.binary('/', h, rt.f(6), 1, 'float')
    end
    return rt.construct(3, h, s, l)
  end
  hslToRgb__vec3 = lambda do |hsl|
    hsl = rt.copy(hsl, 'float')
    _for2_first = nil; _t = nil; h = nil; i = nil; l = nil; p = nil; q = nil; rgb = nil; s = nil
    h = rt.swizzle(hsl, 'x')
    s = rt.swizzle(hsl, 'y')
    l = rt.swizzle(hsl, 'z')
    if rt.bool(rt.binary('<', s, rt.f(0.001)))
      return rt.construct(3, l)
    end
    q = (rt.bool(rt.binary('<', l, rt.f(0.5))) ? (rt.binary('*', l, rt.binary('+', rt.f(1), s, 1, 'float'), 1, 'float')) : (rt.binary('-', rt.binary('+', l, s, 1, 'float'), rt.binary('*', l, s, 1, 'float'), 1, 'float')))
    p = rt.binary('-', rt.binary('*', rt.f(2), l, 1, 'float'), q, 1, 'float')
    rgb = rt.construct(3, 0.0)
    i = rt.i(0)
    _for2_first = true
    (0..1048575).each do |_for2|
      unless _for2_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for2_first = false
      unless rt.bool(rt.binary('<', i, rt.i(3)))
        break
      end
      _t = rt.binary('+', h, rt.binary('/', rt.binary('-', rt.f(1), rt.construct(1, i), 1, 'float'), rt.f(3), 1, 'float'), 1, 'float')
      _t = rt.component_wise('fract', _t)
      if rt.bool(rt.binary('<', _t, rt.binary('/', rt.f(1), rt.f(6), 1, 'float')))
        rgb[(i).to_i] = rt.binary('+', p, rt.binary('*', rt.binary('*', rt.binary('-', q, p, 1, 'float'), rt.f(6), 1, 'float'), _t, 1, 'float'), 1, 'float')
      else
        if rt.bool(rt.binary('<', _t, rt.f(0.5)))
          rgb[(i).to_i] = q
        else
          if rt.bool(rt.binary('<', _t, rt.binary('/', rt.f(2), rt.f(3), 1, 'float')))
            rgb[(i).to_i] = rt.binary('+', p, rt.binary('*', rt.binary('*', rt.binary('-', q, p, 1, 'float'), rt.binary('-', rt.binary('/', rt.f(2), rt.f(3), 1, 'float'), _t, 1, 'float'), 1, 'float'), rt.f(6), 1, 'float'), 1, 'float')
          else
            rgb[(i).to_i] = p
          end
        end
      end
    end
    return rgb
  end
  computeHslKey__vec3_float_float_float_float_float_float_float = lambda do |hsl, hueCenter, hueRange, satMin, satMax, lumMin, lumMax, feather|
    hsl = rt.copy(hsl, 'float')
    hueDist = nil; hueKey = nil; lumKey = nil; satKey = nil
    hueDist = rt.component_wise('abs', rt.binary('-', rt.swizzle(hsl, 'x'), hueCenter, 1, 'float'))
    hueDist = rt.component_wise('min', hueDist, rt.binary('-', rt.f(1), hueDist, 1, 'float'))
    hueKey = rt.binary('-', rt.f(1), rt.component_wise('smoothstep', rt.binary('-', hueRange, feather, 1, 'float'), rt.binary('+', hueRange, feather, 1, 'float'), hueDist), 1, 'float')
    satKey = rt.binary('*', rt.component_wise('smoothstep', rt.binary('-', satMin, feather, 1, 'float'), rt.binary('+', satMin, feather, 1, 'float'), rt.swizzle(hsl, 'y')), rt.binary('-', rt.f(1), rt.component_wise('smoothstep', rt.binary('-', satMax, feather, 1, 'float'), rt.binary('+', satMax, feather, 1, 'float'), rt.swizzle(hsl, 'y')), 1, 'float'), 1, 'float')
    lumKey = rt.binary('*', rt.component_wise('smoothstep', rt.binary('-', lumMin, feather, 1, 'float'), rt.binary('+', lumMin, feather, 1, 'float'), rt.swizzle(hsl, 'z')), rt.binary('-', rt.f(1), rt.component_wise('smoothstep', rt.binary('-', lumMax, feather, 1, 'float'), rt.binary('+', lumMax, feather, 1, 'float'), rt.swizzle(hsl, 'z')), 1, 'float'), 1, 'float')
    return rt.binary('*', rt.binary('*', hueKey, satKey, 1, 'float'), lumKey, 1, 'float')
  end
  applyHslCorrection__vec3_float_float_float = lambda do |hsl, hueShift, satAdjust, lumAdjust|
    hsl = rt.copy(hsl, 'float')
    corrected = nil
    corrected = hsl
    corrected = rt.assign_swizzle(corrected, 'x', rt.component_wise('fract', rt.binary('+', rt.swizzle(corrected, 'x'), hueShift, 1, 'float')))
    corrected = rt.assign_swizzle(corrected, 'y', rt.component_wise('clamp', rt.binary('+', rt.swizzle(corrected, 'y'), satAdjust, 1, 'float'), rt.f(0), rt.f(1)))
    corrected = rt.assign_swizzle(corrected, 'z', rt.component_wise('clamp', rt.binary('+', rt.swizzle(corrected, 'z'), rt.binary('*', lumAdjust, rt.f(0.5), 1, 'float'), 1, 'float'), rt.f(0), rt.f(1)))
    return corrected
  end
  main__void = lambda do
    color = nil; coord = nil; correctedHsl = nil; correctedRgb = nil; globalCoord = nil; hsl = nil; matte = nil; rgb = nil
    globalCoord = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
    coord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy'), 'int')
    color = rt.texel_fetch(_u_inputTex, coord, rt.i(0))
    if rt.bool(rt.binary('==', _u_hslEnable, rt.i(0)))
      g['fragColor'].replace((color).map { |c| rt.f32(c) })
      return
    end
    rgb = srgbToLinear__vec3.call(rt.swizzle(color, 'rgb'))
    hsl = rgbToHsl__vec3.call(rgb)
    matte = computeHslKey__vec3_float_float_float_float_float_float_float.call(hsl, _u_hslHueCenter, _u_hslHueRange, _u_hslSatMin, _u_hslSatMax, _u_hslLumMin, _u_hslLumMax, _u_hslFeather)
    correctedHsl = applyHslCorrection__vec3_float_float_float.call(hsl, _u_hslHueShift, _u_hslSatAdjust, _u_hslLumAdjust)
    correctedRgb = hslToRgb__vec3.call(correctedHsl)
    rgb.replace((rt.component_wise('mix', rgb, correctedRgb, matte)).map { |c| rt.f32(c) })
    rgb.replace((linearToSrgb__vec3.call(rt.component_wise('max', rgb, rt.construct(3, rt.f(0))))).map { |c| rt.f32(c) })
    g['fragColor'].replace((rt.construct(4, rgb, rt.swizzle(color, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
