# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  computeVignetteMask__vec2_vec2 = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_vignetteBrightness = u.key?('vignetteBrightness') ? u['vignetteBrightness'] : rt.f(0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  computeVignetteMask__vec2_vec2 = lambda do |uv, dims|
    uv = rt.copy(uv, 'float')
    dims = rt.copy(dims, 'float')
    aspect = nil; delta = nil; maxRadius = nil; normalizedDist = nil; scaled = nil
    if rt.bool((rt.bool(rt.binary('<=', rt.swizzle(dims, 'x'), rt.f(0))) || rt.bool(rt.binary('<=', rt.swizzle(dims, 'y'), rt.f(0))) ? 1 : 0))
      return rt.f(0)
    end
    delta = rt.construct(2, rt.component_wise('abs', rt.f32(((uv[0]) - ((rt.f(0.5)))))), rt.component_wise('abs', rt.f32(((uv[1]) - ((rt.f(0.5)))))))
    aspect = rt.binary('/', rt.swizzle(dims, 'x'), rt.component_wise('max', rt.swizzle(dims, 'y'), rt.f(1)), 1, 'float')
    scaled = rt.construct(2, rt.construct(2, rt.binary('*', rt.swizzle(delta, 'x'), aspect, 1, 'float'), rt.swizzle(delta, 'y')))
    maxRadius = rt.length(rt.construct(2, rt.binary('*', aspect, rt.f(0.5), 1, 'float'), rt.f(0.5)))
    if rt.bool(rt.binary('<=', maxRadius, rt.f(0)))
      return rt.f(0)
    end
    normalizedDist = rt.component_wise('clamp', rt.binary('/', rt.length(scaled), maxRadius, 1, 'float'), rt.f(0), rt.f(1))
    return rt.binary('*', normalizedDist, normalizedDist, 1, 'float')
  end
  main__void = lambda do
    brightnessRgb = nil; dims = nil; edgeBlend = nil; finalRgb = nil; globalCoord = nil; globalUV = nil; mask = nil; texSize = nil; texel = nil; tileDims = nil; uv = nil
    globalCoord = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0])), ((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1])))
    texSize = rt.texture_size(_u_inputTex)
    tileDims = rt.construct(2, rt.construct(2, texSize))
    dims = rt.construct(2, (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[0]) : (tileDims[0])), (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[1]) : (tileDims[1])))
    uv = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) / (tileDims[0])), ((rt.swizzle(ctx.frag_coord, 'y')) / (tileDims[1])))
    globalUV = rt.construct(2, ((((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0]))) / (dims[0])), ((((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1]))) / (dims[1])))
    texel = rt.construct(4, (rt.texture(_u_inputTex, uv))[0], (rt.texture(_u_inputTex, uv))[1], (rt.texture(_u_inputTex, uv))[2], (rt.texture(_u_inputTex, uv))[3])
    mask = computeVignetteMask__vec2_vec2.call(globalUV, dims)
    brightnessRgb = rt.construct(3, rt.construct(3, _u_vignetteBrightness))
    edgeBlend = rt.construct(3, rt.component_wise('mix', rt.swizzle(texel, 'r'), brightnessRgb[0], mask), rt.component_wise('mix', rt.swizzle(texel, 'g'), brightnessRgb[1], mask), rt.component_wise('mix', rt.swizzle(texel, 'b'), brightnessRgb[2], mask))
    finalRgb = rt.construct(3, rt.component_wise('mix', rt.swizzle(texel, 'r'), edgeBlend[0], _u_alpha), rt.component_wise('mix', rt.swizzle(texel, 'g'), edgeBlend[1], _u_alpha), rt.component_wise('mix', rt.swizzle(texel, 'b'), edgeBlend[2], _u_alpha))
    g['fragColor'].replace((rt.construct(4, finalRgb, rt.swizzle(texel, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
