# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  pcg__uvec3 = hash__vec2 = glyphPixel__int_int_int = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_renderScale = u.key?('renderScale') ? u['renderScale'] : rt.f(0.0)
  _u_cellSize = u.key?('cellSize') ? u['cellSize'] : 0
  _u_seed = u.key?('seed') ? u['seed'] : 0
  _u_colorMode = u.key?('colorMode') ? u['colorMode'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  g['GLYPH_COUNT'] = rt.i(16)
  pcg__uvec3 = lambda do |v|
    v = rt.copy(v, 'uint')
    v.replace(rt.binary('+', rt.binary('*', v, rt.i(1664525), 3, 'uint'), rt.i(1013904223), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    v.replace(rt.binary('^', v, rt.binary('>>', v, rt.i(16), 3, 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    return v
  end
  hash__vec2 = lambda do |p|
    p = rt.copy(p, 'float')
    v = nil
    v = pcg__uvec3.call(rt.construct(3, rt.construct(1, (rt.bool(rt.binary('>=', rt.swizzle(p, 'x'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'x'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'x')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))), 'uint'), rt.construct(1, (rt.bool(rt.binary('>=', rt.swizzle(p, 'y'), rt.f(0))) ? (rt.binary('*', rt.swizzle(p, 'y'), rt.f(2), 1, 'float')) : (rt.binary('+', rt.binary('*', rt.unary('-', rt.swizzle(p, 'y')), rt.f(2), 1, 'float'), rt.f(1), 1, 'float'))), 'uint'), rt.i(0), 'uint'))
    return rt.binary('/', rt.construct(1, rt.swizzle(v, 'x')), rt.construct(1, rt.i(4294967295)), 1, 'float')
  end
  glyphPixel__int_int_int = lambda do |_g, x, y|
    bit = nil; row = nil
    row = rt.i(0)
    if rt.bool(rt.binary('==', _g, rt.i(0)))
      return rt.f(0)
    else
      if rt.bool(rt.binary('==', _g, rt.i(1)))
        if rt.bool(rt.binary('==', y, rt.i(5)))
          row = rt.i(4)
        else
          return rt.f(0)
        end
      else
        if rt.bool(rt.binary('==', _g, rt.i(2)))
          if rt.bool((rt.bool(rt.binary('==', y, rt.i(1))) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
            row = rt.i(4)
          else
            return rt.f(0)
          end
        else
          if rt.bool(rt.binary('==', _g, rt.i(3)))
            if rt.bool(rt.binary('==', y, rt.i(3)))
              row = rt.i(14)
            else
              return rt.f(0)
            end
          else
            if rt.bool(rt.binary('==', _g, rt.i(4)))
              if rt.bool((rt.bool((rt.bool((rt.bool(rt.binary('==', y, rt.i(1))) || rt.bool(rt.binary('==', y, rt.i(2))) ? 1 : 0)) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0)) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                row = rt.i(4)
              else
                if rt.bool(rt.binary('==', y, rt.i(3)))
                  row = rt.i(14)
                else
                  return rt.f(0)
                end
              end
            else
              if rt.bool(rt.binary('==', _g, rt.i(5)))
                if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0))
                  row = rt.i(14)
                else
                  return rt.f(0)
                end
              else
                if rt.bool(rt.binary('==', _g, rt.i(6)))
                  if rt.bool((rt.bool(rt.binary('==', y, rt.i(1))) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                    row = rt.i(10)
                  else
                    if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0))
                      row = rt.i(4)
                    else
                      if rt.bool(rt.binary('==', y, rt.i(3)))
                        row = rt.i(14)
                      else
                        return rt.f(0)
                      end
                    end
                  end
                else
                  if rt.bool(rt.binary('==', _g, rt.i(7)))
                    if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                      row = rt.i(14)
                    else
                      if rt.bool((rt.bool(rt.binary('==', y, rt.i(3))) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0))
                        row = rt.i(10)
                      else
                        return rt.f(0)
                      end
                    end
                  else
                    if rt.bool(rt.binary('==', _g, rt.i(8)))
                      if rt.bool((rt.bool((rt.bool((rt.bool(rt.binary('==', y, rt.i(1))) || rt.bool(rt.binary('==', y, rt.i(2))) ? 1 : 0)) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0)) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                        row = rt.i(10)
                      else
                        if rt.bool(rt.binary('==', y, rt.i(3)))
                          row = rt.i(4)
                        else
                          return rt.f(0)
                        end
                      end
                    else
                      if rt.bool(rt.binary('==', _g, rt.i(9)))
                        if rt.bool((rt.bool((rt.bool(rt.binary('==', y, rt.i(1))) || rt.bool(rt.binary('==', y, rt.i(3))) ? 1 : 0)) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                          row = rt.i(10)
                        else
                          if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(4))) ? 1 : 0))
                            row = rt.i(31)
                          else
                            return rt.f(0)
                          end
                        end
                      else
                        if rt.bool(rt.binary('==', _g, rt.i(10)))
                          if rt.bool(rt.binary('==', y, rt.i(0)))
                            row = rt.i(25)
                          else
                            if rt.bool(rt.binary('==', y, rt.i(1)))
                              row = rt.i(26)
                            else
                              if rt.bool(rt.binary('==', y, rt.i(2)))
                                row = rt.i(4)
                              else
                                if rt.bool(rt.binary('==', y, rt.i(3)))
                                  row = rt.i(9)
                                else
                                  if rt.bool(rt.binary('==', y, rt.i(4)))
                                    row = rt.i(11)
                                  else
                                    if rt.bool(rt.binary('==', y, rt.i(5)))
                                      row = rt.i(19)
                                    else
                                      return rt.f(0)
                                    end
                                  end
                                end
                              end
                            end
                          end
                        else
                          if rt.bool(rt.binary('==', _g, rt.i(11)))
                            if rt.bool(rt.binary('==', y, rt.i(0)))
                              row = rt.i(4)
                            else
                              if rt.bool(rt.binary('==', y, rt.i(1)))
                                row = rt.i(10)
                              else
                                if rt.bool(rt.binary('==', y, rt.i(2)))
                                  row = rt.i(17)
                                else
                                  if rt.bool(rt.binary('==', y, rt.i(3)))
                                    row = rt.i(31)
                                  else
                                    if rt.bool((rt.bool(rt.binary('==', y, rt.i(4))) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                                      row = rt.i(17)
                                    else
                                      return rt.f(0)
                                    end
                                  end
                                end
                              end
                            end
                          else
                            if rt.bool(rt.binary('==', _g, rt.i(12)))
                              if rt.bool((rt.bool(rt.binary('==', y, rt.i(0))) || rt.bool(rt.binary('==', y, rt.i(1))) ? 1 : 0))
                                row = rt.i(17)
                              else
                                if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(3))) ? 1 : 0))
                                  row = rt.i(21)
                                else
                                  if rt.bool(rt.binary('==', y, rt.i(4)))
                                    row = rt.i(27)
                                  else
                                    if rt.bool(rt.binary('==', y, rt.i(5)))
                                      row = rt.i(10)
                                    else
                                      return rt.f(0)
                                    end
                                  end
                                end
                              end
                            else
                              if rt.bool(rt.binary('==', _g, rt.i(13)))
                                if rt.bool(rt.binary('==', y, rt.i(0)))
                                  row = rt.i(17)
                                else
                                  if rt.bool(rt.binary('==', y, rt.i(1)))
                                    row = rt.i(27)
                                  else
                                    if rt.bool((rt.bool(rt.binary('==', y, rt.i(2))) || rt.bool(rt.binary('==', y, rt.i(3))) ? 1 : 0))
                                      row = rt.i(21)
                                    else
                                      if rt.bool((rt.bool(rt.binary('==', y, rt.i(4))) || rt.bool(rt.binary('==', y, rt.i(5))) ? 1 : 0))
                                        row = rt.i(17)
                                      else
                                        return rt.f(0)
                                      end
                                    end
                                  end
                                end
                              else
                                if rt.bool(rt.binary('==', _g, rt.i(14)))
                                  if rt.bool((rt.bool(rt.binary('==', y, rt.i(0))) || rt.bool(rt.binary('==', y, rt.i(6))) ? 1 : 0))
                                    row = rt.i(14)
                                  else
                                    if rt.bool(rt.binary('==', y, rt.i(1)))
                                      row = rt.i(17)
                                    else
                                      if rt.bool(rt.binary('==', y, rt.i(2)))
                                        row = rt.i(23)
                                      else
                                        if rt.bool(rt.binary('==', y, rt.i(3)))
                                          row = rt.i(21)
                                        else
                                          if rt.bool(rt.binary('==', y, rt.i(4)))
                                            row = rt.i(22)
                                          else
                                            if rt.bool(rt.binary('==', y, rt.i(5)))
                                              row = rt.i(16)
                                            else
                                              return rt.f(0)
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                else
                                  return rt.f(1)
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    bit = rt.binary('&', rt.binary('>>', row, rt.binary('-', rt.i(4), x, 1, 'int'), 1, 'int'), rt.i(1), 1, 'int')
    return rt.construct(1, bit)
  end
  main__void = lambda do
    cellCenter = nil; cellHash = nil; cellIndex = nil; cs = nil; csf = nil; glyphIdx = nil; glyphVal = nil; gx = nil; gy = nil; isTileRendering = nil; localPos = nil; luma = nil; pixelCoord = nil; resolution = nil; sampleUV = nil; srcColor = nil; texSize = nil; variant = nil
    texSize = rt.texture_size(_u_inputTex)
    resolution = rt.construct(2, texSize)
    pixelCoord = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
    cs = rt.component_wise('max', rt.construct(1, rt.binary('*', rt.construct(1, _u_cellSize), _u_renderScale, 1, 'float'), 'int'), rt.i(1))
    isTileRendering = rt.binary('>', rt.length(_u_tileOffset), rt.f(0))
    if rt.bool(isTileRendering)
      cs = rt.component_wise('min', cs, rt.i(512))
    end
    csf = rt.construct(1, cs)
    cellIndex = rt.component_wise('floor', rt.binary('/', pixelCoord, csf, 2, 'float'))
    localPos = rt.component_wise('fract', rt.binary('/', pixelCoord, csf, 2, 'float'))
    gx = rt.construct(1, rt.component_wise('floor', rt.binary('*', rt.swizzle(localPos, 'x'), rt.f(5), 1, 'float')), 'int')
    gy = rt.construct(1, rt.component_wise('floor', rt.binary('*', rt.swizzle(localPos, 'y'), rt.f(7), 1, 'float')), 'int')
    gx = rt.component_wise('clamp', gx, rt.i(0), rt.i(4))
    gy = rt.component_wise('clamp', gy, rt.i(0), rt.i(6))
    cellCenter = rt.binary('*', rt.binary('+', cellIndex, rt.f(0.5), 2, 'float'), csf, 2, 'float')
    sampleUV = rt.binary('/', rt.binary('-', cellCenter, _u_tileOffset, 2, 'float'), resolution, 2, 'float')
    if rt.bool(isTileRendering)
      sampleUV.replace((rt.component_wise('clamp', sampleUV, rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
    end
    srcColor = rt.texture(_u_inputTex, sampleUV)
    luma = rt.dot(rt.swizzle(srcColor, 'rgb'), rt.construct(3, rt.f(0.29899999999999999), rt.f(0.58699999999999997), rt.f(0.114)))
    glyphIdx = rt.construct(1, rt.component_wise('floor', rt.binary('*', luma, rt.construct(1, g['GLYPH_COUNT']), 1, 'float')), 'int')
    glyphIdx = rt.component_wise('clamp', glyphIdx, rt.i(0), rt.binary('-', g['GLYPH_COUNT'], rt.i(1), 1, 'int'))
    cellHash = hash__vec2.call(rt.binary('+', cellIndex, rt.binary('*', rt.construct(1, _u_seed), rt.f(0.37), 1, 'float'), 2, 'float'))
    variant = rt.construct(1, rt.component_wise('floor', rt.binary('*', cellHash, rt.f(3), 1, 'float')), 'int')
    if rt.bool((rt.bool((rt.bool(rt.binary('==', variant, rt.i(1))) && rt.bool(rt.binary('>', glyphIdx, rt.i(0))) ? 1 : 0)) && rt.bool(rt.binary('<', glyphIdx, rt.binary('-', g['GLYPH_COUNT'], rt.i(1), 1, 'int'))) ? 1 : 0))
      glyphIdx = glyphIdx
    else
      if rt.bool((rt.bool(rt.binary('==', variant, rt.i(2))) && rt.bool(rt.binary('>', glyphIdx, rt.i(1))) ? 1 : 0))
        glyphIdx = rt.binary('-', glyphIdx, rt.i(1), 1, 'int')
      end
    end
    glyphVal = glyphPixel__int_int_int.call(glyphIdx, gx, gy)
    if rt.bool(rt.binary('>', _u_colorMode, rt.i(0)))
      g['fragColor'].replace((rt.construct(4, rt.binary('*', rt.swizzle(srcColor, 'rgb'), glyphVal, 3, 'float'), rt.f(1))).map { |c| rt.f32(c) })
    else
      g['fragColor'].replace((rt.construct(4, rt.construct(3, glyphVal), rt.f(1))).map { |c| rt.f32(c) })
    end
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
