# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  pcg3__uvec3 = pcg__uint = hashf__uint = gridVal__ivec2_uint = cubic__float_float_float_float_float = bicubicExpGrid__vec2_uint = bilinearExpGrid__vec2_uint = cosineExpGrid__vec2_uint = expFbm6Bicubic__vec2_vec2_uint = expFbm4Bilinear__vec2_vec2_uint = expRidgedFbm3Cosine__vec2_vec2_uint = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_color = u.key?('color') ? u['color'] : rt.construct(3, 0.0)
  _u_density = u.key?('density') ? u['density'] : rt.f(0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  pcg3__uvec3 = lambda do |v|
    v = rt.copy(v, 'uint')
    v.replace(rt.binary('+', rt.binary('*', v, rt.i(1664525), 3, 'uint'), rt.i(1013904223), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    v.replace(rt.binary('^', v, rt.binary('>>', v, rt.i(16), 3, 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    return v
  end
  pcg__uint = lambda do |v|
    return rt.swizzle(pcg3__uvec3.call(rt.construct(3, v, rt.i(0), rt.i(0), 'uint')), 'x')
  end
  hashf__uint = lambda do |h|
    return rt.binary('/', rt.construct(1, rt.swizzle(pcg3__uvec3.call(rt.construct(3, h, rt.i(0), rt.i(0), 'uint')), 'x')), rt.construct(1, rt.i(4294967295)), 1, 'float')
  end
  gridVal__ivec2_uint = lambda do |p, sd|
    p = rt.copy(p, 'int')
    h = nil
    h = pcg3__uvec3.call(rt.construct(3, rt.construct(1, rt.binary('+', rt.swizzle(p, 'x'), rt.i(32768), 1, 'int'), 'uint'), rt.construct(1, rt.binary('+', rt.swizzle(p, 'y'), rt.i(32768), 1, 'int'), 'uint'), sd, 'uint'))
    return rt.binary('/', rt.construct(1, rt.swizzle(h, 'x')), rt.construct(1, rt.i(4294967295)), 1, 'float')
  end
  cubic__float_float_float_float_float = lambda do |a, b, c, d, _t|
    t2 = nil; t3 = nil
    t2 = rt.binary('*', _t, _t, 1, 'float')
    t3 = rt.binary('*', t2, _t, 1, 'float')
    return rt.binary('*', rt.f(0.5), rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('*', rt.f(2), b, 1, 'float'), rt.binary('*', rt.binary('+', rt.unary('-', a), c, 1, 'float'), _t, 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('-', rt.binary('+', rt.binary('-', rt.binary('*', rt.f(2), a, 1, 'float'), rt.binary('*', rt.f(5), b, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(4), c, 1, 'float'), 1, 'float'), d, 1, 'float'), t2, 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('+', rt.binary('-', rt.binary('+', rt.unary('-', a), rt.binary('*', rt.f(3), b, 1, 'float'), 1, 'float'), rt.binary('*', rt.f(3), c, 1, 'float'), 1, 'float'), d, 1, 'float'), t3, 1, 'float'), 1, 'float'), 1, 'float')
  end
  bicubicExpGrid__vec2_uint = lambda do |pos, sd|
    pos = rt.copy(pos, 'float')
    c = nil; f = nil; r0 = nil; r1 = nil; r2 = nil; r3 = nil
    c = rt.construct(2, rt.construct(2, rt.component_wise('floor', pos)), 'int')
    f = rt.construct(2, rt.component_wise('fract', pos))
    r0 = cubic__float_float_float_float_float.call(rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.unary('-', rt.i(1)), rt.unary('-', rt.i(1)), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.unary('-', rt.i(1)), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.unary('-', rt.i(1)), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(2), rt.unary('-', rt.i(1)), 'int'), 2, 'int'), sd), rt.f(4)), rt.swizzle(f, 'x'))
    r1 = cubic__float_float_float_float_float.call(rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(2), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4)), rt.swizzle(f, 'x'))
    r2 = cubic__float_float_float_float_float.call(rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(2), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4)), rt.swizzle(f, 'x'))
    r3 = cubic__float_float_float_float_float.call(rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.unary('-', rt.i(1)), rt.i(2), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.i(2), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(2), 'int'), 2, 'int'), sd), rt.f(4)), rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(2), rt.i(2), 'int'), 2, 'int'), sd), rt.f(4)), rt.swizzle(f, 'x'))
    return rt.component_wise('clamp', cubic__float_float_float_float_float.call(r0, r1, r2, r3, rt.swizzle(f, 'y')), rt.f(0), rt.f(1))
  end
  bilinearExpGrid__vec2_uint = lambda do |pos, sd|
    pos = rt.copy(pos, 'float')
    c = nil; f = nil; v00 = nil; v01 = nil; v10 = nil; v11 = nil
    c = rt.construct(2, rt.construct(2, rt.component_wise('floor', pos)), 'int')
    f = rt.construct(2, rt.component_wise('fract', pos))
    v00 = rt.component_wise('pow', gridVal__ivec2_uint.call(c, sd), rt.f(4))
    v10 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4))
    v01 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4))
    v11 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4))
    return rt.component_wise('mix', rt.component_wise('mix', v00, v10, rt.swizzle(f, 'x')), rt.component_wise('mix', v01, v11, rt.swizzle(f, 'x')), rt.swizzle(f, 'y'))
  end
  cosineExpGrid__vec2_uint = lambda do |pos, sd|
    pos = rt.copy(pos, 'float')
    _t = nil; c = nil; f = nil; v00 = nil; v01 = nil; v10 = nil; v11 = nil
    c = rt.construct(2, rt.construct(2, rt.component_wise('floor', pos)), 'int')
    f = rt.construct(2, rt.component_wise('fract', pos))
    _t = rt.construct(2, rt.binary('*', rt.binary('-', rt.f(1), rt.component_wise('cos', rt.binary('*', f, rt.f(3.1415926500000002), 2, 'float')), 2, 'float'), rt.f(0.5), 2, 'float'))
    v00 = rt.component_wise('pow', gridVal__ivec2_uint.call(c, sd), rt.f(4))
    v10 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(0), 'int'), 2, 'int'), sd), rt.f(4))
    v01 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(0), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4))
    v11 = rt.component_wise('pow', gridVal__ivec2_uint.call(rt.binary('+', c, rt.construct(2, rt.i(1), rt.i(1), 'int'), 2, 'int'), sd), rt.f(4))
    return rt.component_wise('mix', rt.component_wise('mix', v00, v10, rt.swizzle(_t, 'x')), rt.component_wise('mix', v01, v11, rt.swizzle(_t, 'x')), rt.swizzle(_t, 'y'))
  end
  expFbm6Bicubic__vec2_vec2_uint = lambda do |uv, freq, sd|
    uv = rt.copy(uv, 'float')
    freq = rt.copy(freq, 'float')
    a = nil
    a = rt.f(0)
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', uv, freq, 2, 'float'), sd), rt.f(0.5), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(2), 2, 'float'), rt.binary('+', sd, rt.i(10000), 1, 'uint')), rt.f(0.25), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(4), 2, 'float'), rt.binary('+', sd, rt.i(20000), 1, 'uint')), rt.f(0.125), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(8), 2, 'float'), rt.binary('+', sd, rt.i(30000), 1, 'uint')), rt.f(0.0625), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(16), 2, 'float'), rt.binary('+', sd, rt.i(40000), 1, 'uint')), rt.f(0.03125), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bicubicExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(32), 2, 'float'), rt.binary('+', sd, rt.i(50000), 1, 'uint')), rt.f(0.015625), 1, 'float'), 1, 'float')
    return rt.binary('/', a, rt.f(0.984375), 1, 'float')
  end
  expFbm4Bilinear__vec2_vec2_uint = lambda do |uv, freq, sd|
    uv = rt.copy(uv, 'float')
    freq = rt.copy(freq, 'float')
    a = nil
    a = rt.f(0)
    a = rt.binary('+', a, rt.binary('*', bilinearExpGrid__vec2_uint.call(rt.binary('*', uv, freq, 2, 'float'), sd), rt.f(0.5), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bilinearExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(2), 2, 'float'), rt.binary('+', sd, rt.i(10000), 1, 'uint')), rt.f(0.25), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bilinearExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(4), 2, 'float'), rt.binary('+', sd, rt.i(20000), 1, 'uint')), rt.f(0.125), 1, 'float'), 1, 'float')
    a = rt.binary('+', a, rt.binary('*', bilinearExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(8), 2, 'float'), rt.binary('+', sd, rt.i(30000), 1, 'uint')), rt.f(0.0625), 1, 'float'), 1, 'float')
    return rt.binary('/', a, rt.f(0.9375), 1, 'float')
  end
  expRidgedFbm3Cosine__vec2_vec2_uint = lambda do |uv, freq, sd|
    uv = rt.copy(uv, 'float')
    freq = rt.copy(freq, 'float')
    a = nil; v = nil
    a = rt.f(0)
    v = rt.f(0.0)
    v = cosineExpGrid__vec2_uint.call(rt.binary('*', uv, freq, 2, 'float'), sd)
    a = rt.binary('+', a, rt.binary('*', rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', rt.f(2), v, 1, 'float'), rt.f(1), 1, 'float')), 1, 'float'), rt.f(0.5), 1, 'float'), 1, 'float')
    v = cosineExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(2), 2, 'float'), rt.binary('+', sd, rt.i(10000), 1, 'uint'))
    a = rt.binary('+', a, rt.binary('*', rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', rt.f(2), v, 1, 'float'), rt.f(1), 1, 'float')), 1, 'float'), rt.f(0.25), 1, 'float'), 1, 'float')
    v = cosineExpGrid__vec2_uint.call(rt.binary('*', rt.binary('*', uv, freq, 2, 'float'), rt.f(4), 2, 'float'), rt.binary('+', sd, rt.i(20000), 1, 'uint'))
    a = rt.binary('+', a, rt.binary('*', rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', rt.f(2), v, 1, 'float'), rt.f(1), 1, 'float')), 1, 'float'), rt.f(0.125), 1, 'float'), 1, 'float')
    return rt.binary('/', a, rt.f(0.875), 1, 'float')
  end
  main__void = lambda do
    aspect = nil; base = nil; colored = nil; combined = nil; dims = nil; disp = nil; dotFreq = nil; dots = nil; fullRes = nil; globalCoord = nil; globalUV = nil; mask = nil; nUV = nil; result = nil; ridge = nil; ridgeFreq = nil; s = nil; smear = nil; smearFreq = nil; speckFreq = nil; specks = nil; uv = nil; warpFreqX = nil; warpFreqY = nil; warpX = nil; warpY = nil; warpedUV = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    dims = rt.texture_size(_u_inputTex)
    uv = rt.construct(2, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, dims), 2, 'float'))
    base = rt.construct(4, rt.texture(_u_inputTex, uv))
    fullRes = rt.construct(2, (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution) : (rt.construct(2, dims))))
    globalUV = rt.construct(2, rt.binary('/', rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'), fullRes, 2, 'float'))
    aspect = rt.binary('/', rt.swizzle(fullRes, 'x'), rt.swizzle(fullRes, 'y'), 1, 'float')
    nUV = rt.construct(2, rt.binary('*', globalUV, rt.construct(2, aspect, rt.f(1)), 2, 'float'))
    s = rt.binary('*', rt.construct(1, _u_seed, 'uint'), rt.i(17), 1, 'uint')
    smearFreq = rt.component_wise('mix', rt.f(3), rt.f(6), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(10), 1, 'uint'))))
    dotFreq = rt.component_wise('mix', rt.f(32), rt.f(64), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(50), 1, 'uint'))))
    speckFreq = rt.component_wise('mix', rt.f(150), rt.f(200), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(90), 1, 'uint'))))
    ridgeFreq = rt.component_wise('mix', rt.f(2), rt.f(3), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(130), 1, 'uint'))))
    warpFreqX = rt.component_wise('mix', rt.f(2), rt.f(3), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(160), 1, 'uint'))))
    warpFreqY = rt.component_wise('mix', rt.f(1), rt.f(3), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(170), 1, 'uint'))))
    warpX = bilinearExpGrid__vec2_uint.call(rt.binary('*', nUV, rt.construct(2, warpFreqX, warpFreqY), 2, 'float'), rt.binary('+', s, rt.i(200), 1, 'uint'))
    warpY = bilinearExpGrid__vec2_uint.call(rt.binary('*', nUV, rt.construct(2, warpFreqX, warpFreqY), 2, 'float'), rt.binary('+', s, rt.i(300), 1, 'uint'))
    disp = rt.binary('+', rt.f(1), hashf__uint.call(pcg__uint.call(rt.binary('+', s, rt.i(150), 1, 'uint'))), 1, 'float')
    warpedUV = rt.construct(2, rt.binary('+', nUV, rt.binary('*', rt.binary('*', rt.binary('-', rt.construct(2, warpX, warpY), rt.f(0.5), 2, 'float'), disp, 2, 'float'), rt.f(0.12), 2, 'float'), 2, 'float'))
    smear = expFbm6Bicubic__vec2_vec2_uint.call(warpedUV, rt.construct(2, smearFreq), rt.binary('+', s, rt.i(100), 1, 'uint'))
    dots = expFbm4Bilinear__vec2_vec2_uint.call(nUV, rt.construct(2, dotFreq), rt.binary('+', s, rt.i(43), 1, 'uint'))
    dots = rt.component_wise('clamp', rt.binary('-', rt.binary('*', rt.f(4), dots, 1, 'float'), rt.f(1.6000000000000001), 1, 'float'), rt.f(0), rt.f(1))
    specks = expFbm4Bilinear__vec2_vec2_uint.call(nUV, rt.construct(2, speckFreq), rt.binary('+', s, rt.i(71), 1, 'uint'))
    specks = rt.component_wise('clamp', rt.binary('-', rt.binary('*', rt.f(4), specks, 1, 'float'), rt.f(2), 1, 'float'), rt.f(0), rt.f(1))
    combined = rt.component_wise('max', smear, rt.component_wise('max', dots, specks))
    ridge = expRidgedFbm3Cosine__vec2_vec2_uint.call(nUV, rt.construct(2, ridgeFreq), rt.binary('+', s, rt.i(89), 1, 'uint'))
    combined = rt.component_wise('max', rt.f(0), rt.binary('-', combined, ridge, 1, 'float'))
    combined = rt.binary('*', combined, rt.binary('+', rt.f(0.5), rt.binary('*', _u_density, rt.f(2), 1, 'float'), 1, 'float'), 1, 'float')
    mask = rt.component_wise('step', rt.f(0.5), combined)
    colored = rt.construct(3, rt.binary('*', rt.swizzle(base, 'rgb'), _u_color, 3, 'float'))
    result = rt.construct(3, rt.component_wise('mix', rt.swizzle(base, 'rgb'), rt.component_wise('mix', rt.swizzle(base, 'rgb'), colored, mask), _u_alpha))
    g['fragColor'].replace((rt.construct(4, result, rt.swizzle(base, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
