# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  luminance__vec3 = distance_metric__float_float_int = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  _u_sobelMetric = u.key?('sobelMetric') ? u['sobelMetric'] : rt.f(0.0)
  _u_width = u.key?('width') ? u['width'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  luminance__vec3 = lambda do |rgb|
    rgb = rt.copy(rgb, 'float')
    return rt.dot(rgb, rt.construct(3, rt.f(0.29899999499320984), rt.f(0.58700001239776611), rt.f(0.11400000005960464)))
  end
  distance_metric__float_float_int = lambda do |gx, gy, metric|
    abs_gx = nil; abs_gy = nil; cross = nil
    abs_gx = rt.component_wise('abs', gx)
    abs_gy = rt.component_wise('abs', gy)
    cross = rt.f(0.0)
    if rt.bool(rt.binary('==', metric, rt.i(1)))
      return rt.binary('+', abs_gx, abs_gy, 1, 'float')
    else
      if rt.bool(rt.binary('==', metric, rt.i(2)))
        return rt.component_wise('max', abs_gx, abs_gy)
      else
        if rt.bool(rt.binary('==', metric, rt.i(3)))
          cross = rt.binary('/', rt.binary('+', abs_gx, abs_gy, 1, 'float'), rt.f(1.4140000343322754), 1, 'float')
          return rt.component_wise('max', cross, rt.component_wise('max', abs_gx, abs_gy))
        end
      end
    end
    return rt.component_wise('sqrt', rt.binary('+', rt.binary('*', gx, gx, 1, 'float'), rt.binary('*', gy, gy, 1, 'float'), 1, 'float'))
  end
  main__void = lambda do
    base = nil; bc = nil; bl = nil; br = nil; edge = nil; globalCoord = nil; glow = nil; gx = nil; gy = nil; metric = nil; mixed = nil; ml = nil; mr = nil; result = nil; tc = nil; texel = nil; tl = nil; tr = nil; uv = nil
    globalCoord = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0])), ((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1])))
    uv = rt.construct(2, ((globalCoord[0]) / (_u_fullResolution[0])), ((globalCoord[1]) / (_u_fullResolution[1])))
    texel = rt.construct(2, ((_u_width) / (_u_resolution[0])), ((_u_width) / (_u_resolution[1])))
    base = rt.construct(4, (rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')))[0], (rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')))[1], (rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')))[2], (rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')))[3])
    tl = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.unary('-', rt.swizzle(texel, 'x')), rt.unary('-', rt.swizzle(texel, 'y'))), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    tc = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.f(0), rt.unary('-', rt.swizzle(texel, 'y'))), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    tr = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.unary('-', rt.swizzle(texel, 'y'))), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    ml = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.unary('-', rt.swizzle(texel, 'x')), rt.f(0)), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    mr = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.f(0)), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    bl = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.unary('-', rt.swizzle(texel, 'x')), rt.swizzle(texel, 'y')), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    bc = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.f(0), rt.swizzle(texel, 'y')), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    br = luminance__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('/', rt.binary('-', rt.binary('*', rt.binary('+', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.swizzle(texel, 'y')), 2, 'float'), _u_fullResolution, 2, 'float'), _u_tileOffset, 2, 'float'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float')), 'rgb'))
    gx = rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('-', rt.binary('-', rt.unary('-', tl), rt.binary('*', rt.f(2), ml, 1, 'float'), 1, 'float'), bl, 1, 'float'), tr, 1, 'float'), rt.binary('*', rt.f(2), mr, 1, 'float'), 1, 'float'), br, 1, 'float')
    gy = rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('-', rt.binary('-', rt.unary('-', tl), rt.binary('*', rt.f(2), tc, 1, 'float'), 1, 'float'), tr, 1, 'float'), bl, 1, 'float'), rt.binary('*', rt.f(2), bc, 1, 'float'), 1, 'float'), br, 1, 'float')
    metric = rt.construct(1, _u_sobelMetric, 'int')
    edge = rt.component_wise('clamp', rt.binary('*', distance_metric__float_float_int.call(gx, gy, metric), rt.f(3), 1, 'float'), rt.f(0), rt.f(1))
    glow = rt.construct(3, ((((edge) * (rt.swizzle(base, 'r')))) * (rt.f(2))), ((((edge) * (rt.swizzle(base, 'g')))) * (rt.f(2))), ((((edge) * (rt.swizzle(base, 'b')))) * (rt.f(2))))
    result = rt.construct(3, (((rt.f(1))) - ((((((rt.f(1))) - (rt.swizzle(base, 'r')))) * ((((rt.f(1))) - (glow[0])))))), (((rt.f(1))) - ((((((rt.f(1))) - (rt.swizzle(base, 'g')))) * ((((rt.f(1))) - (glow[1])))))), (((rt.f(1))) - ((((((rt.f(1))) - (rt.swizzle(base, 'b')))) * ((((rt.f(1))) - (glow[2])))))))
    mixed = rt.construct(3, rt.component_wise('mix', rt.swizzle(base, 'r'), result[0], _u_alpha), rt.component_wise('mix', rt.swizzle(base, 'g'), result[1], _u_alpha), rt.component_wise('mix', rt.swizzle(base, 'b'), result[2], _u_alpha))
    g['fragColor'].replace((rt.construct(4, rt.component_wise('clamp', mixed, rt.f(0), rt.f(1)), rt.swizzle(base, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
