# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_accumTex = ctx.texture_binding('accumTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  main__void = lambda do
    _for0_first = nil; _for1_first = nil; accum = nil; count = nil; globalCoord = nil; gx = nil; gy = nil; mean = nil; normalized = nil; s = nil; sampleUV = nil; sqrtVal = nil; src = nil; sum = nil; uv = nil; v = nil
    globalCoord = rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float')
    uv = rt.binary('/', globalCoord, _u_fullResolution, 2, 'float')
    src = rt.texture(_u_inputTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_inputTex)), 2, 'float'))
    accum = rt.texture(_u_accumTex, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), rt.construct(2, rt.texture_size(_u_accumTex)), 2, 'float'))
    sum = rt.f(0)
    count = rt.f(0)
    gy = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        gy = rt.binary('+', gy, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', gy, rt.i(32)))
        break
      end
      gx = rt.i(0)
      _for1_first = true
      (0..1048575).each do |_for1|
        unless _for1_first
          gx = rt.binary('+', gx, rt.i(1), 1, 'int')
        end
        _for1_first = false
        unless rt.bool(rt.binary('<', gx, rt.i(32)))
          break
        end
        sampleUV = rt.binary('/', rt.binary('+', rt.construct(2, rt.construct(1, gx), rt.construct(1, gy)), rt.f(0.5), 2, 'float'), rt.f(32), 2, 'float')
        s = rt.texture(_u_accumTex, sampleUV)
        v = rt.binary('/', rt.binary('+', rt.binary('+', rt.swizzle(s, 'r'), rt.swizzle(s, 'g'), 1, 'float'), rt.swizzle(s, 'b'), 1, 'float'), rt.f(3), 1, 'float')
        sum = rt.binary('+', sum, v, 1, 'float')
        count = rt.binary('+', count, rt.f(1), 1, 'float')
      end
    end
    mean = rt.binary('/', sum, count, 1, 'float')
    normalized = rt.construct(3, 0.0)
    if rt.bool(rt.binary('>', mean, rt.f(0)))
      normalized.replace((rt.component_wise('clamp', rt.binary('/', rt.swizzle(accum, 'rgb'), rt.binary('*', mean, rt.f(4), 1, 'float'), 3, 'float'), rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
    else
      normalized.replace((rt.swizzle(accum, 'rgb')).map { |c| rt.f32(c) })
    end
    sqrtVal = rt.component_wise('sqrt', normalized)
    g['fragColor'].replace((rt.construct(4, rt.component_wise('mix', rt.swizzle(src, 'rgb'), sqrtVal, _u_alpha), rt.swizzle(src, 'a'))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
