# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  getLuminosity__vec3 = sampleLayer__int_vec2 = layerActive__int = bandWeight__float_float = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_source = ctx.texture_binding('source')
  _u_layer0_tex = ctx.texture_binding('layer0_tex')
  _u_layer1_tex = ctx.texture_binding('layer1_tex')
  _u_layer2_tex = ctx.texture_binding('layer2_tex')
  _u_layer3_tex = ctx.texture_binding('layer3_tex')
  _u_layer4_tex = ctx.texture_binding('layer4_tex')
  _u_layer5_tex = ctx.texture_binding('layer5_tex')
  _u_layer6_tex = ctx.texture_binding('layer6_tex')
  _u_layer7_tex = ctx.texture_binding('layer7_tex')
  _u_layers = u.key?('layers') ? u['layers'] : 0
  _u_smoothness = u.key?('smoothness') ? u['smoothness'] : rt.f(0.0)
  _u_layer0_active = u.key?('layer0_active') ? u['layer0_active'] : 0
  _u_layer1_active = u.key?('layer1_active') ? u['layer1_active'] : 0
  _u_layer2_active = u.key?('layer2_active') ? u['layer2_active'] : 0
  _u_layer3_active = u.key?('layer3_active') ? u['layer3_active'] : 0
  _u_layer4_active = u.key?('layer4_active') ? u['layer4_active'] : 0
  _u_layer5_active = u.key?('layer5_active') ? u['layer5_active'] : 0
  _u_layer6_active = u.key?('layer6_active') ? u['layer6_active'] : 0
  _u_layer7_active = u.key?('layer7_active') ? u['layer7_active'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  getLuminosity__vec3 = lambda do |color|
    color = rt.copy(color, 'float')
    return rt.dot(color, rt.construct(3, rt.f(0.29899999999999999), rt.f(0.58699999999999997), rt.f(0.114)))
  end
  sampleLayer__int_vec2 = lambda do |i, uv|
    uv = rt.copy(uv, 'float')
    if rt.bool(rt.binary('==', i, rt.i(0)))
      return rt.texture(_u_layer0_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(1)))
      return rt.texture(_u_layer1_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(2)))
      return rt.texture(_u_layer2_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(3)))
      return rt.texture(_u_layer3_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(4)))
      return rt.texture(_u_layer4_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(5)))
      return rt.texture(_u_layer5_tex, uv)
    end
    if rt.bool(rt.binary('==', i, rt.i(6)))
      return rt.texture(_u_layer6_tex, uv)
    end
    return rt.texture(_u_layer7_tex, uv)
  end
  layerActive__int = lambda do |i|
    if rt.bool(rt.binary('==', i, rt.i(0)))
      return _u_layer0_active
    end
    if rt.bool(rt.binary('==', i, rt.i(1)))
      return _u_layer1_active
    end
    if rt.bool(rt.binary('==', i, rt.i(2)))
      return _u_layer2_active
    end
    if rt.bool(rt.binary('==', i, rt.i(3)))
      return _u_layer3_active
    end
    if rt.bool(rt.binary('==', i, rt.i(4)))
      return _u_layer4_active
    end
    if rt.bool(rt.binary('==', i, rt.i(5)))
      return _u_layer5_active
    end
    if rt.bool(rt.binary('==', i, rt.i(6)))
      return _u_layer6_active
    end
    return _u_layer7_active
  end
  bandWeight__float_float = lambda do |lum, boundary|
    if rt.bool(rt.binary('<=', _u_smoothness, rt.f(0)))
      return rt.component_wise('step', boundary, lum)
    end
    return rt.component_wise('smoothstep', rt.binary('-', boundary, _u_smoothness, 1, 'float'), rt.binary('+', boundary, _u_smoothness, 1, 'float'), lum)
  end
  main__void = lambda do
    _for0_first = nil; boundary = nil; controlColor = nil; k = nil; lum = nil; n = nil; result = nil; src = nil; uv = nil; w = nil
    uv = rt.construct(2, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), _u_resolution, 2, 'float'))
    controlColor = rt.construct(4, rt.texture(_u_source, uv))
    lum = getLuminosity__vec3.call(rt.swizzle(controlColor, 'rgb'))
    n = rt.component_wise('clamp', _u_layers, rt.i(2), rt.i(8))
    result = rt.construct(4, (rt.bool(rt.binary('==', layerActive__int.call(rt.i(0)), rt.i(1))) ? (sampleLayer__int_vec2.call(rt.i(0), uv)) : (controlColor)))
    k = rt.i(1)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        k = rt.binary('+', k, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', k, rt.i(8)))
        break
      end
      if rt.bool(rt.binary('>=', k, n))
        break
      end
      src = rt.construct(4, (rt.bool(rt.binary('==', layerActive__int.call(k), rt.i(1))) ? (sampleLayer__int_vec2.call(k, uv)) : (controlColor)))
      boundary = rt.binary('/', rt.construct(1, k), rt.construct(1, n), 1, 'float')
      w = bandWeight__float_float.call(lum, boundary)
      result.replace((rt.component_wise('mix', result, src, w)).map { |c| rt.f32(c) })
    end
    g['fragColor'].replace((result).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
