# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash_uint__uint = hash__uint = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_typeCount = u.key?('typeCount') ? u['typeCount'] : 0
  _u_matrixSeed = u.key?('matrixSeed') ? u['matrixSeed'] : rt.f(0.0)
  _u_symmetricForces = u.key?('symmetricForces') ? u['symmetricForces'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  hash_uint__uint = lambda do |seed|
    state = nil; word = nil
    state = rt.binary('+', rt.binary('*', seed, rt.i(747796405), 1, 'uint'), rt.i(2891336453), 1, 'uint')
    word = rt.binary('*', rt.binary('^', rt.binary('>>', state, rt.binary('+', rt.binary('>>', state, rt.i(28), 1, 'uint'), rt.i(4), 1, 'uint'), 1, 'uint'), state, 1, 'uint'), rt.i(277803737), 1, 'uint')
    return rt.binary('^', rt.binary('>>', word, rt.i(22), 1, 'uint'), word, 1, 'uint')
  end
  hash__uint = lambda do |seed|
    return rt.binary('/', rt.construct(1, rt.hash_uint(seed)), rt.f(4294967295), 1, 'float')
  end
  main__void = lambda do
    coord = nil; curveShape = nil; prefDist = nil; seed = nil; strength = nil; typeA = nil; typeB = nil
    coord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy'), 'int')
    typeA = rt.swizzle(coord, 'x')
    typeB = rt.swizzle(coord, 'y')
    if rt.bool((rt.bool(rt.binary('>=', typeA, _u_typeCount)) || rt.bool(rt.binary('>=', typeB, _u_typeCount)) ? 1 : 0))
      g['fragColor'].replace((rt.construct(4, rt.f(0))).map { |c| rt.f32(c) })
      return
    end
    seed = rt.binary('+', rt.construct(1, rt.binary('*', _u_matrixSeed, rt.f(1000), 1, 'float'), 'uint'), rt.construct(1, rt.binary('+', rt.binary('*', typeA, rt.i(31), 1, 'int'), rt.binary('*', typeB, rt.i(17), 1, 'int'), 1, 'int'), 'uint'), 1, 'uint')
    if rt.bool((rt.bool(_u_symmetricForces) && rt.bool(rt.binary('<', typeB, typeA)) ? 1 : 0))
      seed = rt.binary('+', rt.construct(1, rt.binary('*', _u_matrixSeed, rt.f(1000), 1, 'float'), 'uint'), rt.construct(1, rt.binary('+', rt.binary('*', typeB, rt.i(31), 1, 'int'), rt.binary('*', typeA, rt.i(17), 1, 'int'), 1, 'int'), 'uint'), 1, 'uint')
    end
    strength = rt.f(0.0)
    if rt.bool(rt.binary('==', typeA, typeB))
      strength = rt.binary('-', rt.unary('-', rt.f(0.29999999999999999)), rt.binary('*', hash__uint.call(seed), rt.f(0.40000000000000002), 1, 'float'), 1, 'float')
    else
      strength = rt.binary('-', rt.binary('*', hash__uint.call(seed), rt.f(2), 1, 'float'), rt.f(1), 1, 'float')
    end
    prefDist = rt.binary('+', rt.f(0.29999999999999999), rt.binary('*', hash__uint.call(rt.binary('+', seed, rt.i(1), 1, 'uint')), rt.f(0.5), 1, 'float'), 1, 'float')
    curveShape = hash__uint.call(rt.binary('+', seed, rt.i(2), 1, 'uint'))
    g['fragColor'].replace((rt.construct(4, strength, prefDist, curveShape, rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
