# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash_uint__uint = hash__uint = rand__float = randomDirection__float = wrap01__vec2 = sampleGrid__vec2 = neighborhood__vec2_float = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_frame = u.key?('frame') ? u['frame'] : 0
  _u_stride = u.key?('stride') ? u['stride'] : rt.f(0.0)
  _u_inputWeight = u.key?('inputWeight') ? u['inputWeight'] : rt.f(0.0)
  _u_attrition = u.key?('attrition') ? u['attrition'] : rt.f(0.0)
  _u_stateSize = u.key?('stateSize') ? u['stateSize'] : 0
  _u_resetState = u.key?('resetState') ? u['resetState'] : 0
  _u_xyzTex = ctx.texture_binding('xyzTex')
  _u_velTex = ctx.texture_binding('velTex')
  _u_rgbaTex = ctx.texture_binding('rgbaTex')
  _u_gridTex = ctx.texture_binding('gridTex')
  _u_inputTex = ctx.texture_binding('inputTex')
  g['outXYZ'] = rt.construct(4, 0.0)
  g['outVel'] = rt.construct(4, 0.0)
  g['outRGBA'] = rt.construct(4, 0.0)
  hash_uint__uint = lambda do |seed|
    state = nil; word = nil
    state = rt.binary('+', rt.binary('*', seed, rt.i(747796405), 1, 'uint'), rt.i(2891336453), 1, 'uint')
    word = rt.binary('*', rt.binary('^', rt.binary('>>', state, rt.binary('+', rt.binary('>>', state, rt.i(28), 1, 'uint'), rt.i(4), 1, 'uint'), 1, 'uint'), state, 1, 'uint'), rt.i(277803737), 1, 'uint')
    return rt.binary('^', rt.binary('>>', word, rt.i(22), 1, 'uint'), word, 1, 'uint')
  end
  hash__uint = lambda do |seed|
    return rt.binary('/', rt.construct(1, rt.hash_uint(seed)), rt.f(4294967295), 1, 'float')
  end
  rand__float = lambda do |seed|
    bits = nil
    bits = rt.float_bits_to_uint(seed)
    bits = rt.hash_uint(bits)
    seed = rt.binary('-', rt.uint_bits_to_float(rt.binary('|', bits, rt.i(1065353216), 1, 'uint')), rt.f(1), 1, 'float')
    bits = rt.hash_uint(rt.binary('+', bits, rt.i(1), 1, 'uint'))
    seed = rt.binary('-', rt.uint_bits_to_float(rt.binary('|', rt.binary('&', bits, rt.i(8388607), 1, 'uint'), rt.i(1065353216), 1, 'uint')), rt.f(1), 1, 'float')
    return [seed, seed]
    return [nil, seed]
  end
  randomDirection__float = lambda do |seed|
    theta = nil
    theta = rt.binary('*', (begin _retc, seed = rand__float.call(seed); _retc end), rt.f(6.2831853071800001), 1, 'float')
    return [rt.construct(2, rt.component_wise('cos', theta), rt.component_wise('sin', theta)), seed]
    return [nil, seed]
  end
  wrap01__vec2 = lambda do |v|
    v = rt.copy(v, 'float')
    return rt.component_wise('fract', rt.component_wise('max', v, rt.f(0)))
  end
  sampleGrid__vec2 = lambda do |uv|
    uv = rt.copy(uv, 'float')
    coord = nil; dims = nil
    dims = rt.texture_size(_u_gridTex)
    coord = rt.construct(2, rt.binary('*', wrap01__vec2.call(uv), rt.construct(2, dims), 2, 'float'), 'int')
    return rt.swizzle(rt.texel_fetch(_u_gridTex, coord, rt.i(0)), 'a')
  end
  neighborhood__vec2_float = lambda do |uv, radius|
    uv = rt.copy(uv, 'float')
    accum = nil; gridDims = nil; texel = nil
    gridDims = rt.construct(2, rt.texture_size(_u_gridTex))
    texel = rt.binary('/', radius, gridDims, 2, 'float')
    accum = rt.f(0)
    accum = rt.binary('+', accum, sampleGrid__vec2.call(uv), 1, 'float')
    accum = rt.binary('+', accum, sampleGrid__vec2.call(rt.binary('+', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.f(0)), 2, 'float')), 1, 'float')
    accum = rt.binary('+', accum, sampleGrid__vec2.call(rt.binary('-', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.f(0)), 2, 'float')), 1, 'float')
    accum = rt.binary('+', accum, sampleGrid__vec2.call(rt.binary('+', uv, rt.construct(2, rt.f(0), rt.swizzle(texel, 'y')), 2, 'float')), 1, 'float')
    accum = rt.binary('+', accum, sampleGrid__vec2.call(rt.binary('-', uv, rt.construct(2, rt.f(0), rt.swizzle(texel, 'y')), 2, 'float')), 1, 'float')
    return rt.binary('*', accum, rt.f(0.20000000000000001), 1, 'float')
  end
  main__void = lambda do
    agentId = nil; agentRand = nil; alive = nil; attritionRate = nil; candidate = nil; coord = nil; frameSeed = nil; gridDims = nil; here = nil; inputCoord = nil; inputDims = nil; inputDir = nil; inputVal = nil; inputW = nil; local = nil; nearby = nil; needsRespawn = nil; pos = nil; proximity = nil; randomDir = nil; rgba = nil; seed = nil; stateDims = nil; stepDir = nil; stepSize = nil; stuck = nil; texel = nil; vel = nil; xyz = nil
    coord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy'), 'int')
    stateDims = rt.texture_size(_u_xyzTex)
    xyz = rt.texel_fetch(_u_xyzTex, coord, rt.i(0))
    vel = rt.texel_fetch(_u_velTex, coord, rt.i(0))
    rgba = rt.texel_fetch(_u_rgbaTex, coord, rt.i(0))
    pos = rt.swizzle(xyz, 'xy')
    alive = rt.swizzle(xyz, 'w')
    seed = rt.swizzle(vel, 'x')
    agentRand = rt.swizzle(vel, 'w')
    agentId = rt.construct(1, rt.binary('+', rt.swizzle(coord, 'x'), rt.binary('*', rt.swizzle(coord, 'y'), rt.swizzle(stateDims, 'x'), 1, 'int'), 1, 'int'), 'uint')
    if rt.bool(rt.binary('<=', seed, rt.f(0)))
      seed = rt.binary('+', hash__uint.call(agentId), rt.f(0.001), 1, 'float')
    end
    frameSeed = rt.hash_uint(rt.binary('+', rt.binary('*', agentId, rt.i(31), 1, 'uint'), rt.float_bits_to_uint(seed), 1, 'uint'))
    seed = rt.binary('-', rt.uint_bits_to_float(rt.binary('|', rt.binary('&', frameSeed, rt.i(8388607), 1, 'uint'), rt.i(1065353216), 1, 'uint')), rt.f(1), 1, 'float')
    if rt.bool(rt.binary('<', alive, rt.f(0.5)))
      g['outXYZ'].replace((xyz).map { |c| rt.f32(c) })
      g['outVel'].replace((rt.construct(4, seed, rt.f(0), rt.f(0), agentRand)).map { |c| rt.f32(c) })
      g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
      return
    end
    gridDims = rt.construct(2, rt.texture_size(_u_gridTex))
    texel = rt.binary('/', rt.f(1), rt.component_wise('max', rt.swizzle(gridDims, 'x'), rt.swizzle(gridDims, 'y')), 1, 'float')
    local = neighborhood__vec2_float.call(pos, rt.f(2))
    proximity = rt.component_wise('smoothstep', rt.f(0.014999999999999999), rt.f(0.12), local)
    randomDir = (begin _retc, seed = randomDirection__float.call(seed); _retc end)
    inputW = rt.binary('/', _u_inputWeight, rt.f(100), 1, 'float')
    stepDir = randomDir
    inputCoord = rt.construct(2, 0.0, 'int')
    inputDims = rt.construct(2, 0.0, 'int')
    inputDir = rt.construct(2, 0.0)
    inputVal = rt.construct(4, 0.0)
    if rt.bool(rt.binary('>', inputW, rt.f(0)))
      inputDims = rt.texture_size(_u_inputTex)
      inputCoord = rt.construct(2, rt.binary('*', wrap01__vec2.call(pos), rt.construct(2, inputDims), 2, 'float'), 'int')
      inputVal = rt.texel_fetch(_u_inputTex, inputCoord, rt.i(0))
      inputDir = rt.binary('-', rt.binary('*', rt.swizzle(inputVal, 'xy'), rt.f(2), 2, 'float'), rt.f(1), 2, 'float')
      if rt.bool(rt.binary('>', rt.length(inputDir), rt.f(0.01)))
        inputDir.replace((rt.normalize(inputDir)).map { |c| rt.f32(c) })
        stepDir.replace((rt.normalize(rt.component_wise('mix', randomDir, inputDir, inputW))).map { |c| rt.f32(c) })
      end
    end
    stepSize = rt.binary('*', rt.binary('*', rt.binary('/', _u_stride, rt.f(10), 1, 'float'), texel, 1, 'float'), rt.component_wise('mix', rt.f(3), rt.f(0.5), proximity), 1, 'float')
    stepDir.replace((rt.binary('+', stepDir, rt.binary('*', (begin _retc, seed = randomDirection__float.call(seed); _retc end), rt.f(0.29999999999999999), 2, 'float'), 2, 'float')).map { |c| rt.f32(c) })
    stepDir.replace((rt.normalize(stepDir)).map { |c| rt.f32(c) })
    candidate = wrap01__vec2.call(rt.binary('+', pos, rt.binary('*', stepDir, stepSize, 2, 'float'), 2, 'float'))
    here = sampleGrid__vec2.call(candidate)
    nearby = neighborhood__vec2_float.call(candidate, rt.f(1))
    stuck = (rt.bool(rt.binary('>', nearby, rt.f(0.29999999999999999))) && rt.bool(rt.binary('<', here, rt.f(0.5))) ? 1 : 0)
    needsRespawn = 0
    attritionRate = rt.f(0.0)
    if rt.bool(rt.binary('>', _u_attrition, rt.f(0)))
      attritionRate = rt.binary('*', _u_attrition, rt.f(0.01), 1, 'float')
      if rt.bool(rt.binary('<', (begin _retc, seed = rand__float.call(seed); _retc end), attritionRate))
        needsRespawn = 1
      end
    end
    if rt.bool(stuck)
      g['outXYZ'].replace((rt.construct(4, candidate, rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
      g['outVel'].replace((rt.construct(4, seed, rt.f(1), rt.f(0), agentRand)).map { |c| rt.f32(c) })
      g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
    else
      if rt.bool(needsRespawn)
        g['outXYZ'].replace((rt.construct(4, candidate, rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        g['outVel'].replace((rt.construct(4, seed, rt.f(0), rt.f(0), agentRand)).map { |c| rt.f32(c) })
        g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
      else
        g['outXYZ'].replace((rt.construct(4, candidate, rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
        g['outVel'].replace((rt.construct(4, seed, rt.f(0), rt.f(0), agentRand)).map { |c| rt.f32(c) })
        g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
      end
    end
  end
  main__void.call
  c0 = g['outXYZ']
  out[0] = rt.f32(c0[0]); out[1] = rt.f32(c0[1]); out[2] = rt.f32(c0[2]); out[3] = rt.f32(c0[3])
  c1 = g['outVel']
  out[4] = rt.f32(c1[0]); out[5] = rt.f32(c1[1]); out[6] = rt.f32(c1[2]); out[7] = rt.f32(c1[3])
  c2 = g['outRGBA']
  out[8] = rt.f32(c2[0]); out[9] = rt.f32(c2[1]); out[10] = rt.f32(c2[2]); out[11] = rt.f32(c2[3])
end
{ kernel: run_pixel, uses_derivatives: false, output_names: ["outXYZ", "outVel", "outRGBA"] }
