# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash_uint__uint = hash__uint = complexToScreen__vec2 = inMandelbrotInterior__float_float = main__void = nil
  _retc = nil
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_maxIter = u.key?('maxIter') ? u['maxIter'] : 0
  _u_minIter = u.key?('minIter') ? u['minIter'] : 0
  _u_mode = u.key?('mode') ? u['mode'] : 0
  _u_centerX = u.key?('centerX') ? u['centerX'] : rt.f(0.0)
  _u_centerY = u.key?('centerY') ? u['centerY'] : rt.f(0.0)
  _u_zoom = u.key?('zoom') ? u['zoom'] : rt.f(0.0)
  _u_xyzTex = ctx.texture_binding('xyzTex')
  _u_velTex = ctx.texture_binding('velTex')
  _u_rgbaTex = ctx.texture_binding('rgbaTex')
  g['outXYZ'] = rt.construct(4, 0.0)
  g['outVel'] = rt.construct(4, 0.0)
  g['outRGBA'] = rt.construct(4, 0.0)
  hash_uint__uint = lambda do |s|
    state = nil; word = nil
    state = rt.binary('+', rt.binary('*', s, rt.i(747796405), 1, 'uint'), rt.i(2891336453), 1, 'uint')
    word = rt.binary('*', rt.binary('^', rt.binary('>>', state, rt.binary('+', rt.binary('>>', state, rt.i(28), 1, 'uint'), rt.i(4), 1, 'uint'), 1, 'uint'), state, 1, 'uint'), rt.i(277803737), 1, 'uint')
    return rt.binary('^', rt.binary('>>', word, rt.i(22), 1, 'uint'), word, 1, 'uint')
  end
  hash__uint = lambda do |s|
    return rt.binary('/', rt.construct(1, rt.hash_uint(s)), rt.f(4294967295), 1, 'float')
  end
  complexToScreen__vec2 = lambda do |z|
    z = rt.copy(z, 'float')
    return rt.construct(2, rt.binary('+', rt.binary('*', rt.binary('*', rt.binary('*', rt.binary('-', rt.swizzle(z, 'y'), _u_centerY, 1, 'float'), _u_zoom, 1, 'float'), _u_zoom, 1, 'float'), rt.f(0.20000000000000001), 1, 'float'), rt.f(0.5), 1, 'float'), rt.binary('+', rt.binary('*', rt.binary('*', rt.binary('*', rt.binary('-', _u_centerX, rt.swizzle(z, 'x'), 1, 'float'), _u_zoom, 1, 'float'), _u_zoom, 1, 'float'), rt.f(0.20000000000000001), 1, 'float'), rt.f(0.5), 1, 'float'))
  end
  inMandelbrotInterior__float_float = lambda do |cRe, cIm|
    q = nil; xp1 = nil; y2 = nil
    y2 = rt.binary('*', cIm, cIm, 1, 'float')
    q = rt.binary('+', rt.binary('*', rt.binary('-', cRe, rt.f(0.25), 1, 'float'), rt.binary('-', cRe, rt.f(0.25), 1, 'float'), 1, 'float'), y2, 1, 'float')
    if rt.bool(rt.binary('<=', rt.binary('*', q, rt.binary('+', q, rt.binary('-', cRe, rt.f(0.25), 1, 'float'), 1, 'float'), 1, 'float'), rt.binary('*', rt.f(0.25), y2, 1, 'float')))
      return 1
    end
    xp1 = rt.binary('+', cRe, rt.f(1), 1, 'float')
    return rt.binary('<=', rt.binary('+', rt.binary('*', xp1, xp1, 1, 'float'), y2, 1, 'float'), rt.f(0.0625))
  end
  main__void = lambda do
    _for0_first = nil; _for1_first = nil; _for2_first = nil; agentSeed = nil; brightness = nil; cIm = nil; cRe = nil; col = nil; coord = nil; currentStep = nil; escapeAt = nil; escapeStep = nil; escaped = nil; i = nil; iterCap = nil; needsInit = nil; pos = nil; s = nil; screen = nil; stateSize = nil; step = nil; texSize = nil; vel = nil; z = nil; zi = nil; zr = nil
    coord = rt.construct(2, rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy')), 'int')
    texSize = rt.texture_size(_u_xyzTex)
    stateSize = rt.swizzle(texSize, 'x')
    pos = rt.construct(4, rt.texel_fetch(_u_xyzTex, coord, rt.i(0)))
    vel = rt.construct(4, rt.texel_fetch(_u_velTex, coord, rt.i(0)))
    col = rt.construct(4, rt.texel_fetch(_u_rgbaTex, coord, rt.i(0)))
    if rt.bool(rt.binary('<', rt.swizzle(pos, 'w'), rt.f(0.5)))
      g['outXYZ'].replace((pos).map { |c| rt.f32(c) })
      g['outVel'].replace((vel).map { |c| rt.f32(c) })
      g['outRGBA'].replace((col).map { |c| rt.f32(c) })
      return
    end
    agentSeed = rt.binary('^', rt.binary('^', rt.hash_uint(rt.construct(1, rt.binary('+', rt.swizzle(coord, 'x'), rt.binary('*', rt.swizzle(coord, 'y'), stateSize, 1, 'int'), 1, 'int'), 'uint')), rt.construct(1, rt.binary('*', _u_time, rt.f(65536), 1, 'float'), 'uint'), 1, 'uint'), rt.construct(1, rt.binary('*', rt.swizzle(vel, 'z'), rt.f(137), 1, 'float'), 'uint'), 1, 'uint')
    needsInit = rt.binary('<', rt.swizzle(pos, 'z'), rt.f(0.25))
    brightness = rt.f(0.0)
    cIm = rt.f(0.0)
    cRe = rt.f(0.0)
    escapeAt = 0
    escapeStep = rt.f(0.0)
    escaped = 0
    iterCap = 0
    screen = rt.construct(2, 0.0)
    z = rt.construct(2, 0.0)
    if rt.bool(needsInit)
      cRe = rt.binary('-', rt.binary('*', hash__uint.call(agentSeed), rt.f(3.5), 1, 'float'), rt.f(2.5), 1, 'float')
      cIm = rt.binary('-', rt.binary('*', hash__uint.call(rt.binary('+', agentSeed, rt.i(1), 1, 'uint')), rt.f(3), 1, 'float'), rt.f(1.5), 1, 'float')
      if rt.bool((rt.bool(rt.binary('==', _u_mode, rt.i(0))) && rt.bool(inMandelbrotInterior__float_float.call(cRe, cIm)) ? 1 : 0))
        g['outXYZ'].replace((rt.construct(4, rt.swizzle(pos, 'xy'), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        g['outVel'].replace((vel).map { |c| rt.f32(c) })
        g['outRGBA'].replace((rt.construct(4, rt.f(0), rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        return
      end
      z = rt.construct(2, rt.construct(2, rt.f(0)))
      escapeAt = rt.i(0)
      iterCap = rt.component_wise('min', _u_maxIter, rt.i(2048))
      i = rt.i(0)
      _for0_first = true
      (0..1048575).each do |_for0|
        unless _for0_first
          i = rt.binary('+', i, rt.i(1), 1, 'int')
        end
        _for0_first = false
        unless rt.bool(rt.binary('<', i, rt.i(2048)))
          break
        end
        if rt.bool(rt.binary('>=', i, iterCap))
          break
        end
        zr = rt.binary('+', rt.binary('-', rt.binary('*', rt.swizzle(z, 'x'), rt.swizzle(z, 'x'), 1, 'float'), rt.binary('*', rt.swizzle(z, 'y'), rt.swizzle(z, 'y'), 1, 'float'), 1, 'float'), cRe, 1, 'float')
        zi = rt.binary('+', rt.binary('*', rt.binary('*', rt.f(2), rt.swizzle(z, 'x'), 1, 'float'), rt.swizzle(z, 'y'), 1, 'float'), cIm, 1, 'float')
        z.replace((rt.construct(2, zr, zi)).map { |c| rt.f32(c) })
        if rt.bool(rt.binary('>', rt.dot(z, z), rt.f(4)))
          escapeAt = rt.binary('+', i, rt.i(1), 1, 'int')
          break
        end
      end
      escaped = rt.binary('>', escapeAt, rt.i(0))
      escapeStep = rt.f(0)
      brightness = rt.f(0)
      if rt.bool(rt.binary('==', _u_mode, rt.i(0)))
        if rt.bool((rt.bool(escaped) && rt.bool(rt.binary('>=', escapeAt, _u_minIter)) ? 1 : 0))
          escapeStep = rt.construct(1, escapeAt)
          brightness = rt.f(0.029999999999999999)
        end
      else
        if rt.bool((rt.bool(escaped) ? 0 : 1))
          escapeStep = rt.construct(1, iterCap)
          brightness = rt.f(0.029999999999999999)
        end
      end
      if rt.bool(rt.binary('==', brightness, rt.f(0)))
        g['outXYZ'].replace((rt.construct(4, rt.swizzle(pos, 'xy'), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        g['outVel'].replace((vel).map { |c| rt.f32(c) })
        g['outRGBA'].replace((rt.construct(4, rt.f(0), rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        return
      end
      screen = rt.construct(2, complexToScreen__vec2.call(rt.construct(2, cRe, cIm)))
      g['outXYZ'].replace((rt.construct(4, screen, rt.f(0.5), rt.f(1))).map { |c| rt.f32(c) })
      g['outVel'].replace((rt.construct(4, cRe, cIm, rt.f(1), escapeStep)).map { |c| rt.f32(c) })
      g['outRGBA'].replace((rt.construct(4, brightness, brightness, brightness, rt.f(1))).map { |c| rt.f32(c) })
      return
    end
    cRe = rt.swizzle(vel, 'x')
    cIm = rt.swizzle(vel, 'y')
    step = rt.swizzle(vel, 'z')
    escapeStep = rt.swizzle(vel, 'w')
    z = rt.construct(2, rt.construct(2, rt.f(0)))
    currentStep = rt.construct(1, step, 'int')
    i = rt.i(0)
    _for1_first = true
    (0..1048575).each do |_for1|
      unless _for1_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for1_first = false
      unless rt.bool(rt.binary('<', i, rt.i(2048)))
        break
      end
      if rt.bool(rt.binary('>=', i, currentStep))
        break
      end
      zr = rt.binary('+', rt.binary('-', rt.binary('*', rt.swizzle(z, 'x'), rt.swizzle(z, 'x'), 1, 'float'), rt.binary('*', rt.swizzle(z, 'y'), rt.swizzle(z, 'y'), 1, 'float'), 1, 'float'), cRe, 1, 'float')
      zi = rt.binary('+', rt.binary('*', rt.binary('*', rt.f(2), rt.swizzle(z, 'x'), 1, 'float'), rt.swizzle(z, 'y'), 1, 'float'), cIm, 1, 'float')
      z.replace((rt.construct(2, zr, zi)).map { |c| rt.f32(c) })
    end
    s = rt.i(0)
    _for2_first = true
    (0..1048575).each do |_for2|
      unless _for2_first
        s = rt.binary('+', s, rt.i(1), 1, 'int')
      end
      _for2_first = false
      unless rt.bool(rt.binary('<', s, rt.i(8)))
        break
      end
      step = rt.binary('+', step, rt.f(1), 1, 'float')
      if rt.bool(rt.binary('>=', step, escapeStep))
        g['outXYZ'].replace((rt.construct(4, rt.swizzle(pos, 'xy'), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        g['outVel'].replace((rt.construct(4, rt.f(0), rt.f(0), step, rt.f(0))).map { |c| rt.f32(c) })
        g['outRGBA'].replace((rt.construct(4, rt.f(0), rt.f(0), rt.f(0), rt.f(0))).map { |c| rt.f32(c) })
        return
      end
      zr = rt.binary('+', rt.binary('-', rt.binary('*', rt.swizzle(z, 'x'), rt.swizzle(z, 'x'), 1, 'float'), rt.binary('*', rt.swizzle(z, 'y'), rt.swizzle(z, 'y'), 1, 'float'), 1, 'float'), cRe, 1, 'float')
      zi = rt.binary('+', rt.binary('*', rt.binary('*', rt.f(2), rt.swizzle(z, 'x'), 1, 'float'), rt.swizzle(z, 'y'), 1, 'float'), cIm, 1, 'float')
      z.replace((rt.construct(2, zr, zi)).map { |c| rt.f32(c) })
    end
    screen = rt.construct(2, complexToScreen__vec2.call(z))
    g['outXYZ'].replace((rt.construct(4, screen, rt.f(0.5), rt.f(1))).map { |c| rt.f32(c) })
    g['outVel'].replace((rt.construct(4, cRe, cIm, step, escapeStep)).map { |c| rt.f32(c) })
    g['outRGBA'].replace((col).map { |c| rt.f32(c) })
  end
  main__void.call
  c0 = g['outXYZ']
  out[0] = rt.f32(c0[0]); out[1] = rt.f32(c0[1]); out[2] = rt.f32(c0[2]); out[3] = rt.f32(c0[3])
  c1 = g['outVel']
  out[4] = rt.f32(c1[0]); out[5] = rt.f32(c1[1]); out[6] = rt.f32(c1[2]); out[7] = rt.f32(c1[3])
  c2 = g['outRGBA']
  out[8] = rt.f32(c2[0]); out[9] = rt.f32(c2[1]); out[10] = rt.f32(c2[2]); out[11] = rt.f32(c2[3])
end
{ kernel: run_pixel, uses_derivatives: false, output_names: ["outXYZ", "outVel", "outRGBA"] }
