# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  _kernel__float_float_float = main__void = nil
  _retc = nil
  _u_densityTex = ctx.texture_binding('densityTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_muK = u.key?('muK') ? u['muK'] : rt.f(0.0)
  _u_sigmaK = u.key?('sigmaK') ? u['sigmaK'] : rt.f(0.0)
  _u_searchRadius = u.key?('searchRadius') ? u['searchRadius'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['EPSILON'] = rt.f(0.0001)
  g['PI'] = rt.f(3.1415926535900001)
  _kernel__float_float_float = lambda do |r, mu, sigma|
    x = nil
    x = rt.binary('/', rt.binary('-', r, mu, 1, 'float'), sigma, 1, 'float')
    return rt.component_wise('exp', rt.binary('*', rt.unary('-', x), x, 1, 'float'))
  end
  main__void = lambda do
    _U = nil; _for0_first = nil; _for1_first = nil; _for2_first = nil; density = nil; densitySize = nil; dr = nil; dx = nil; dy = nil; i = nil; iRadius = nil; kVal = nil; numSamples = nil; r = nil; sampleUV = nil; texelSize = nil; uv = nil; wK = nil
    densitySize = rt.construct(2, rt.construct(2, rt.texture_size(_u_densityTex)))
    uv = rt.construct(2, rt.binary('/', rt.swizzle(ctx.frag_coord, 'xy'), densitySize, 2, 'float'))
    texelSize = rt.construct(2, rt.binary('/', rt.f(1), densitySize, 2, 'float'))
    wK = rt.f(0)
    numSamples = rt.i(64)
    dr = rt.binary('/', _u_searchRadius, rt.construct(1, numSamples), 1, 'float')
    i = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        i = rt.binary('+', i, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', i, numSamples))
        break
      end
      r = rt.binary('*', rt.binary('+', rt.construct(1, i), rt.f(0.5), 1, 'float'), dr, 1, 'float')
      wK = rt.binary('+', wK, rt.binary('*', rt.binary('*', _kernel__float_float_float.call(r, _u_muK, _u_sigmaK), r, 1, 'float'), dr, 1, 'float'), 1, 'float')
    end
    wK = rt.binary('/', rt.f(1), rt.component_wise('max', rt.binary('*', rt.binary('*', wK, rt.f(2), 1, 'float'), g['PI'], 1, 'float'), g['EPSILON']), 1, 'float')
    _U = rt.f(0)
    iRadius = rt.construct(1, rt.component_wise('ceil', _u_searchRadius), 'int')
    dy = rt.unary('-', iRadius)
    _for1_first = true
    (0..1048575).each do |_for1|
      unless _for1_first
        dy = rt.binary('+', dy, rt.i(1), 1, 'int')
      end
      _for1_first = false
      unless rt.bool(rt.binary('<=', dy, iRadius))
        break
      end
      dx = rt.unary('-', iRadius)
      _for2_first = true
      (0..1048575).each do |_for2|
        unless _for2_first
          dx = rt.binary('+', dx, rt.i(1), 1, 'int')
        end
        _for2_first = false
        unless rt.bool(rt.binary('<=', dx, iRadius))
          break
        end
        r = rt.length(rt.construct(2, rt.construct(1, dx), rt.construct(1, dy)))
        if rt.bool(rt.binary('>', r, _u_searchRadius))
          next
        end
        sampleUV = rt.construct(2, rt.component_wise('fract', rt.binary('+', uv, rt.binary('*', rt.construct(2, rt.construct(1, dx), rt.construct(1, dy)), texelSize, 2, 'float'), 2, 'float')))
        density = rt.swizzle(rt.texture(_u_densityTex, sampleUV), 'r')
        kVal = rt.binary('*', _kernel__float_float_float.call(r, _u_muK, _u_sigmaK), wK, 1, 'float')
        _U = rt.binary('+', _U, rt.binary('*', density, kVal, 1, 'float'), 1, 'float')
      end
    end
    g['fragColor'].replace((rt.construct(4, _U, rt.f(0), rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
