# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  growth__float_float_float = growthDerivative__float_float_float = main__void = nil
  _retc = nil
  _u_xyzTex = ctx.texture_binding('xyzTex')
  _u_velTex = ctx.texture_binding('velTex')
  _u_rgbaTex = ctx.texture_binding('rgbaTex')
  _u_fieldTex = ctx.texture_binding('fieldTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_muG = u.key?('muG') ? u['muG'] : rt.f(0.0)
  _u_sigmaG = u.key?('sigmaG') ? u['sigmaG'] : rt.f(0.0)
  _u_repulsion = u.key?('repulsion') ? u['repulsion'] : rt.f(0.0)
  _u_dt = u.key?('dt') ? u['dt'] : rt.f(0.0)
  g['outXYZ'] = rt.construct(4, 0.0)
  g['outVel'] = rt.construct(4, 0.0)
  g['outRGBA'] = rt.construct(4, 0.0)
  g['EPSILON'] = rt.f(0.0001)
  growth__float_float_float = lambda do |_u, mu, sigma|
    x = nil
    x = rt.binary('/', rt.binary('-', _u, mu, 1, 'float'), sigma, 1, 'float')
    return rt.component_wise('exp', rt.binary('*', rt.unary('-', x), x, 1, 'float'))
  end
  growthDerivative__float_float_float = lambda do |_u, mu, sigma|
    _G = nil
    _G = growth__float_float_float.call(_u, mu, sigma)
    return rt.binary('/', rt.binary('*', _G, rt.binary('*', rt.unary('-', rt.f(2)), rt.binary('-', _u, mu, 1, 'float'), 1, 'float'), 1, 'float'), rt.binary('*', sigma, sigma, 1, 'float'), 1, 'float')
  end
  main__void = lambda do
    _U = nil; _Ux_minus = nil; _Ux_plus = nil; _Uy_minus = nil; _Uy_plus = nil; age = nil; alive = nil; coord = nil; dGdU = nil; fieldSize = nil; force = nil; forceMag = nil; gradG = nil; gradR = nil; gradU = nil; newPos = nil; rgba = nil; stateSize = nil; texelSize = nil; uv = nil; vel = nil; velocity = nil; worldScale = nil; xyz = nil
    stateSize = rt.texture_size(_u_xyzTex)
    coord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy'), 'int')
    xyz = rt.texel_fetch(_u_xyzTex, coord, rt.i(0))
    vel = rt.texel_fetch(_u_velTex, coord, rt.i(0))
    rgba = rt.texel_fetch(_u_rgbaTex, coord, rt.i(0))
    alive = rt.swizzle(xyz, 'w')
    if rt.bool(rt.binary('<', alive, rt.f(0.5)))
      g['outXYZ'].replace((xyz).map { |c| rt.f32(c) })
      g['outVel'].replace((vel).map { |c| rt.f32(c) })
      g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
      return
    end
    uv = rt.swizzle(xyz, 'xy')
    _U = rt.swizzle(rt.texture(_u_fieldTex, uv), 'r')
    fieldSize = rt.construct(2, rt.texture_size(_u_fieldTex))
    texelSize = rt.binary('/', rt.f(1), fieldSize, 2, 'float')
    _Ux_plus = rt.swizzle(rt.texture(_u_fieldTex, rt.component_wise('fract', rt.binary('+', uv, rt.construct(2, rt.swizzle(texelSize, 'x'), rt.f(0)), 2, 'float'))), 'r')
    _Ux_minus = rt.swizzle(rt.texture(_u_fieldTex, rt.component_wise('fract', rt.binary('-', uv, rt.construct(2, rt.swizzle(texelSize, 'x'), rt.f(0)), 2, 'float'))), 'r')
    _Uy_plus = rt.swizzle(rt.texture(_u_fieldTex, rt.component_wise('fract', rt.binary('+', uv, rt.construct(2, rt.f(0), rt.swizzle(texelSize, 'y')), 2, 'float'))), 'r')
    _Uy_minus = rt.swizzle(rt.texture(_u_fieldTex, rt.component_wise('fract', rt.binary('-', uv, rt.construct(2, rt.f(0), rt.swizzle(texelSize, 'y')), 2, 'float'))), 'r')
    gradU = rt.construct(2, rt.binary('/', rt.binary('-', _Ux_plus, _Ux_minus, 1, 'float'), rt.binary('*', rt.f(2), rt.swizzle(texelSize, 'x'), 1, 'float'), 1, 'float'), rt.binary('/', rt.binary('-', _Uy_plus, _Uy_minus, 1, 'float'), rt.binary('*', rt.f(2), rt.swizzle(texelSize, 'y'), 1, 'float'), 1, 'float'))
    worldScale = rt.binary('*', rt.component_wise('min', rt.swizzle(_u_resolution, 'x'), rt.swizzle(_u_resolution, 'y')), rt.f(0.050000000000000003), 1, 'float')
    gradU.replace((rt.binary('/', gradU, worldScale, 2, 'float')).map { |c| rt.f32(c) })
    dGdU = growthDerivative__float_float_float.call(_U, _u_muG, _u_sigmaG)
    gradG = rt.binary('*', dGdU, gradU, 2, 'float')
    gradR = rt.binary('*', _u_repulsion, gradU, 2, 'float')
    force = rt.binary('-', gradG, gradR, 2, 'float')
    forceMag = rt.length(force)
    if rt.bool(rt.binary('>', forceMag, rt.f(10)))
      force.replace((rt.binary('*', rt.binary('/', force, forceMag, 2, 'float'), rt.f(10), 2, 'float')).map { |c| rt.f32(c) })
    end
    newPos = rt.binary('+', uv, rt.binary('*', rt.binary('*', force, _u_dt, 2, 'float'), rt.f(0.01), 2, 'float'), 2, 'float')
    newPos.replace((rt.component_wise('fract', rt.binary('+', newPos, rt.f(1), 2, 'float'))).map { |c| rt.f32(c) })
    velocity = rt.binary('*', rt.binary('*', force, _u_dt, 2, 'float'), rt.f(0.01), 2, 'float')
    age = rt.binary('+', rt.swizzle(vel, 'z'), rt.f(0.016), 1, 'float')
    g['outXYZ'].replace((rt.construct(4, newPos, rt.swizzle(xyz, 'z'), rt.f(1))).map { |c| rt.f32(c) })
    g['outVel'].replace((rt.construct(4, velocity, age, rt.swizzle(vel, 'w'))).map { |c| rt.f32(c) })
    g['outRGBA'].replace((rgba).map { |c| rt.f32(c) })
  end
  main__void.call
  c0 = g['outXYZ']
  out[0] = rt.f32(c0[0]); out[1] = rt.f32(c0[1]); out[2] = rt.f32(c0[2]); out[3] = rt.f32(c0[3])
  c1 = g['outVel']
  out[4] = rt.f32(c1[0]); out[5] = rt.f32(c1[1]); out[6] = rt.f32(c1[2]); out[7] = rt.f32(c1[3])
  c2 = g['outRGBA']
  out[8] = rt.f32(c2[0]); out[9] = rt.f32(c2[1]); out[10] = rt.f32(c2[2]); out[11] = rt.f32(c2[3])
end
{ kernel: run_pixel, uses_derivatives: false, output_names: ["outXYZ", "outVel", "outRGBA"] }
