# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_accumTex = ctx.texture_binding('accumTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_alpha = u.key?('alpha') ? u['alpha'] : rt.f(0.0)
  _u_intensity = u.key?('intensity') ? u['intensity'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  main__void = lambda do
    a = nil; accum = nil; blended = nil; i = nil; inputColor = nil; result = nil; st = nil
    st = rt.construct(2, ((rt.swizzle(ctx.frag_coord, 'x')) / (_u_resolution[0])), ((rt.swizzle(ctx.frag_coord, 'y')) / (_u_resolution[1])))
    inputColor = rt.construct(4, (rt.texture(_u_inputTex, st))[0], (rt.texture(_u_inputTex, st))[1], (rt.texture(_u_inputTex, st))[2], (rt.texture(_u_inputTex, st))[3])
    accum = rt.construct(4, (rt.texture(_u_accumTex, st))[0], (rt.texture(_u_accumTex, st))[1], (rt.texture(_u_accumTex, st))[2], (rt.texture(_u_accumTex, st))[3])
    a = rt.binary('/', _u_alpha, rt.f(100), 1, 'float')
    i = rt.binary('/', _u_intensity, rt.f(100), 1, 'float')
    blended = rt.construct(4, rt.component_wise('max', inputColor[0], rt.f32(((accum[0]) * (i)))), rt.component_wise('max', inputColor[1], rt.f32(((accum[1]) * (i)))), rt.component_wise('max', inputColor[2], rt.f32(((accum[2]) * (i)))), rt.component_wise('max', inputColor[3], rt.f32(((accum[3]) * (i)))))
    result = rt.construct(4, rt.component_wise('mix', inputColor[0], blended[0], a), rt.component_wise('mix', inputColor[1], blended[1], a), rt.component_wise('mix', inputColor[2], blended[2], a), rt.component_wise('mix', inputColor[3], blended[3], a))
    result = rt.assign_swizzle(result, 'a', rt.component_wise('max', rt.swizzle(inputColor, 'a'), rt.swizzle(accum, 'a')))
    g['fragColor'].replace((result).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
