# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  atlasTexel__ivec3_int = sampleVolume__vec3 = intersectBox__vec3_vec3 = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_volumeSize = u.key?('volumeSize') ? u['volumeSize'] : 0
  _u_cubeBasis = u.key?('cubeBasis') ? u['cubeBasis'] : rt.construct(9, 0.0)
  _u_bgColor = u.key?('bgColor') ? u['bgColor'] : rt.construct(3, 0.0)
  _u_bgAlpha = u.key?('bgAlpha') ? u['bgAlpha'] : rt.f(0.0)
  _u_volumeCache = ctx.texture_binding('volumeCache')
  _u_density = u.key?('density') ? u['density'] : rt.f(0.0)
  _u_absorption = u.key?('absorption') ? u['absorption'] : rt.f(0.0)
  _u_emission = u.key?('emission') ? u['emission'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['geoOut'] = rt.construct(4, 0.0)
  g['MAX_STEPS'] = rt.i(256)
  atlasTexel__ivec3_int = lambda do |p, volSize|
    p = rt.copy(p, 'int')
    return rt.construct(2, rt.swizzle(p, 'x'), rt.binary('+', rt.swizzle(p, 'y'), rt.binary('*', rt.swizzle(p, 'z'), volSize, 1, 'int'), 1, 'int'), 'int')
  end
  sampleVolume__vec3 = lambda do |worldPos|
    worldPos = rt.copy(worldPos, 'float')
    c0 = nil; c00 = nil; c000 = nil; c001 = nil; c01 = nil; c010 = nil; c011 = nil; c1 = nil; c10 = nil; c100 = nil; c101 = nil; c11 = nil; c110 = nil; c111 = nil; frac = nil; i0 = nil; i1 = nil; texelFloor = nil; texelPos = nil; uvw = nil; volSize = nil; volSizeF = nil
    volSize = _u_volumeSize
    volSizeF = rt.construct(1, volSize)
    uvw = rt.construct(3, ((((worldPos[0]) * (rt.f(0.5)))) + (rt.f(0.5))), ((((worldPos[1]) * (rt.f(0.5)))) + (rt.f(0.5))), ((((worldPos[2]) * (rt.f(0.5)))) + (rt.f(0.5))))
    uvw.replace((rt.component_wise('clamp', uvw, rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
    texelPos = rt.construct(3, ((uvw[0]) * (((volSizeF) - (rt.f(1))))), ((uvw[1]) * (((volSizeF) - (rt.f(1))))), ((uvw[2]) * (((volSizeF) - (rt.f(1))))))
    texelFloor = rt.construct(3, rt.component_wise('floor', texelPos[0]), rt.component_wise('floor', texelPos[1]), rt.component_wise('floor', texelPos[2]))
    frac = rt.construct(3, ((texelPos[0]) - (texelFloor[0])), ((texelPos[1]) - (texelFloor[1])), ((texelPos[2]) - (texelFloor[2])))
    i0 = rt.construct(3, rt.construct(3, texelFloor), 'int')
    i1 = rt.component_wise('min', rt.binary('+', i0, rt.i(1), 3, 'int'), rt.binary('-', volSize, rt.i(1), 1, 'int'))
    c000 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i0, 'x'), rt.swizzle(i0, 'y'), rt.swizzle(i0, 'z'), 'int'), volSize), rt.i(0)))
    c100 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i1, 'x'), rt.swizzle(i0, 'y'), rt.swizzle(i0, 'z'), 'int'), volSize), rt.i(0)))
    c010 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i0, 'x'), rt.swizzle(i1, 'y'), rt.swizzle(i0, 'z'), 'int'), volSize), rt.i(0)))
    c110 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i1, 'x'), rt.swizzle(i1, 'y'), rt.swizzle(i0, 'z'), 'int'), volSize), rt.i(0)))
    c001 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i0, 'x'), rt.swizzle(i0, 'y'), rt.swizzle(i1, 'z'), 'int'), volSize), rt.i(0)))
    c101 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i1, 'x'), rt.swizzle(i0, 'y'), rt.swizzle(i1, 'z'), 'int'), volSize), rt.i(0)))
    c011 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i0, 'x'), rt.swizzle(i1, 'y'), rt.swizzle(i1, 'z'), 'int'), volSize), rt.i(0)))
    c111 = rt.construct(4, rt.texel_fetch(_u_volumeCache, atlasTexel__ivec3_int.call(rt.construct(3, rt.swizzle(i1, 'x'), rt.swizzle(i1, 'y'), rt.swizzle(i1, 'z'), 'int'), volSize), rt.i(0)))
    c00 = rt.construct(4, rt.component_wise('mix', c000[0], c100[0], rt.swizzle(frac, 'x')), rt.component_wise('mix', c000[1], c100[1], rt.swizzle(frac, 'x')), rt.component_wise('mix', c000[2], c100[2], rt.swizzle(frac, 'x')), rt.component_wise('mix', c000[3], c100[3], rt.swizzle(frac, 'x')))
    c10 = rt.construct(4, rt.component_wise('mix', c010[0], c110[0], rt.swizzle(frac, 'x')), rt.component_wise('mix', c010[1], c110[1], rt.swizzle(frac, 'x')), rt.component_wise('mix', c010[2], c110[2], rt.swizzle(frac, 'x')), rt.component_wise('mix', c010[3], c110[3], rt.swizzle(frac, 'x')))
    c01 = rt.construct(4, rt.component_wise('mix', c001[0], c101[0], rt.swizzle(frac, 'x')), rt.component_wise('mix', c001[1], c101[1], rt.swizzle(frac, 'x')), rt.component_wise('mix', c001[2], c101[2], rt.swizzle(frac, 'x')), rt.component_wise('mix', c001[3], c101[3], rt.swizzle(frac, 'x')))
    c11 = rt.construct(4, rt.component_wise('mix', c011[0], c111[0], rt.swizzle(frac, 'x')), rt.component_wise('mix', c011[1], c111[1], rt.swizzle(frac, 'x')), rt.component_wise('mix', c011[2], c111[2], rt.swizzle(frac, 'x')), rt.component_wise('mix', c011[3], c111[3], rt.swizzle(frac, 'x')))
    c0 = rt.construct(4, rt.component_wise('mix', c00[0], c10[0], rt.swizzle(frac, 'y')), rt.component_wise('mix', c00[1], c10[1], rt.swizzle(frac, 'y')), rt.component_wise('mix', c00[2], c10[2], rt.swizzle(frac, 'y')), rt.component_wise('mix', c00[3], c10[3], rt.swizzle(frac, 'y')))
    c1 = rt.construct(4, rt.component_wise('mix', c01[0], c11[0], rt.swizzle(frac, 'y')), rt.component_wise('mix', c01[1], c11[1], rt.swizzle(frac, 'y')), rt.component_wise('mix', c01[2], c11[2], rt.swizzle(frac, 'y')), rt.component_wise('mix', c01[3], c11[3], rt.swizzle(frac, 'y')))
    return rt.component_wise('mix', c0, c1, rt.swizzle(frac, 'z'))
  end
  intersectBox__vec3_vec3 = lambda do |ro, rd|
    ro = rt.copy(ro, 'float')
    rd = rt.copy(rd, 'float')
    invRd = nil; t0 = nil; t1 = nil; tEnter = nil; tExit = nil; tmax = nil; tmin = nil
    invRd = rt.construct(3, ((rt.f(1)) / (rd[0])), ((rt.f(1)) / (rd[1])), ((rt.f(1)) / (rd[2])))
    t0 = rt.construct(3, ((((rt.unary('-', rt.f(1))) - (ro[0]))) * (invRd[0])), ((((rt.unary('-', rt.f(1))) - (ro[1]))) * (invRd[1])), ((((rt.unary('-', rt.f(1))) - (ro[2]))) * (invRd[2])))
    t1 = rt.construct(3, ((((rt.f(1)) - (ro[0]))) * (invRd[0])), ((((rt.f(1)) - (ro[1]))) * (invRd[1])), ((((rt.f(1)) - (ro[2]))) * (invRd[2])))
    tmin = rt.construct(3, rt.component_wise('min', t0[0], t1[0]), rt.component_wise('min', t0[1], t1[1]), rt.component_wise('min', t0[2], t1[2]))
    tmax = rt.construct(3, rt.component_wise('max', t0[0], t1[0]), rt.component_wise('max', t0[1], t1[1]), rt.component_wise('max', t0[2], t1[2]))
    tEnter = rt.component_wise('max', rt.component_wise('max', rt.swizzle(tmin, 'x'), rt.swizzle(tmin, 'y')), rt.swizzle(tmin, 'z'))
    tExit = rt.component_wise('min', rt.component_wise('min', rt.swizzle(tmax, 'x'), rt.swizzle(tmax, 'y')), rt.swizzle(tmax, 'z'))
    if rt.bool((rt.bool(rt.binary('>', tEnter, tExit)) || rt.bool(rt.binary('<', tExit, rt.f(0))) ? 1 : 0))
      return rt.construct(2, rt.unary('-', rt.f(1)))
    end
    return rt.construct(2, tEnter, tExit)
  end
  main__void = lambda do
    _for0_first = nil; _t = nil; a = nil; col = nil; dt = nil; i = nil; outc = nil; rd = nil; res = nil; ro = nil; s = nil; t0 = nil; tb = nil; trans = nil; uv = nil
    res = rt.construct(2, (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[0]) : (_u_resolution[0])), (rt.bool(rt.binary('>', rt.swizzle(_u_fullResolution, 'x'), rt.f(0))) ? (_u_fullResolution[1]) : (_u_resolution[1])))
    uv = rt.construct(2, ((((((rt.swizzle(ctx.frag_coord, 'x')) + (_u_tileOffset[0]))) - (((rt.f(0.5)) * (res[0]))))) / (((rt.f(0.5)) * (rt.swizzle(res, 'y'))))), ((((((rt.swizzle(ctx.frag_coord, 'y')) + (_u_tileOffset[1]))) - (((rt.f(0.5)) * (res[1]))))) / (((rt.f(0.5)) * (rt.swizzle(res, 'y'))))))
    ro = rt.construct(3, rt.construct(3, rt.f(0)))
    rd = rt.construct(3, rt.normalize(rt.matrix_mult(_u_cubeBasis, rt.construct(3, rt.swizzle(uv, 'x'), rt.unary('-', rt.swizzle(uv, 'y')), rt.f(1)), 3)))
    col = rt.construct(3, rt.construct(3, rt.f(0)))
    trans = rt.f(1)
    tb = rt.construct(2, intersectBox__vec3_vec3.call(ro, rd))
    dt = rt.f(0.0)
    _t = rt.f(0.0)
    t0 = rt.f(0.0)
    if rt.bool(rt.binary('>', rt.swizzle(tb, 'y'), rt.f(0)))
      t0 = rt.component_wise('max', rt.swizzle(tb, 'x'), rt.f(0))
      dt = rt.binary('/', rt.binary('-', rt.swizzle(tb, 'y'), t0, 1, 'float'), rt.construct(1, g['MAX_STEPS']), 1, 'float')
      _t = t0
      i = rt.i(0)
      _for0_first = true
      (0..1048575).each do |_for0|
        unless _for0_first
          i = rt.binary('+', i, rt.i(1), 1, 'int')
        end
        _for0_first = false
        unless rt.bool(rt.binary('<', i, g['MAX_STEPS']))
          break
        end
        s = rt.construct(4, sampleVolume__vec3.call(rt.construct(3, ((ro[0]) + (((rd[0]) * (_t)))), ((ro[1]) + (((rd[1]) * (_t)))), ((ro[2]) + (((rd[2]) * (_t)))))))
        a = rt.binary('-', rt.f(1), rt.component_wise('exp', rt.binary('*', rt.binary('*', rt.binary('*', rt.unary('-', rt.swizzle(s, 'r')), _u_density, 1, 'float'), _u_absorption, 1, 'float'), dt, 1, 'float')), 1, 'float')
        col[0] = rt.f32(rt.binary('+', col[0], ((((((trans) * (a))) * (rt.swizzle(s, 'r')))) * (_u_emission)), 1, 'float')); col[1] = rt.f32(rt.binary('+', col[1], ((((((trans) * (a))) * (rt.swizzle(s, 'g')))) * (_u_emission)), 1, 'float')); col[2] = rt.f32(rt.binary('+', col[2], ((((((trans) * (a))) * (rt.swizzle(s, 'b')))) * (_u_emission)), 1, 'float'))
        trans = rt.binary('*', trans, rt.binary('-', rt.f(1), a, 1, 'float'), 1, 'float')
        if rt.bool(rt.binary('<', trans, rt.f(0.0099999997764825821)))
          break
        end
        _t = rt.binary('+', _t, dt, 1, 'float')
      end
    end
    outc = rt.construct(3, ((col[0]) + (((_u_bgColor[0]) * (trans)))), ((col[1]) + (((_u_bgColor[1]) * (trans)))), ((col[2]) + (((_u_bgColor[2]) * (trans)))))
    g['fragColor'].replace((rt.construct(4, outc, rt.binary('+', rt.binary('-', rt.f(1), trans, 1, 'float'), rt.binary('*', _u_bgAlpha, trans, 1, 'float'), 1, 'float'))).map { |c| rt.f32(c) })
    g['geoOut'][0] = rt.f32(rt.f(0.5)); g['geoOut'][1] = rt.f32(rt.f(0.5)); g['geoOut'][2] = rt.f32(rt.f(0.5)); g['geoOut'][3] = rt.f32(rt.f(1))
  end
  main__void.call
  c0 = g['fragColor']
  out[0] = rt.f32(c0[0]); out[1] = rt.f32(c0[1]); out[2] = rt.f32(c0[2]); out[3] = rt.f32(c0[3])
  c1 = g['geoOut']
  out[4] = rt.f32(c1[0]); out[5] = rt.f32(c1[1]); out[6] = rt.f32(c1[2]); out[7] = rt.f32(c1[3])
end
{ kernel: run_pixel, uses_derivatives: false, output_names: ["fragColor", "geoOut"] }
