# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash11__float = hash22__vec2 = lum__vec3 = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_inputForce = u.key?('inputForce') ? u['inputForce'] : rt.f(0.0)
  _u_inputDye = u.key?('inputDye') ? u['inputDye'] : rt.f(0.0)
  _u_resetState = u.key?('resetState') ? u['resetState'] : 0
  _u_bufTex = ctx.texture_binding('bufTex')
  _u_inputTex = ctx.texture_binding('inputTex')
  g['fragColor'] = rt.construct(4, 0.0)
  hash11__float = lambda do |x|
    return rt.component_wise('fract', rt.binary('*', rt.component_wise('sin', rt.binary('*', x, rt.f(12.989800453186035), 1, 'float')), rt.f(43758.546875), 1, 'float'))
  end
  hash22__vec2 = lambda do |p|
    p = rt.copy(p, 'float')
    p = rt.assign_swizzle(p, 'x', rt.dot(p, rt.construct(2, rt.f(127.09999847412109), rt.f(311.70001220703125))))
    p = rt.assign_swizzle(p, 'y', rt.dot(p, rt.construct(2, rt.f(269.5), rt.f(183.30000305175781))))
    return rt.component_wise('fract', rt.construct(2, ((rt.component_wise('sin', p[0])) * (rt.f(43758.546875))), ((rt.component_wise('sin', p[1])) * (rt.f(43758.546875)))))
  end
  lum__vec3 = lambda do |c|
    c = rt.copy(c, 'float')
    return rt.binary('+', rt.binary('+', rt.binary('*', rt.f(0.2125999927520752), rt.swizzle(c, 'r'), 1, 'float'), rt.binary('*', rt.f(0.71520000696182251), rt.swizzle(c, 'g'), 1, 'float'), 1, 'float'), rt.binary('*', rt.f(0.072200000286102295), rt.swizzle(c, 'b'), 1, 'float'), 1, 'float')
  end
  main__void = lambda do
    _for0_first = nil; bufferEmpty = nil; c = nil; d = nil; dt = nil; dye = nil; falloff = nil; fragCoord = nil; grad = nil; i = nil; iDye = nil; iForce = nil; idf = nil; lc = nil; lr = nil; lu = nil; prev = nil; r2 = nil; radius = nil; seedF = nil; sign = nil; tangent = nil; texSize = nil; texel = nil; uv = nil; vel = nil
    texSize = rt.texture_size(_u_bufTex)
    fragCoord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'x'), rt.swizzle(ctx.frag_coord, 'y'))
    uv = rt.construct(2, ((fragCoord[0]) / ((texSize[0]))), ((fragCoord[1]) / ((texSize[1]))))
    prev = rt.construct(4, (rt.texture(_u_bufTex, uv))[0], (rt.texture(_u_bufTex, uv))[1], (rt.texture(_u_bufTex, uv))[2], (rt.texture(_u_bufTex, uv))[3])
    bufferEmpty = rt.binary('==', rt.swizzle(prev, 'a'), rt.f(0))
    dye = rt.f(0.0)
    seedF = rt.f(0.0)
    vel = rt.construct(2, 0.0)
    if rt.bool((rt.bool(_u_resetState) || rt.bool(bufferEmpty) ? 1 : 0))
      vel = rt.construct(2, rt.construct(2, rt.f(0)))
      dye = rt.f(0)
      seedF = rt.construct(1, _u_seed)
      i = rt.i(0)
      _for0_first = true
      (0..1048575).each do |_for0|
        unless _for0_first
          i = rt.binary('+', i, rt.i(1), 1, 'int')
        end
        _for0_first = false
        unless rt.bool(rt.binary('<', i, rt.i(9)))
          break
        end
        idf = rt.construct(1, i)
        c = rt.construct(2, hash22__vec2.call(rt.construct(2, (((((idf) * (rt.f(7.309999942779541)))) + (rt.f(1)))), (((((seedF) * (rt.f(13.699999809265137)))) + (idf))))))
        sign = (rt.bool(rt.binary('>', hash11__float.call(rt.binary('+', rt.binary('*', idf, rt.f(4.1700000762939453), 1, 'float'), rt.binary('*', seedF, rt.f(5.9000000953674316), 1, 'float'), 1, 'float')), rt.f(0.5))) ? (rt.f(1)) : (rt.unary('-', rt.f(1))))
        radius = rt.binary('+', rt.f(0.10000000149011612), rt.binary('*', rt.f(0.059999998658895493), hash11__float.call(rt.binary('+', rt.binary('*', idf, rt.f(2.1099998950958252), 1, 'float'), seedF, 1, 'float')), 1, 'float'), 1, 'float')
        d = rt.construct(2, ((uv[0]) - (c[0])), ((uv[1]) - (c[1])))
        r2 = rt.dot(d, d)
        falloff = rt.component_wise('exp', rt.binary('/', rt.unary('-', r2), rt.binary('*', rt.binary('*', rt.f(2), radius, 1, 'float'), radius, 1, 'float'), 1, 'float'))
        tangent = rt.construct(2, rt.construct(2, rt.unary('-', rt.swizzle(d, 'y')), rt.swizzle(d, 'x')))
        vel[0] = rt.f32(rt.binary('+', vel[0], ((((((tangent[0]) * (sign))) * (falloff))) * (rt.f(12))), 1, 'float')); vel[1] = rt.f32(rt.binary('+', vel[1], ((((((tangent[1]) * (sign))) * (falloff))) * (rt.f(12))), 1, 'float'))
        dye = rt.binary('+', dye, falloff, 1, 'float')
      end
      g['fragColor'].replace((rt.construct(4, vel, rt.component_wise('clamp', dye, rt.f(0), rt.f(1)), rt.f(1))).map { |c| rt.f32(c) })
      return
    end
    vel = rt.construct(2, rt.swizzle(prev, 'r'), rt.swizzle(prev, 'g'))
    dye = rt.swizzle(prev, 'b')
    dt = rt.binary('*', rt.component_wise('clamp', _u_speed, rt.f(0), rt.f(200)), rt.f(9.9999997473787516e-05), 1, 'float')
    iForce = rt.binary('*', rt.component_wise('clamp', _u_inputForce, rt.f(0), rt.f(100)), rt.f(0.0099999997764825821), 1, 'float')
    iDye = rt.binary('*', rt.component_wise('clamp', _u_inputDye, rt.f(0), rt.f(100)), rt.f(0.0099999997764825821), 1, 'float')
    grad = rt.construct(2, 0.0)
    lc = rt.f(0.0)
    lr = rt.f(0.0)
    lu = rt.f(0.0)
    texel = rt.construct(2, 0.0)
    if rt.bool((rt.bool(rt.binary('>', iForce, rt.f(0))) || rt.bool(rt.binary('>', iDye, rt.f(0))) ? 1 : 0))
      texel = rt.construct(2, ((rt.f(1)) / ((texSize[0]))), ((rt.f(1)) / ((texSize[1]))))
      lc = lum__vec3.call(rt.swizzle(rt.texture(_u_inputTex, uv), 'rgb'))
      lr = lum__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('+', uv, rt.construct(2, rt.swizzle(texel, 'x'), rt.f(0)), 2, 'float')), 'rgb'))
      lu = lum__vec3.call(rt.swizzle(rt.texture(_u_inputTex, rt.binary('+', uv, rt.construct(2, rt.f(0), rt.swizzle(texel, 'y')), 2, 'float')), 'rgb'))
      grad = rt.construct(2, rt.construct(2, rt.binary('-', lr, lc, 1, 'float'), rt.binary('-', lu, lc, 1, 'float')))
      vel[0] = rt.f32(rt.binary('+', vel[0], ((((grad[0]) * (iForce))) * (rt.f(50))), 1, 'float')); vel[1] = rt.f32(rt.binary('+', vel[1], ((((grad[1]) * (iForce))) * (rt.f(50))), 1, 'float'))
      dye = rt.binary('+', dye, rt.binary('*', rt.binary('*', rt.binary('*', lc, iDye, 1, 'float'), dt, 1, 'float'), rt.f(60), 1, 'float'), 1, 'float')
    end
    dye = rt.component_wise('clamp', dye, rt.f(0), rt.f(2))
    g['fragColor'].replace((rt.construct(4, vel, dye, rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
