# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash11__float_float = tilingNoise1D__float_float_float = periodicValue__float_float = rotate2D__vec2_float = oscSine__float = oscLinear__float = oscSawtooth__float = oscSawtoothInv__float = oscSquare__float = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_aspect = u.key?('aspect') ? u['aspect'] : rt.f(0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_oscType = u.key?('oscType') ? u['oscType'] : 0
  _u_frequency = u.key?('frequency') ? u['frequency'] : 0
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_rotation = u.key?('rotation') ? u['rotation'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  g['fragColor'] = rt.construct(4, 0.0)
  g['PI'] = rt.f(3.1415926535897931)
  g['TAU'] = rt.f(6.2831853071795862)
  hash11__float_float = lambda do |p, s|
    p = rt.component_wise('fract', rt.binary('+', rt.binary('*', p, rt.f(234.34), 1, 'float'), rt.binary('*', s, rt.f(0.71830000000000005), 1, 'float'), 1, 'float'))
    p = rt.binary('+', p, rt.binary('*', p, rt.binary('+', p, rt.f(34.229999999999997), 1, 'float'), 1, 'float'), 1, 'float')
    return rt.component_wise('fract', rt.binary('*', p, p, 1, 'float'))
  end
  tilingNoise1D__float_float_float = lambda do |x, freq, s|
    a = nil; b = nil; f = nil; i = nil; i0 = nil; i1 = nil; p = nil
    p = rt.binary('*', x, freq, 1, 'float')
    i = rt.component_wise('floor', p)
    f = rt.component_wise('fract', p)
    f = rt.binary('*', rt.binary('*', f, f, 1, 'float'), rt.binary('-', rt.f(3), rt.binary('*', rt.f(2), f, 1, 'float'), 1, 'float'), 1, 'float')
    i0 = rt.component_wise('mod', i, freq)
    i1 = rt.component_wise('mod', rt.binary('+', i, rt.f(1), 1, 'float'), freq)
    a = hash11__float_float.call(i0, s)
    b = hash11__float_float.call(i1, s)
    return rt.component_wise('mix', a, b, f)
  end
  periodicValue__float_float = lambda do |_t, v|
    return rt.binary('*', rt.binary('+', rt.component_wise('sin', rt.binary('*', rt.binary('-', _t, v, 1, 'float'), g['TAU'], 1, 'float')), rt.f(1), 1, 'float'), rt.f(0.5), 1, 'float')
  end
  rotate2D__vec2_float = lambda do |p, angle|
    p = rt.copy(p, 'float')
    c = nil; s = nil
    s = rt.component_wise('sin', angle)
    c = rt.component_wise('cos', angle)
    return rt.construct(2, rt.binary('-', rt.binary('*', rt.swizzle(p, 'x'), c, 1, 'float'), rt.binary('*', rt.swizzle(p, 'y'), s, 1, 'float'), 1, 'float'), rt.binary('+', rt.binary('*', rt.swizzle(p, 'x'), s, 1, 'float'), rt.binary('*', rt.swizzle(p, 'y'), c, 1, 'float'), 1, 'float'))
  end
  oscSine__float = lambda do |_t|
    return rt.component_wise('sin', rt.binary('*', rt.component_wise('fract', _t), g['PI'], 1, 'float'))
  end
  oscLinear__float = lambda do |_t|
    _t = rt.component_wise('fract', _t)
    return rt.binary('-', rt.f(1), rt.component_wise('abs', rt.binary('-', rt.binary('*', _t, rt.f(2), 1, 'float'), rt.f(1), 1, 'float')), 1, 'float')
  end
  oscSawtooth__float = lambda do |_t|
    return rt.component_wise('fract', _t)
  end
  oscSawtoothInv__float = lambda do |_t|
    return rt.binary('-', rt.f(1), rt.component_wise('fract', _t), 1, 'float')
  end
  oscSquare__float = lambda do |_t|
    return rt.component_wise('step', rt.f(0.5), rt.component_wise('fract', _t))
  end
  main__void = lambda do
    _t = nil; freq = nil; globalCoord = nil; res = nil; rotRad = nil; scaledTime = nil; scrollOffset = nil; scrolledPos = nil; spatialPhase = nil; spatialPos = nil; st = nil; timeNoise = nil; timePhase = nil; val = nil; valueNoise = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    res = _u_fullResolution
    if rt.bool(rt.binary('<', rt.swizzle(res, 'x'), rt.f(1)))
      res.replace((rt.construct(2, rt.f(1024), rt.f(1024))).map { |c| rt.f32(c) })
    end
    st = rt.construct(2, rt.binary('/', rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'), res, 2, 'float'))
    st.replace((rt.binary('-', st, rt.f(0.5), 2, 'float')).map { |c| rt.f32(c) })
    st = rt.assign_swizzle(st, 'x', rt.binary('*', rt.swizzle(st, 'x'), _u_aspect, 1, 'float'))
    rotRad = rt.binary('/', rt.binary('*', _u_rotation, g['PI'], 1, 'float'), rt.f(180), 1, 'float')
    st.replace((rotate2D__vec2_float.call(st, rotRad)).map { |c| rt.f32(c) })
    spatialPos = rt.binary('+', rt.swizzle(st, 'y'), rt.f(0.5), 1, 'float')
    freq = rt.construct(1, _u_frequency)
    spatialPhase = rt.binary('*', rt.swizzle(st, 'y'), freq, 1, 'float')
    timePhase = rt.binary('*', _u_time, _u_speed, 1, 'float')
    _t = rt.binary('+', spatialPhase, timePhase, 1, 'float')
    val = rt.f(0.0)
    scaledTime = rt.f(0.0)
    scrollOffset = rt.f(0.0)
    scrolledPos = rt.f(0.0)
    timeNoise = rt.f(0.0)
    valueNoise = rt.f(0.0)
    if rt.bool(rt.binary('==', _u_oscType, rt.i(0)))
      val = oscSine__float.call(_t)
    else
      if rt.bool(rt.binary('==', _u_oscType, rt.i(1)))
        val = oscLinear__float.call(_t)
      else
        if rt.bool(rt.binary('==', _u_oscType, rt.i(2)))
          val = oscSawtooth__float.call(_t)
        else
          if rt.bool(rt.binary('==', _u_oscType, rt.i(3)))
            val = oscSawtoothInv__float.call(_t)
          else
            if rt.bool(rt.binary('==', _u_oscType, rt.i(4)))
              val = oscSquare__float.call(_t)
            else
              if rt.bool(rt.binary('==', _u_oscType, rt.i(5)))
                scrollOffset = rt.component_wise('fract', rt.binary('*', _u_time, _u_speed, 1, 'float'))
                scrolledPos = rt.component_wise('fract', rt.binary('+', spatialPos, scrollOffset, 1, 'float'))
                timeNoise = tilingNoise1D__float_float_float.call(scrolledPos, freq, rt.binary('+', rt.construct(1, _u_seed), rt.f(12345), 1, 'float'))
                valueNoise = tilingNoise1D__float_float_float.call(scrolledPos, freq, rt.construct(1, _u_seed))
                scaledTime = rt.binary('*', periodicValue__float_float.call(rt.f(0), timeNoise), _u_speed, 1, 'float')
                val = periodicValue__float_float.call(scaledTime, valueNoise)
              else
                timeNoise = tilingNoise1D__float_float_float.call(spatialPos, freq, rt.binary('+', rt.construct(1, _u_seed), rt.f(12345), 1, 'float'))
                valueNoise = tilingNoise1D__float_float_float.call(spatialPos, freq, rt.construct(1, _u_seed))
                scaledTime = rt.binary('*', periodicValue__float_float.call(_u_time, timeNoise), _u_speed, 1, 'float')
                val = periodicValue__float_float.call(scaledTime, valueNoise)
              end
            end
          end
        end
      end
    end
    g['fragColor'].replace((rt.construct(4, rt.construct(3, val), rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
