# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  hash3__vec3 = atlasTexel__ivec3_int = sampleState__ivec3_int = sampleSeed__ivec3_int = laplacian3D__ivec3_int = main__void = nil
  _retc = nil
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : 0
  _u_volumeSize = u.key?('volumeSize') ? u['volumeSize'] : 0
  _u_feed = u.key?('feed') ? u['feed'] : rt.f(0.0)
  _u_kill = u.key?('kill') ? u['kill'] : rt.f(0.0)
  _u_rate1 = u.key?('rate1') ? u['rate1'] : rt.f(0.0)
  _u_rate2 = u.key?('rate2') ? u['rate2'] : rt.f(0.0)
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_iterations = u.key?('iterations') ? u['iterations'] : 0
  _u_colorMode = u.key?('colorMode') ? u['colorMode'] : 0
  _u_weight = u.key?('weight') ? u['weight'] : rt.f(0.0)
  _u_resetState = u.key?('resetState') ? u['resetState'] : 0
  _u_stateTex = ctx.texture_binding('stateTex')
  _u_seedTex = ctx.texture_binding('seedTex')
  g['fragColor'] = rt.construct(4, 0.0)
  hash3__vec3 = lambda do |p|
    p = rt.copy(p, 'float')
    p.replace((rt.binary('+', p, rt.binary('*', rt.construct(1, _u_seed), rt.f(0.10000000000000001), 1, 'float'), 3, 'float')).map { |c| rt.f32(c) })
    p.replace((rt.component_wise('fract', rt.binary('*', p, rt.construct(3, rt.f(0.1031), rt.f(0.10299999999999999), rt.f(0.097299999999999998)), 3, 'float'))).map { |c| rt.f32(c) })
    p.replace((rt.binary('+', p, rt.dot(p, rt.binary('+', rt.swizzle(p, 'yxz'), rt.f(33.329999999999998), 3, 'float')), 3, 'float')).map { |c| rt.f32(c) })
    return rt.component_wise('fract', rt.binary('*', rt.binary('+', rt.swizzle(p, 'x'), rt.swizzle(p, 'y'), 1, 'float'), rt.swizzle(p, 'z'), 1, 'float'))
  end
  atlasTexel__ivec3_int = lambda do |p, volSize|
    p = rt.copy(p, 'int')
    wrapped = nil
    wrapped = rt.construct(3, rt.binary('%', rt.binary('+', rt.swizzle(p, 'x'), volSize, 1, 'int'), volSize, 1, 'int'), rt.binary('%', rt.binary('+', rt.swizzle(p, 'y'), volSize, 1, 'int'), volSize, 1, 'int'), rt.binary('%', rt.binary('+', rt.swizzle(p, 'z'), volSize, 1, 'int'), volSize, 1, 'int'), 'int')
    return rt.construct(2, rt.swizzle(wrapped, 'x'), rt.binary('+', rt.swizzle(wrapped, 'y'), rt.binary('*', rt.swizzle(wrapped, 'z'), volSize, 1, 'int'), 1, 'int'), 'int')
  end
  sampleState__ivec3_int = lambda do |voxel, volSize|
    voxel = rt.copy(voxel, 'int')
    return rt.texel_fetch(_u_stateTex, atlasTexel__ivec3_int.call(voxel, volSize), rt.i(0))
  end
  sampleSeed__ivec3_int = lambda do |voxel, volSize|
    voxel = rt.copy(voxel, 'int')
    return rt.texel_fetch(_u_seedTex, atlasTexel__ivec3_int.call(voxel, volSize), rt.i(0))
  end
  laplacian3D__ivec3_int = lambda do |voxel, volSize|
    voxel = rt.copy(voxel, 'int')
    center = nil; lap = nil; neighborSum = nil; xn = nil; xp = nil; yn = nil; yp = nil; zn = nil; zp = nil
    center = rt.construct(4, sampleState__ivec3_int.call(voxel, volSize))
    xp = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.i(1), rt.i(0), rt.i(0), 'int'), 3, 'int'), volSize))
    xn = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.unary('-', rt.i(1)), rt.i(0), rt.i(0), 'int'), 3, 'int'), volSize))
    yp = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.i(0), rt.i(1), rt.i(0), 'int'), 3, 'int'), volSize))
    yn = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.i(0), rt.unary('-', rt.i(1)), rt.i(0), 'int'), 3, 'int'), volSize))
    zp = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.i(0), rt.i(0), rt.i(1), 'int'), 3, 'int'), volSize))
    zn = rt.construct(4, sampleState__ivec3_int.call(rt.binary('+', voxel, rt.construct(3, rt.i(0), rt.i(0), rt.unary('-', rt.i(1)), 'int'), 3, 'int'), volSize))
    neighborSum = rt.construct(2, rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('+', rt.binary('+', rt.swizzle(xp, 'ra'), rt.swizzle(xn, 'ra'), 2, 'float'), rt.swizzle(yp, 'ra'), 2, 'float'), rt.swizzle(yn, 'ra'), 2, 'float'), rt.swizzle(zp, 'ra'), 2, 'float'), rt.swizzle(zn, 'ra'), 2, 'float'))
    lap = rt.construct(2, rt.binary('-', neighborSum, rt.binary('*', rt.f(6), rt.swizzle(center, 'ra'), 2, 'float'), 2, 'float'))
    return lap
  end
  main__void = lambda do
    _end = nil; a = nil; b = nil; bufferIsEmpty = nil; density = nil; f = nil; hasSeedInput = nil; inCenterCube = nil; iterF = nil; k = nil; lap = nil; lum = nil; newA = nil; newB = nil; outRgb = nil; p = nil; pixelCoord = nil; r1 = nil; r2 = nil; s = nil; seedLum = nil; seedVal = nil; start = nil; state = nil; volSize = nil; voxel = nil; x = nil; y = nil; z = nil
    volSize = _u_volumeSize
    pixelCoord = rt.construct(2, rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy')), 'int')
    x = rt.swizzle(pixelCoord, 'x')
    y = rt.binary('%', rt.swizzle(pixelCoord, 'y'), volSize, 1, 'int')
    z = rt.binary('/', rt.construct(1, rt.swizzle(pixelCoord, 'y')), rt.construct(1, volSize), 1, 'float')
    voxel = rt.construct(3, x, y, z, 'int')
    if rt.bool((rt.bool((rt.bool(rt.binary('>=', x, volSize)) || rt.bool(rt.binary('>=', y, volSize)) ? 1 : 0)) || rt.bool(rt.binary('>=', z, volSize)) ? 1 : 0))
      g['fragColor'].replace((rt.construct(4, rt.f(0))).map { |c| rt.f32(c) })
      return
    end
    state = rt.construct(4, sampleState__ivec3_int.call(voxel, volSize))
    b = rt.swizzle(state, 'r')
    a = rt.swizzle(state, 'a')
    bufferIsEmpty = (rt.bool((rt.bool((rt.bool(rt.binary('==', rt.swizzle(state, 'r'), rt.f(0))) && rt.bool(rt.binary('==', rt.swizzle(state, 'g'), rt.f(0))) ? 1 : 0)) && rt.bool(rt.binary('==', rt.swizzle(state, 'b'), rt.f(0))) ? 1 : 0)) && rt.bool(rt.binary('==', rt.swizzle(state, 'a'), rt.f(0))) ? 1 : 0)
    if rt.bool((rt.bool(bufferIsEmpty) || rt.bool(_u_resetState) ? 1 : 0))
      a = rt.f(1)
      b = rt.f(0)
      _end = 0
      hasSeedInput = 0
      inCenterCube = 0
      seedVal = rt.construct(4, 0.0)
      start = 0
      if rt.bool(_u_resetState)
        start = rt.component_wise('max', rt.i(0), rt.binary('-', rt.binary('/', volSize, rt.i(2), 1, 'int'), rt.i(2), 1, 'int'))
        _end = rt.component_wise('min', rt.binary('-', volSize, rt.i(1), 1, 'int'), rt.binary('+', start, rt.i(3), 1, 'int'))
        inCenterCube = (rt.bool((rt.bool((rt.bool((rt.bool((rt.bool(rt.binary('>=', x, start)) && rt.bool(rt.binary('<=', x, _end)) ? 1 : 0)) && rt.bool(rt.binary('>=', y, start)) ? 1 : 0)) && rt.bool(rt.binary('<=', y, _end)) ? 1 : 0)) && rt.bool(rt.binary('>=', z, start)) ? 1 : 0)) && rt.bool(rt.binary('<=', z, _end)) ? 1 : 0)
        b = (rt.bool(inCenterCube) ? (rt.f(1)) : (rt.f(0)))
      else
        seedVal = rt.construct(4, sampleSeed__ivec3_int.call(voxel, volSize))
        hasSeedInput = (rt.bool((rt.bool(rt.binary('>', rt.swizzle(seedVal, 'r'), rt.f(0))) || rt.bool(rt.binary('>', rt.swizzle(seedVal, 'g'), rt.f(0))) ? 1 : 0)) || rt.bool(rt.binary('>', rt.swizzle(seedVal, 'b'), rt.f(0))) ? 1 : 0)
        lum = rt.f(0.0)
        p = rt.construct(3, 0.0)
        if rt.bool(hasSeedInput)
          lum = rt.binary('+', rt.binary('+', rt.binary('*', rt.f(0.29899999999999999), rt.swizzle(seedVal, 'r'), 1, 'float'), rt.binary('*', rt.f(0.58699999999999997), rt.swizzle(seedVal, 'g'), 1, 'float'), 1, 'float'), rt.binary('*', rt.f(0.114), rt.swizzle(seedVal, 'b'), 1, 'float'), 1, 'float')
          b = (rt.bool(rt.binary('>', lum, rt.f(0.5))) ? (rt.f(1)) : (rt.f(0)))
        else
          p = rt.construct(3, rt.construct(3, rt.construct(1, x), rt.construct(1, y), rt.construct(1, z)))
          if rt.bool(rt.binary('>', hash3__vec3.call(p), rt.f(0.96999999999999997)))
            b = rt.f(1)
          end
        end
      end
      g['fragColor'].replace((rt.construct(4, b, b, b, a)).map { |c| rt.f32(c) })
      return
    end
    lap = rt.construct(2, laplacian3D__ivec3_int.call(voxel, volSize))
    f = rt.binary('*', _u_feed, rt.f(0.001), 1, 'float')
    k = rt.binary('*', _u_kill, rt.f(0.001), 1, 'float')
    r1 = rt.binary('/', rt.binary('*', _u_rate1, rt.f(0.01), 1, 'float'), rt.f(6), 1, 'float')
    r2 = rt.binary('/', rt.binary('*', _u_rate2, rt.f(0.01), 1, 'float'), rt.f(6), 1, 'float')
    iterF = rt.component_wise('max', rt.f(1), rt.construct(1, _u_iterations))
    s = rt.binary('/', rt.binary('*', _u_speed, rt.f(0.01), 1, 'float'), iterF, 1, 'float')
    newA = rt.binary('+', a, rt.binary('*', rt.binary('+', rt.binary('-', rt.binary('*', r1, rt.swizzle(lap, 'y'), 1, 'float'), rt.binary('*', rt.binary('*', a, b, 1, 'float'), b, 1, 'float'), 1, 'float'), rt.binary('*', f, rt.binary('-', rt.f(1), a, 1, 'float'), 1, 'float'), 1, 'float'), s, 1, 'float'), 1, 'float')
    newB = rt.binary('+', b, rt.binary('*', rt.binary('-', rt.binary('+', rt.binary('*', r2, rt.swizzle(lap, 'x'), 1, 'float'), rt.binary('*', rt.binary('*', a, b, 1, 'float'), b, 1, 'float'), 1, 'float'), rt.binary('*', rt.binary('+', k, f, 1, 'float'), b, 1, 'float'), 1, 'float'), s, 1, 'float'), 1, 'float')
    seedLum = rt.f(0.0)
    seedVal = rt.construct(4, 0.0)
    if rt.bool(rt.binary('>', _u_weight, rt.f(0)))
      seedVal = rt.construct(4, sampleSeed__ivec3_int.call(voxel, volSize))
      seedLum = rt.binary('+', rt.binary('+', rt.binary('*', rt.f(0.29899999999999999), rt.swizzle(seedVal, 'r'), 1, 'float'), rt.binary('*', rt.f(0.58699999999999997), rt.swizzle(seedVal, 'g'), 1, 'float'), 1, 'float'), rt.binary('*', rt.f(0.114), rt.swizzle(seedVal, 'b'), 1, 'float'), 1, 'float')
      newB = rt.component_wise('mix', newB, seedLum, rt.binary('*', _u_weight, rt.f(0.01), 1, 'float'))
    end
    newA = rt.component_wise('clamp', newA, rt.f(0), rt.f(1))
    newB = rt.component_wise('clamp', newB, rt.f(0), rt.f(1))
    density = newB
    outRgb = rt.construct(3, 0.0)
    if rt.bool(rt.binary('==', _u_colorMode, rt.i(0)))
      outRgb.replace((rt.construct(3, density)).map { |c| rt.f32(c) })
    else
      outRgb.replace((rt.construct(3, density, newA, rt.binary('-', rt.f(1), density, 1, 'float'))).map { |c| rt.f32(c) })
    end
    g['fragColor'].replace((rt.construct(4, outRgb, newA)).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
