# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  pcg__uvec3 = prng__vec3 = cellRand__vec2_float_float_float = circleShape__vec2 = diamondShape__vec2 = squareShape__vec2 = arcShape__vec2_float_float_float = drawShape__int_vec2_float_float_float = shadeFromHash__float = main__void = nil
  _retc = nil
  _u_inputTex = ctx.texture_binding('inputTex')
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_tileOffset = u.key?('tileOffset') ? u['tileOffset'] : rt.construct(2, 0.0)
  _u_fullResolution = u.key?('fullResolution') ? u['fullResolution'] : rt.construct(2, 0.0)
  _u_renderScale = u.key?('renderScale') ? u['renderScale'] : rt.f(0.0)
  _u_mode = u.key?('mode') ? u['mode'] : rt.f(0.0)
  _u_depth = u.key?('depth') ? u['depth'] : rt.f(0.0)
  _u_density = u.key?('density') ? u['density'] : rt.f(0.0)
  _u_seed = u.key?('seed') ? u['seed'] : rt.f(0.0)
  _u_fill = u.key?('fill') ? u['fill'] : rt.f(0.0)
  _u_outline = u.key?('outline') ? u['outline'] : rt.f(0.0)
  _u_inputMix = u.key?('inputMix') ? u['inputMix'] : rt.f(0.0)
  _u_wrap = u.key?('wrap') ? u['wrap'] : rt.f(0.0)
  _u_time = u.key?('time') ? u['time'] : rt.f(0.0)
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  g['fragColor'] = rt.construct(4, 0.0)
  g['PHI'] = rt.f(1.6180339887498949)
  pcg__uvec3 = lambda do |v|
    v = rt.copy(v, 'uint')
    v.replace(rt.binary('+', rt.binary('*', v, rt.i(1664525), 3, 'uint'), rt.i(1013904223), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    v.replace(rt.binary('^', v, rt.binary('>>', v, rt.i(16), 3, 'uint'), 3, 'uint'))
    v = rt.assign_swizzle(v, 'x', rt.binary('+', rt.swizzle(v, 'x'), rt.binary('*', rt.swizzle(v, 'y'), rt.swizzle(v, 'z'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'y', rt.binary('+', rt.swizzle(v, 'y'), rt.binary('*', rt.swizzle(v, 'z'), rt.swizzle(v, 'x'), 1, 'uint'), 1, 'uint'))
    v = rt.assign_swizzle(v, 'z', rt.binary('+', rt.swizzle(v, 'z'), rt.binary('*', rt.swizzle(v, 'x'), rt.swizzle(v, 'y'), 1, 'uint'), 1, 'uint'))
    return v
  end
  prng__vec3 = lambda do |p|
    p = rt.copy(p, 'float')
    return rt.binary('/', rt.construct(3, pcg__uvec3.call(rt.construct(3, rt.construct(1, rt.swizzle(p, 'x'), 'uint'), rt.construct(1, rt.swizzle(p, 'y'), 'uint'), rt.construct(1, rt.swizzle(p, 'z'), 'uint'), 'uint'))), rt.construct(1, rt.i(4294967295)), 3, 'float')
  end
  cellRand__vec2_float_float_float = lambda do |cellMin, level, channel, animSeed|
    cellMin = rt.copy(cellMin, 'float')
    cx = nil; cy = nil
    cx = rt.component_wise('floor', rt.binary('*', rt.swizzle(cellMin, 'x'), rt.f(1000), 1, 'float'))
    cy = rt.component_wise('floor', rt.binary('*', rt.swizzle(cellMin, 'y'), rt.f(1000), 1, 'float'))
    return rt.swizzle(prng__vec3.call(rt.construct(3, rt.binary('+', cx, rt.binary('*', level, rt.f(7), 1, 'float'), 1, 'float'), rt.binary('+', cy, rt.binary('*', level, rt.f(13), 1, 'float'), 1, 'float'), rt.binary('+', rt.binary('+', _u_seed, channel, 1, 'float'), rt.binary('*', animSeed, rt.f(100), 1, 'float'), 1, 'float'))), 'x')
  end
  circleShape__vec2 = lambda do |centered|
    centered = rt.copy(centered, 'float')
    return rt.component_wise('step', rt.length(centered), rt.f(0.32000000000000001))
  end
  diamondShape__vec2 = lambda do |centered|
    centered = rt.copy(centered, 'float')
    return rt.component_wise('step', rt.binary('+', rt.component_wise('abs', rt.swizzle(centered, 'x')), rt.component_wise('abs', rt.swizzle(centered, 'y')), 1, 'float'), rt.f(0.32000000000000001))
  end
  squareShape__vec2 = lambda do |centered|
    centered = rt.copy(centered, 'float')
    return rt.component_wise('step', rt.component_wise('max', rt.component_wise('abs', rt.swizzle(centered, 'x')), rt.component_wise('abs', rt.swizzle(centered, 'y'))), rt.f(0.28000000000000003))
  end
  arcShape__vec2_float_float_float = lambda do |centered, halfW, halfH, h|
    centered = rt.copy(centered, 'float')
    corner = nil; dist = nil; origin = nil
    corner = rt.construct(1, rt.binary('*', h, rt.f(4), 1, 'float'), 'int')
    origin = rt.construct(2, 0.0)
    if rt.bool(rt.binary('==', corner, rt.i(0)))
      origin.replace((rt.construct(2, rt.unary('-', halfW), rt.unary('-', halfH))).map { |c| rt.f32(c) })
    else
      if rt.bool(rt.binary('==', corner, rt.i(1)))
        origin.replace((rt.construct(2, halfW, rt.unary('-', halfH))).map { |c| rt.f32(c) })
      else
        if rt.bool(rt.binary('==', corner, rt.i(2)))
          origin.replace((rt.construct(2, rt.unary('-', halfW), halfH)).map { |c| rt.f32(c) })
        else
          origin.replace((rt.construct(2, halfW, halfH)).map { |c| rt.f32(c) })
        end
      end
    end
    dist = rt.length(rt.binary('-', centered, origin, 2, 'float'))
    return rt.binary('*', rt.component_wise('step', dist, rt.f(0.69999999999999996)), rt.binary('-', rt.f(1), rt.component_wise('step', dist, rt.f(0.5)), 1, 'float'), 1, 'float')
  end
  drawShape__int_vec2_float_float_float = lambda do |shapeType, centered, halfW, halfH, h|
    centered = rt.copy(centered, 'float')
    if rt.bool(rt.binary('==', shapeType, rt.i(0)))
      return rt.f(1)
    end
    if rt.bool(rt.binary('==', shapeType, rt.i(1)))
      return circleShape__vec2.call(centered)
    end
    if rt.bool(rt.binary('==', shapeType, rt.i(2)))
      return diamondShape__vec2.call(centered)
    end
    if rt.bool(rt.binary('==', shapeType, rt.i(3)))
      return squareShape__vec2.call(centered)
    end
    if rt.bool(rt.binary('==', shapeType, rt.i(4)))
      return arcShape__vec2_float_float_float.call(centered, halfW, halfH, h)
    end
    return rt.f(1)
  end
  shadeFromHash__float = lambda do |h|
    idx = nil
    idx = rt.construct(1, rt.binary('*', h, rt.f(5), 1, 'float'), 'int')
    if rt.bool(rt.binary('==', idx, rt.i(0)))
      return rt.f(0.14999999999999999)
    end
    if rt.bool(rt.binary('==', idx, rt.i(1)))
      return rt.f(0.34999999999999998)
    end
    if rt.bool(rt.binary('==', idx, rt.i(2)))
      return rt.f(0.55000000000000004)
    end
    if rt.bool(rt.binary('==', idx, rt.i(3)))
      return rt.f(0.75)
    end
    return rt.f(1)
  end
  main__void = lambda do
    _for0_first = nil; bgShade = nil; blend = nil; canSplitH = nil; canSplitV = nil; cellAspect = nil; cellH = nil; cellMax = nil; cellMin = nil; cellPixelH = nil; cellPixelW = nil; cellSize = nil; cellUv = nil; cellW = nil; centered = nil; color = nil; curCorner = nil; curMask = nil; curShapeType = nil; curTexScale = nil; curVisualTime = nil; dens = nil; dir = nil; fillType = nil; globalCoord = nil; h = nil; halfH = nil; halfW = nil; inputColor = nil; isOutline = nil; level = nil; levelTime = nil; maxDepth = nil; mid = nil; minDim = nil; modeType = nil; nextCorner = nil; nextMask = nil; nextShapeType = nil; nextTexScale = nil; nextVisualTime = nil; outlineWidthX = nil; outlineWidthY = nil; ratio = nil; result = nil; shade = nil; shapeMask = nil; spd = nil; splitDir = nil; st = nil; texAspect = nil; texScale = nil; texUv = nil; visualBlend = nil; visualT = nil; wrapMode = nil
    globalCoord = rt.construct(2, rt.binary('+', rt.swizzle(ctx.frag_coord, 'xy'), _u_tileOffset, 2, 'float'))
    st = rt.construct(2, rt.binary('/', globalCoord, _u_fullResolution, 2, 'float'))
    maxDepth = rt.construct(1, _u_depth, 'int')
    dens = rt.binary('/', _u_density, rt.f(100), 1, 'float')
    fillType = rt.construct(1, _u_fill, 'int')
    modeType = rt.construct(1, _u_mode, 'int')
    spd = rt.binary('*', rt.component_wise('floor', _u_speed), rt.f(2), 1, 'float')
    outlineWidthX = rt.binary('/', rt.binary('*', _u_outline, _u_renderScale, 1, 'float'), rt.swizzle(_u_fullResolution, 'x'), 1, 'float')
    outlineWidthY = rt.binary('/', rt.binary('*', _u_outline, _u_renderScale, 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')
    cellMin = rt.construct(2, rt.construct(2, rt.f(0)))
    cellMax = rt.construct(2, rt.construct(2, rt.f(1)))
    isOutline = 0
    level = rt.i(0)
    _for0_first = true
    (0..1048575).each do |_for0|
      unless _for0_first
        level = rt.binary('+', level, rt.i(1), 1, 'int')
      end
      _for0_first = false
      unless rt.bool(rt.binary('<', level, rt.i(6)))
        break
      end
      if rt.bool(rt.binary('>=', level, maxDepth))
        break
      end
      levelTime = rt.component_wise('floor', rt.binary('+', rt.binary('*', _u_time, spd, 1, 'float'), rt.binary('*', rt.construct(1, level), g['PHI'], 1, 'float'), 1, 'float'))
      h = cellRand__vec2_float_float_float.call(cellMin, rt.construct(1, level), rt.f(0), levelTime)
      canSplitH = 0
      canSplitV = 0
      cellH = rt.f(0.0)
      cellW = rt.f(0.0)
      if rt.bool(rt.binary('<', h, dens))
        cellW = rt.binary('*', rt.binary('-', rt.swizzle(cellMax, 'x'), rt.swizzle(cellMin, 'x'), 1, 'float'), rt.swizzle(_u_fullResolution, 'x'), 1, 'float')
        cellH = rt.binary('*', rt.binary('-', rt.swizzle(cellMax, 'y'), rt.swizzle(cellMin, 'y'), 1, 'float'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')
        canSplitH = rt.binary('>=', rt.binary('/', rt.component_wise('min', cellW, rt.binary('*', cellH, rt.f(0.5), 1, 'float')), rt.component_wise('max', cellW, rt.binary('*', cellH, rt.f(0.5), 1, 'float')), 1, 'float'), rt.f(0.20000000000000001))
        canSplitV = rt.binary('>=', rt.binary('/', rt.component_wise('min', rt.binary('*', cellW, rt.f(0.5), 1, 'float'), cellH), rt.component_wise('max', rt.binary('*', cellW, rt.f(0.5), 1, 'float'), cellH), 1, 'float'), rt.f(0.20000000000000001))
        dir = rt.f(0.0)
        splitDir = 0
        if rt.bool(rt.binary('==', modeType, rt.i(0)))
          dir = cellRand__vec2_float_float_float.call(cellMin, rt.construct(1, level), rt.f(1), levelTime)
          splitDir = rt.unary('-', rt.i(1))
          if rt.bool(rt.binary('<', dir, rt.f(0.5)))
            if rt.bool(canSplitH)
              splitDir = rt.i(0)
            else
              if rt.bool(canSplitV)
                splitDir = rt.i(1)
              end
            end
          else
            if rt.bool(canSplitV)
              splitDir = rt.i(1)
            else
              if rt.bool(canSplitH)
                splitDir = rt.i(0)
              end
            end
          end
          mid = rt.f(0.0)
          if rt.bool(rt.binary('==', splitDir, rt.i(0)))
            mid = rt.binary('*', rt.binary('+', rt.swizzle(cellMin, 'y'), rt.swizzle(cellMax, 'y'), 1, 'float'), rt.f(0.5), 1, 'float')
            if rt.bool(rt.binary('<', rt.component_wise('abs', rt.binary('-', rt.swizzle(st, 'y'), mid, 1, 'float')), outlineWidthY))
              isOutline = 1
            end
            if rt.bool(rt.binary('<', rt.swizzle(st, 'y'), mid))
              cellMax = rt.assign_swizzle(cellMax, 'y', mid)
            else
              cellMin = rt.assign_swizzle(cellMin, 'y', mid)
            end
          else
            if rt.bool(rt.binary('==', splitDir, rt.i(1)))
              mid = rt.binary('*', rt.binary('+', rt.swizzle(cellMin, 'x'), rt.swizzle(cellMax, 'x'), 1, 'float'), rt.f(0.5), 1, 'float')
              if rt.bool(rt.binary('<', rt.component_wise('abs', rt.binary('-', rt.swizzle(st, 'x'), mid, 1, 'float')), outlineWidthX))
                isOutline = 1
              end
              if rt.bool(rt.binary('<', rt.swizzle(st, 'x'), mid))
                cellMax = rt.assign_swizzle(cellMax, 'x', mid)
              else
                cellMin = rt.assign_swizzle(cellMin, 'x', mid)
              end
            end
          end
        else
          mid = rt.construct(2, 0.0)
          if rt.bool((rt.bool(canSplitH) && rt.bool(canSplitV) ? 1 : 0))
            mid = rt.construct(2, rt.binary('*', rt.binary('+', cellMin, cellMax, 2, 'float'), rt.f(0.5), 2, 'float'))
            if rt.bool((rt.bool(rt.binary('<', rt.component_wise('abs', rt.binary('-', rt.swizzle(st, 'x'), rt.swizzle(mid, 'x'), 1, 'float')), outlineWidthX)) || rt.bool(rt.binary('<', rt.component_wise('abs', rt.binary('-', rt.swizzle(st, 'y'), rt.swizzle(mid, 'y'), 1, 'float')), outlineWidthY)) ? 1 : 0))
              isOutline = 1
            end
            if rt.bool(rt.binary('<', rt.swizzle(st, 'x'), rt.swizzle(mid, 'x')))
              cellMax = rt.assign_swizzle(cellMax, 'x', rt.swizzle(mid, 'x'))
            else
              cellMin = rt.assign_swizzle(cellMin, 'x', rt.swizzle(mid, 'x'))
            end
            if rt.bool(rt.binary('<', rt.swizzle(st, 'y'), rt.swizzle(mid, 'y')))
              cellMax = rt.assign_swizzle(cellMax, 'y', rt.swizzle(mid, 'y'))
            else
              cellMin = rt.assign_swizzle(cellMin, 'y', rt.swizzle(mid, 'y'))
            end
          end
        end
      end
    end
    cellSize = rt.construct(2, rt.binary('-', cellMax, cellMin, 2, 'float'))
    cellUv = rt.construct(2, rt.binary('/', rt.binary('-', st, cellMin, 2, 'float'), cellSize, 2, 'float'))
    cellPixelW = rt.binary('*', rt.swizzle(cellSize, 'x'), rt.swizzle(_u_fullResolution, 'x'), 1, 'float')
    cellPixelH = rt.binary('*', rt.swizzle(cellSize, 'y'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')
    minDim = rt.component_wise('min', cellPixelW, cellPixelH)
    centered = rt.construct(2, rt.binary('-', cellUv, rt.f(0.5), 2, 'float'))
    centered = rt.assign_swizzle(centered, 'x', rt.binary('*', rt.swizzle(centered, 'x'), rt.binary('/', cellPixelW, minDim, 1, 'float'), 1, 'float'))
    centered = rt.assign_swizzle(centered, 'y', rt.binary('*', rt.swizzle(centered, 'y'), rt.binary('/', cellPixelH, minDim, 1, 'float'), 1, 'float'))
    halfW = rt.binary('*', rt.binary('/', cellPixelW, minDim, 1, 'float'), rt.f(0.5), 1, 'float')
    halfH = rt.binary('*', rt.binary('/', cellPixelH, minDim, 1, 'float'), rt.f(0.5), 1, 'float')
    visualT = rt.binary('+', rt.binary('*', _u_time, spd, 1, 'float'), rt.binary('*', g['PHI'], rt.f(7), 1, 'float'), 1, 'float')
    curVisualTime = rt.component_wise('floor', visualT)
    nextVisualTime = rt.binary('+', curVisualTime, rt.f(1), 1, 'float')
    visualBlend = rt.component_wise('smoothstep', rt.f(0), rt.f(1), rt.component_wise('fract', visualT))
    shade = rt.component_wise('mix', shadeFromHash__float.call(cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(2), curVisualTime)), shadeFromHash__float.call(cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(2), nextVisualTime)), visualBlend)
    bgShade = rt.component_wise('mix', shadeFromHash__float.call(cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(8), curVisualTime)), shadeFromHash__float.call(cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(8), nextVisualTime)), visualBlend)
    curShapeType = fillType
    nextShapeType = fillType
    if rt.bool(rt.binary('==', modeType, rt.i(0)))
      curShapeType = rt.i(0)
      nextShapeType = rt.i(0)
    else
      if rt.bool(rt.binary('==', fillType, rt.i(5)))
        curShapeType = rt.construct(1, rt.binary('*', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(3), curVisualTime), rt.f(5), 1, 'float'), 'int')
        nextShapeType = rt.construct(1, rt.binary('*', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(3), nextVisualTime), rt.f(5), 1, 'float'), 'int')
      end
    end
    curCorner = cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(4), curVisualTime)
    nextCorner = cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(4), nextVisualTime)
    curMask = drawShape__int_vec2_float_float_float.call(curShapeType, centered, halfW, halfH, curCorner)
    nextMask = drawShape__int_vec2_float_float_float.call(nextShapeType, centered, halfW, halfH, nextCorner)
    shapeMask = rt.component_wise('mix', curMask, nextMask, visualBlend)
    color = rt.component_wise('mix', bgShade, shade, shapeMask)
    result = rt.construct(3, rt.construct(3, color))
    blend = rt.binary('/', _u_inputMix, rt.f(100), 1, 'float')
    cellAspect = rt.f(0.0)
    curTexScale = rt.f(0.0)
    inputColor = rt.construct(3, 0.0)
    nextTexScale = rt.f(0.0)
    ratio = rt.f(0.0)
    texAspect = rt.f(0.0)
    texScale = rt.f(0.0)
    texUv = rt.construct(2, 0.0)
    wrapMode = 0
    if rt.bool(rt.binary('>', blend, rt.f(0)))
      curTexScale = rt.binary('+', rt.f(0.29999999999999999), rt.binary('*', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(5), curVisualTime), rt.f(0.69999999999999996), 1, 'float'), 1, 'float')
      nextTexScale = rt.binary('+', rt.f(0.29999999999999999), rt.binary('*', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(5), nextVisualTime), rt.f(0.69999999999999996), 1, 'float'), 1, 'float')
      texScale = rt.component_wise('mix', curTexScale, nextTexScale, visualBlend)
      texUv = cellUv
      cellAspect = rt.binary('/', rt.binary('*', rt.swizzle(cellSize, 'x'), rt.swizzle(_u_fullResolution, 'x'), 1, 'float'), rt.binary('*', rt.swizzle(cellSize, 'y'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float'), 1, 'float')
      texAspect = rt.binary('/', rt.swizzle(_u_fullResolution, 'x'), rt.swizzle(_u_fullResolution, 'y'), 1, 'float')
      ratio = rt.binary('/', cellAspect, texAspect, 1, 'float')
      if rt.bool(rt.binary('>', ratio, rt.f(1)))
        texUv = rt.assign_swizzle(texUv, 'x', rt.binary('+', rt.f(0.5), rt.binary('*', rt.binary('-', rt.swizzle(texUv, 'x'), rt.f(0.5), 1, 'float'), ratio, 1, 'float'), 1, 'float'))
      else
        texUv = rt.assign_swizzle(texUv, 'y', rt.binary('+', rt.f(0.5), rt.binary('/', rt.binary('-', rt.swizzle(texUv, 'y'), rt.f(0.5), 1, 'float'), ratio, 1, 'float'), 1, 'float'))
      end
      texUv.replace((rt.binary('*', texUv, texScale, 2, 'float')).map { |c| rt.f32(c) })
      texUv = rt.assign_swizzle(texUv, 'x', rt.binary('+', rt.swizzle(texUv, 'x'), rt.binary('*', rt.component_wise('mix', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(6), curVisualTime), cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(6), nextVisualTime), visualBlend), rt.binary('-', rt.f(1), texScale, 1, 'float'), 1, 'float'), 1, 'float'))
      texUv = rt.assign_swizzle(texUv, 'y', rt.binary('+', rt.swizzle(texUv, 'y'), rt.binary('*', rt.component_wise('mix', cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(7), curVisualTime), cellRand__vec2_float_float_float.call(cellMin, rt.f(0), rt.f(7), nextVisualTime), visualBlend), rt.binary('-', rt.f(1), texScale, 1, 'float'), 1, 'float'), 1, 'float'))
      wrapMode = rt.construct(1, _u_wrap, 'int')
      if rt.bool(rt.binary('==', wrapMode, rt.i(0)))
        texUv.replace((rt.component_wise('abs', rt.binary('-', rt.component_wise('mod', rt.binary('+', texUv, rt.f(1), 2, 'float'), rt.f(2)), rt.f(1), 2, 'float'))).map { |c| rt.f32(c) })
      else
        if rt.bool(rt.binary('==', wrapMode, rt.i(1)))
          texUv.replace((rt.component_wise('mod', texUv, rt.f(1))).map { |c| rt.f32(c) })
        else
          texUv.replace((rt.component_wise('clamp', texUv, rt.f(0), rt.f(1))).map { |c| rt.f32(c) })
        end
      end
      inputColor = rt.construct(3, rt.swizzle(rt.texture(_u_inputTex, texUv), 'rgb'))
      result.replace((rt.component_wise('mix', result, inputColor, blend)).map { |c| rt.f32(c) })
    end
    if rt.bool((rt.bool(isOutline) && rt.bool(rt.binary('>', _u_outline, rt.f(0))) ? 1 : 0))
      result.replace((rt.construct(3, rt.f(0))).map { |c| rt.f32(c) })
    end
    g['fragColor'].replace((rt.construct(4, result, rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
