# Generated by NoisemakerCpu::Transpiler - do not edit.
run_pixel = lambda do |ctx, out|
  rt = ctx.rt
  u = ctx.uniforms
  g = {}
  fetchTex__ivec2_ivec2_ivec2 = sampleBilinear__vec2_ivec2 = main__void = nil
  _retc = nil
  _u_resolution = u.key?('resolution') ? u['resolution'] : rt.construct(2, 0.0)
  _u_speed = u.key?('speed') ? u['speed'] : rt.f(0.0)
  _u_dyeDecay = u.key?('dyeDecay') ? u['dyeDecay'] : rt.f(0.0)
  _u_velocityDecay = u.key?('velocityDecay') ? u['velocityDecay'] : rt.f(0.0)
  _u_bufTex = ctx.texture_binding('bufTex')
  g['fragColor'] = rt.construct(4, 0.0)
  fetchTex__ivec2_ivec2_ivec2 = lambda do |idx, minIdx, maxIdx|
    idx = rt.copy(idx, 'int')
    minIdx = rt.copy(minIdx, 'int')
    maxIdx = rt.copy(maxIdx, 'int')
    return rt.texel_fetch(_u_bufTex, rt.component_wise('clamp', idx, minIdx, maxIdx), rt.i(0))
  end
  sampleBilinear__vec2_ivec2 = lambda do |uv, texSize|
    uv = rt.copy(uv, 'float')
    texSize = rt.copy(texSize, 'int')
    baseI = nil; f = nil; maxIdx = nil; minIdx = nil; texelPos = nil; v0 = nil; v00 = nil; v01 = nil; v1 = nil; v10 = nil; v11 = nil
    minIdx = rt.construct(2, rt.i(0), 'int')
    maxIdx = rt.binary('-', texSize, rt.construct(2, rt.i(1), 'int'), 2, 'int')
    texelPos = rt.construct(2, rt.binary('-', rt.binary('*', uv, rt.construct(2, texSize), 2, 'float'), rt.construct(2, rt.f(0.5)), 2, 'float'))
    baseI = rt.construct(2, rt.construct(2, rt.component_wise('floor', texelPos)), 'int')
    f = rt.construct(2, rt.component_wise('fract', texelPos))
    v00 = rt.construct(4, fetchTex__ivec2_ivec2_ivec2.call(baseI, minIdx, maxIdx))
    v10 = rt.construct(4, fetchTex__ivec2_ivec2_ivec2.call(rt.binary('+', baseI, rt.construct(2, rt.i(1), rt.i(0), 'int'), 2, 'int'), minIdx, maxIdx))
    v01 = rt.construct(4, fetchTex__ivec2_ivec2_ivec2.call(rt.binary('+', baseI, rt.construct(2, rt.i(0), rt.i(1), 'int'), 2, 'int'), minIdx, maxIdx))
    v11 = rt.construct(4, fetchTex__ivec2_ivec2_ivec2.call(rt.binary('+', baseI, rt.construct(2, rt.i(1), rt.i(1), 'int'), 2, 'int'), minIdx, maxIdx))
    v0 = rt.construct(4, rt.component_wise('mix', v00, v10, rt.swizzle(f, 'x')))
    v1 = rt.construct(4, rt.component_wise('mix', v01, v11, rt.swizzle(f, 'x')))
    return rt.component_wise('mix', v0, v1, rt.swizzle(f, 'y'))
  end
  main__void = lambda do
    _u = nil; advected = nil; backUv = nil; dDecay = nil; dt = nil; fragCoord = nil; here = nil; newDye = nil; newVel = nil; texSize = nil; uv = nil; vDecay = nil
    texSize = rt.texture_size(_u_bufTex)
    fragCoord = rt.construct(2, rt.swizzle(ctx.frag_coord, 'xy'))
    uv = rt.construct(2, rt.binary('/', fragCoord, rt.construct(2, texSize), 2, 'float'))
    here = rt.construct(4, rt.texel_fetch(_u_bufTex, rt.component_wise('clamp', rt.construct(2, rt.construct(2, fragCoord), 'int'), rt.construct(2, rt.i(0), 'int'), rt.binary('-', texSize, rt.construct(2, rt.i(1), 'int'), 2, 'int')), rt.i(0)))
    _u = rt.construct(2, rt.swizzle(here, 'rg'))
    dt = rt.binary('*', rt.component_wise('clamp', _u_speed, rt.f(0), rt.f(200)), rt.f(0.0001), 1, 'float')
    backUv = rt.construct(2, rt.component_wise('clamp', rt.binary('-', uv, rt.binary('*', _u, dt, 2, 'float'), 2, 'float'), rt.construct(2, rt.f(0)), rt.construct(2, rt.f(1))))
    advected = rt.construct(4, sampleBilinear__vec2_ivec2.call(backUv, texSize))
    newVel = rt.construct(2, rt.swizzle(advected, 'rg'))
    newDye = rt.swizzle(advected, 'b')
    vDecay = rt.component_wise('pow', rt.binary('*', rt.component_wise('clamp', _u_velocityDecay, rt.f(0), rt.f(100)), rt.f(0.01), 1, 'float'), rt.binary('*', dt, rt.f(60), 1, 'float'))
    dDecay = rt.component_wise('pow', rt.binary('*', rt.component_wise('clamp', _u_dyeDecay, rt.f(0), rt.f(100)), rt.f(0.01), 1, 'float'), rt.binary('*', dt, rt.f(60), 1, 'float'))
    newVel.replace((rt.binary('*', newVel, vDecay, 2, 'float')).map { |c| rt.f32(c) })
    newDye = rt.binary('*', newDye, dDecay, 1, 'float')
    g['fragColor'].replace((rt.construct(4, newVel, newDye, rt.f(1))).map { |c| rt.f32(c) })
  end
  main__void.call
  c = g['fragColor']
  out[0] = rt.f32(c[0]); out[1] = rt.f32(c[1]); out[2] = rt.f32(c[2]); out[3] = rt.f32(c[3])
end
{ kernel: run_pixel, uses_derivatives: false }
